table 'Base Funcionários'
	lineageTag: fb1f8543-b5db-4982-a6f8-56f2939d3cfa

	column CODFILIAL
		dataType: int64
		lineageTag: 56056549-294f-4444-b202-44682c7bfd61
		summarizeBy: sum
		sourceColumn: CODFILIAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CHAPA
		dataType: string
		lineageTag: c661b493-104e-4969-9ea8-7adebc1ae44d
		summarizeBy: none
		sourceColumn: CHAPA

		annotation SummarizationSetBy = Automatic

	column DEPARTAMENTO
		dataType: string
		lineageTag: c29da394-0c91-4742-bfa6-2853b4295920
		summarizeBy: none
		sourceColumn: DEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	column SETOR
		dataType: string
		lineageTag: b399614c-1f59-4d04-a492-2986069635bf
		summarizeBy: none
		sourceColumn: SETOR

		annotation SummarizationSetBy = Automatic

	column TURNO
		dataType: string
		lineageTag: 147c4be0-3e8c-4934-8b80-1a2923789be4
		summarizeBy: none
		sourceColumn: TURNO

		annotation SummarizationSetBy = Automatic

	column _TK = 'Base Funcionários'[CODFILIAL]&'Base Funcionários'[CHAPA]
		lineageTag: 1574c70d-7074-407b-99cf-9f0e51f169f7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Turno = if ('Base Funcionários'[TURNO] in {"Administrativo","Primeiro Turno"}, "Diurno", "Noturno")
		lineageTag: 8f527d58-0e28-4043-ba7a-bf3afc682f79
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Base Funcionários-f9df49b4-ff8a-47ff-8145-d4ed34b970c4' = m
		mode: import
		queryGroup: 'Ponto Funcionário'
		source = ```
				let
				    // 1. Conexão SQL nativa no Oracle
				    Fonte = Oracle.Database("DATAVALE", [
				        Query = "SELECT * FROM DATAVALE.FPBI_FUNCIONARIOFLOWRM", 
				        HierarchicalNavigation = true
				    ]),
				
				    // 2. Filtro de filiais especificadas
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each [CODFILIAL] = 2 or [CODFILIAL] = 4 or [CODFILIAL] = 12 or [CODFILIAL] = 104 or [CODFILIAL] = 27 or [CODFILIAL] = 18 or [CODFILIAL] = 72),
				
				    // 3. Limpeza e ajuste dos textos de Departamento, Setor e Seção
				    #"Texto Aparado" = Table.TransformColumns(#"Linhas Filtradas", {{"DEPARTAMENTO", Text.Trim, type text}, {"SETOR", Text.Trim, type text}, {"SECAO", Text.Trim, type text}}),
				    #"Texto Limpo" = Table.TransformColumns(#"Texto Aparado", {{"DEPARTAMENTO", Text.Clean, type text}, {"SETOR", Text.Clean, type text}, {"SECAO", Text.Clean, type text}}),
				
				    // 4. Regra de negócio para classificação do TURNO
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Texto Limpo", "TURNO", each 
				        if Text.Contains([SECAO], "1º TURNO") then "Primeiro Turno" 
				        else if Text.Contains([SECAO], "2º TURNO") then "Segundo Turno" 
				        else if Text.Contains([SECAO], "3º TURNO") then "Segundo Turno" 
				        else if Text.Contains([SECAO], "2ºTURNO") then "Segundo Turno" 
				        else if Text.Contains([SECAO], "3ºTURNO") then "Segundo Turno" 
				        else if Text.Contains([SECAO], "1ºTURNO") then "Primeiro Turno" 
				        else "Administrativo", 
				        type text
				    ),
				
				    // 5. Seleção final das colunas para o modelo
				    #"Columns removed by Measure Killer" = Table.SelectColumns(#"Coluna Condicional Adicionada", {
				        "DEPARTAMENTO",
				        "CODFILIAL",
				        "SETOR",
				        "CHAPA",
				        "TURNO"
				    })
				in
				    #"Columns removed by Measure Killer"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

