table 'Cadastro de Produto'
	lineageTag: 492ab4b2-312f-4050-9905-2e2eb9fe8c10

	column SEQPRODUTO
		dataType: int64
		formatString: 0
		lineageTag: 358f38fe-c49c-4274-9892-ada81a73b124
		summarizeBy: none
		sourceColumn: SEQPRODUTO

		annotation SummarizationSetBy = Automatic

	column GRUPOPRODUTO
		dataType: string
		lineageTag: cfb61812-47ae-4e1a-aa50-fbf1c741cb01
		summarizeBy: none
		sourceColumn: GRUPOPRODUTO

		annotation SummarizationSetBy = Automatic

	partition 'Cadastro de Produto' = m
		mode: import
		source =
				let
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true, Query="SELECT * FROM DATAVALE.dgevpb_cadastroproduto"]),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([STATUSPRODUTO] = "Ativo") and ([TIPOPRODUTO] = "CARNES E INDUSTRIALIZADOS") and ([SUBGRUPOPRODUTO] <> "13-SUB-PRODUTOS BOVINOS - TRIP" and [SUBGRUPOPRODUTO] <> "13-SUB-PRODUTOS BOVINOS -DESOS" and [SUBGRUPOPRODUTO] <> "13-SUB-PRODUTOS BOVINOS- MIUDO" and [SUBGRUPOPRODUTO] <> "13-SUB-PRODUTOS SUINOS EXP DES" and [SUBGRUPOPRODUTO] <> "13-SUB-PRODUTOS SUINOS-DESOSSA" and [SUBGRUPOPRODUTO] <> "14-GRAXARIA" and [SUBGRUPOPRODUTO] <> "17-TRIPAS BOVINAS EXPORTAÇÃO" and [SUBGRUPOPRODUTO] <> "51 - MATERIA-PRIMA EMB-MIUDOS " and [SUBGRUPOPRODUTO] <> "51- MATERIA PRIMA -MIUDOS" and [SUBGRUPOPRODUTO] <> "51-CARNE -MATERIA PRIMA" and [SUBGRUPOPRODUTO] <> "51-EMBUTIDOS- MATERIA PRIMA" and [SUBGRUPOPRODUTO] <> "51-EMBUTIDOS-MATERIA PRIMA" and [SUBGRUPOPRODUTO] <> "51-MATERIA PRIMA MUIDOS SUINO" and [SUBGRUPOPRODUTO] <> "51-MATERIA-PRIMA EMBUTIDOS" and [SUBGRUPOPRODUTO] <> "GRAXARIA" and [SUBGRUPOPRODUTO] <> "GRAXARIA ABATE" and [SUBGRUPOPRODUTO] <> "GRAXARIA DESOSSA" and [SUBGRUPOPRODUTO] <> "GRAXARIA SALGA" and [SUBGRUPOPRODUTO] <> "MAT. PRIMA DESOSSA P/EMBUTIDO" and [SUBGRUPOPRODUTO] <> "MATERIA PRIMA DESOS- TCHE" and [SUBGRUPOPRODUTO] <> "MATERIA PRIMA INDUSTRIALIZADO" and [SUBGRUPOPRODUTO] <> "MATERIA PRIMA MIUDOS - TCHE" and [SUBGRUPOPRODUTO] <> "MATERIA PRIMA MIUDOS CONG-TCHE" and [SUBGRUPOPRODUTO] <> "MATERIA-PRIMA TRIPARIA" and [SUBGRUPOPRODUTO] <> "QUEIJOS" and [SUBGRUPOPRODUTO] <> "RESIDUOS " and [SUBGRUPOPRODUTO] <> "TEMPERO")),
				    #"Columns removed by Measure Killer"= Table.SelectColumns(#"Linhas Filtradas",{"GRUPOPRODUTO","SEQPRODUTO"})
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

