table Calendário
	lineageTag: 5ff9e005-e885-4a6a-9d27-4a19808850d4

	column Data
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 894f966c-542e-415d-83ff-8037af65e157
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: b157ea83-ae81-49c3-adea-c0786db2da70
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: int64
		formatString: 0
		lineageTag: 3dbeb3cf-6d02-436f-ba76-534a879b76bf
		summarizeBy: sum
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column MesNo
		dataType: int64
		formatString: 0
		lineageTag: fb117a70-be7c-4260-9339-b12c6aa77449
		summarizeBy: sum
		sourceColumn: MesNo

		annotation SummarizationSetBy = Automatic

	column Dia
		dataType: int64
		formatString: 0
		lineageTag: 033b2c12-faa9-4207-859a-d9e3399c7f56
		summarizeBy: sum
		sourceColumn: Dia

		annotation SummarizationSetBy = Automatic

	column AnoMesDia
		dataType: int64
		formatString: 0
		lineageTag: d8abb4b1-72b9-4021-8a44-b78d8edd1a9c
		summarizeBy: sum
		sourceColumn: AnoMesDia

		annotation SummarizationSetBy = Automatic

	column Mês
		dataType: string
		lineageTag: bbcc5652-0a05-49ca-9fab-4bfa75735214
		summarizeBy: none
		sourceColumn: Mês
		sortByColumn: MesNo

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Mês/Ano
		dataType: string
		lineageTag: eadd9c6f-ea7c-4d14-96d6-d0f3101cd1af
		summarizeBy: none
		sourceColumn: Mês/Ano

		annotation SummarizationSetBy = Automatic

	column Trimestre/Ano
		dataType: string
		lineageTag: 0a5f1736-c2e1-49c5-b4b0-5c30f1f32f8f
		summarizeBy: none
		sourceColumn: Trimestre/Ano

		annotation SummarizationSetBy = Automatic

	column 'Dia da Semana'
		dataType: int64
		formatString: 0
		lineageTag: 17d9ea7e-5ad5-47b7-81fb-0e54ba8291c1
		summarizeBy: sum
		sourceColumn: Dia da Semana

		annotation SummarizationSetBy = Automatic

	column 'Nome do Dia'
		dataType: string
		lineageTag: e538dde6-7513-4f68-8373-7c24fdab8fea
		summarizeBy: none
		sourceColumn: Nome do Dia

		annotation SummarizationSetBy = Automatic

	column 'Semana do Ano'
		dataType: int64
		formatString: 0
		lineageTag: 6f39dcc5-6d42-4746-a70f-5fdc0098fd8f
		summarizeBy: sum
		sourceColumn: Semana do Ano

		annotation SummarizationSetBy = Automatic

	column Semana/Ano
		dataType: string
		lineageTag: d87e42d5-189b-495d-9919-de82777e448c
		summarizeBy: none
		sourceColumn: Semana/Ano

		annotation SummarizationSetBy = Automatic

	column AnoSemana
		dataType: int64
		formatString: 0
		lineageTag: e851c516-ef7d-4ca1-8e9f-ae9b465ece00
		summarizeBy: sum
		sourceColumn: AnoSemana

		annotation SummarizationSetBy = Automatic

	column AnoMes
		dataType: int64
		formatString: 0
		lineageTag: 04965b0d-d0b2-40f1-96bc-aa0450ad5c21
		summarizeBy: sum
		sourceColumn: AnoMes
		sortByColumn: MesNo

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column AnoTrimestre
		dataType: int64
		formatString: 0
		lineageTag: 52deb96f-6d61-4b0b-bf0a-e6f49e10714e
		summarizeBy: sum
		sourceColumn: AnoTrimestre

		annotation SummarizationSetBy = Automatic

	column 'Ano Fiscal'
		dataType: string
		lineageTag: 30f30daa-6da5-4257-a580-0ea8f454f701
		summarizeBy: none
		sourceColumn: Ano Fiscal

		annotation SummarizationSetBy = Automatic

	column 'Trimestre Fiscal'
		dataType: string
		lineageTag: e97ce812-8929-43e1-9d75-f351d63a67de
		summarizeBy: none
		sourceColumn: Trimestre Fiscal

		annotation SummarizationSetBy = Automatic

	column 'Mês Fiscal'
		dataType: int64
		formatString: 0
		lineageTag: 08e4ca90-6b0c-4848-909a-d6f842225045
		summarizeBy: sum
		sourceColumn: Mês Fiscal

		annotation SummarizationSetBy = Automatic

	column Futuro
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: bf60311e-5a5d-4ddf-b176-88343d61e5ca
		summarizeBy: none
		sourceColumn: Futuro

		annotation SummarizationSetBy = Automatic

	column 'Dia Útil'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9a6f6e43-53de-4b32-acc7-9b2a056dc666
		summarizeBy: none
		sourceColumn: Dia Útil

		annotation SummarizationSetBy = Automatic

	column 'Offset Dia'
		dataType: int64
		formatString: 0
		lineageTag: 245f331f-e160-40b4-8e3f-a4e8f2dc415a
		summarizeBy: sum
		sourceColumn: Offset Dia

		annotation SummarizationSetBy = Automatic

	column 'Offset Semana'
		dataType: int64
		formatString: 0
		lineageTag: f485dbfd-d1ce-4d0f-9a3e-eae267c64fce
		summarizeBy: sum
		sourceColumn: Offset Semana

		annotation SummarizationSetBy = Automatic

	column 'Offset Mês'
		dataType: int64
		formatString: 0
		lineageTag: 8cab12c1-8692-40a5-afbc-249ba4d1b3a3
		summarizeBy: sum
		sourceColumn: Offset Mês

		annotation SummarizationSetBy = Automatic

	column 'Offset Trimestre'
		dataType: int64
		formatString: 0
		lineageTag: ffc7af4e-db45-4b8b-a5eb-ebd4e6da3206
		summarizeBy: sum
		sourceColumn: Offset Trimestre

		annotation SummarizationSetBy = Automatic

	column 'Offset Ano'
		dataType: int64
		formatString: 0
		lineageTag: 145c1928-3fe2-4675-aa9e-be388a0eb9d8
		summarizeBy: sum
		sourceColumn: Offset Ano

		annotation SummarizationSetBy = Automatic

	column 'Offset Ano Fiscal'
		dataType: int64
		formatString: 0
		lineageTag: 11e124ae-be8c-43eb-9509-e470c155d86a
		summarizeBy: sum
		sourceColumn: Offset Ano Fiscal

		annotation SummarizationSetBy = Automatic

	column 'Semana Completa'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 325d29a8-078a-41e8-b662-27c5d133263f
		summarizeBy: none
		sourceColumn: Semana Completa

		annotation SummarizationSetBy = Automatic

	column 'Mês Completo'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4eee74b6-d270-427c-b68b-dcd4fef8ba3b
		summarizeBy: none
		sourceColumn: Mês Completo

		annotation SummarizationSetBy = Automatic

	column 'Trimestre Completo'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 82691520-7e43-4b97-aa54-95907135089a
		summarizeBy: none
		sourceColumn: Trimestre Completo

		annotation SummarizationSetBy = Automatic

	column 'Mês/Ano Fechamento'
		dataType: string
		lineageTag: 93712ceb-cbc3-4b23-acd6-7961269d5f70
		summarizeBy: none
		sourceColumn: Mês/Ano Fechamento

		annotation SummarizationSetBy = Automatic

	column 'AnoMes Fechamento'
		dataType: int64
		formatString: 0
		lineageTag: 7ba1d762-e706-40c3-b5f4-5a3f698f1bf7
		summarizeBy: sum
		sourceColumn: AnoMes Fechamento

		annotation SummarizationSetBy = Automatic

	column _DataDia = 'Calendário'[Data] &" - "&LEFT('Calendário'[Nome do Dia],3)
		lineageTag: a2eead22-088f-4210-83e0-155652c9d334
		summarizeBy: none
		sortByColumn: Data

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column '_Filtro RH' = IF('Calendário'[AnoMes Fechamento] IN {202301,202302,202303},1,0)
		formatString: 0
		lineageTag: 1344a431-2649-421e-b9b1-d5790d2a7056
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column _Mês/Ano = DATE(YEAR('Calendário'[Data]),MONTH('Calendário'[Data]),1)
		formatString: General Date
		lineageTag: 73f7a783-c7af-4a55-b55d-51349e9ad4e6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DiaUtilMeta = ```
			
			VAR DiaSemana = WEEKDAY('Calendário'[Data], 2 )   -- 2 = semana começa na segunda
			RETURN
			IF( DiaSemana <= 5, 1, 0 )
			
			```
		formatString: 0
		lineageTag: 4b90b567-4775-4671-aac9-b87d664d9178
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column InicioDoMesMeta = EOMONTH('Calendário'[Data], -1) + 1
		formatString: General Date
		lineageTag: 2a84827d-21ed-42fd-8b70-c14b68a5b43d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Calendário-bcbc94e3-2c90-4505-a948-003cd8de74ce = m
		mode: import
		source = ```
				let
				    //AnoMinDinamico = Date.Year(List.Min(fVendas[Data Venda])),
				    //AnoMaxDinamico = Date.Year(List.Max(fVendas[Data Venda])),
				    //DataInicio = #date(AnoMinDinamico, 1, 1),
				    //DataFim = #date(AnoMaxDinamico, 12, 31),
				    DataInicio = #date(AnoMin, 1, 1),
				    DataFim = #date(AnoMax, 12, 31),
				    DataAtual = DateTime.Date(DateTime.FixedLocalNow()),
				    QtdDias = Duration.Days(Duration.From(DataFim - DataInicio))+1,
				    Fonte = List.Dates(DataInicio,QtdDias,#duration(1,0,0,0)),
				    CriaTabela = Table.FromList(Fonte, Splitter.SplitByNothing()),   
				    TipoAlterado1 = Table.TransformColumnTypes(CriaTabela,{{"Column1", type date}}),
				    RenomeiaColuna = Table.RenameColumns(TipoAlterado1,{{"Column1", "Data"}}),
				    InsereAno = Table.AddColumn(RenomeiaColuna, "Ano", each Date.Year([Data]), type number),
				    InsereTrimestre = Table.AddColumn(InsereAno, "Trimestre", each Date.QuarterOfYear([Data]), type number),
				    InsereMesNo = Table.AddColumn(InsereTrimestre, "MesNo", each Date.Month([Data]), type number),
				    InsereDia = Table.AddColumn(InsereMesNo, "Dia", each Date.Day([Data]), type number),
				    InsereAnoMesDia = Table.AddColumn(InsereDia, "AnoMesDia", each [Ano] * 10000 + [MesNo] * 100 + [Dia], type number),
				    InsereMes = Table.AddColumn(InsereAnoMesDia, "Mês", each Date.ToText([Data], "MMMM"), type text),
				    InsereMesAno = Table.AddColumn(InsereMes, "Mês/Ano", each (try(Text.Range([Mês],0,3)) otherwise [Mês]) & "/" & Number.ToText([Ano]), type text),
				    InsereTrimestreAno = Table.AddColumn(InsereMesAno, "Trimestre/Ano", each "T" & Number.ToText([Trimestre]) & "/" & Number.ToText([Ano]), type text),
				    InsereDiaSemana = Table.AddColumn(InsereTrimestreAno, "Dia da Semana", each Date.DayOfWeek([Data]), Int64.Type),
				    InsereNomeDia = Table.AddColumn(InsereDiaSemana, "Nome do Dia", each Date.ToText([Data], "dddd"), type text),
				    InsereSemanaDoAno= Table.AddColumn(InsereNomeDia, "Semana do Ano", each Date.WeekOfYear([Data]), type number),
				    InsereSemanaAno = Table.AddColumn(InsereSemanaDoAno, "Semana/Ano", each "S" & Text.From([Semana do Ano]) & "/" & Text.From([Ano]), type text ),
				    InsereAnoSemana = Table.AddColumn(InsereSemanaAno, "AnoSemana", each [Ano] * 100 + [Semana do Ano], type number),
				    InsereAnoMes = Table.AddColumn(InsereAnoSemana , "AnoMes", each [Ano] * 100 + [MesNo], type number),
				    InsereAnoTrimestre = Table.AddColumn(InsereAnoMes, "AnoTrimestre", each [Ano] * 100 + [Trimestre], type number),
				    InsereAnoFiscal = Table.AddColumn(InsereAnoTrimestre, "Ano Fiscal", each (if MesInicioAnoFiscal = 1 then Text.From([Ano]) & "/" & Text.From([Ano] + 1) else if [MesNo]>=MesInicioAnoFiscal then Text.From([Ano]) & "/" & Text.From([Ano] + 1) else Text.From([Ano] - 1) & "/" & Text.From([Ano])), type text),
				    InsereTrimestreFiscal = Table.AddColumn(InsereAnoFiscal, "Trimestre Fiscal", each "FT" & Text.From( Number.RoundUp( Date.Month( Date.AddMonths( [Data], - (MesInicioAnoFiscal - 1) )) / 3 )), type text),
				    InsereMesFiscal = Table.AddColumn(InsereTrimestreFiscal, "Mês Fiscal", each if [MesNo]>=MesInicioAnoFiscal then [MesNo]-(MesInicioAnoFiscal-1) else [MesNo]+(12-MesInicioAnoFiscal+1), type text),
				
				    InsereFlagFuturo = Table.AddColumn(InsereMesFiscal, "Futuro", each not ([Data] <= Date.From(DataAtual)), type logical),
				    InsereFlagDiaUtil = Table.AddColumn(InsereFlagFuturo, "Dia Útil", each if [Dia da Semana] = 6 then false else if [Dia da Semana] = 0 then false else true, type logical),
				
				    InsereOffsetDia = Table.AddColumn(InsereFlagDiaUtil, "Offset Dia", each Number.From([Data] - DataAtual), type number),
				    InsereOffsetSemana = Table.AddColumn(InsereOffsetDia, "Offset Semana", each (Number.From(Date.StartOfWeek([Data]))-Number.From(Date.StartOfWeek(DateTime.LocalNow())))/7, type number),
				    InsereOffsetMes = Table.AddColumn(InsereOffsetSemana, "Offset Mês", each ((12 * Date.Year([Data])) +  Date.Month([Data])) - ((12 * Date.Year(Date.From(DataAtual))) +  Date.Month(Date.From(DataAtual))), type number),
				    InsereOffsetTrimestre = Table.AddColumn(InsereOffsetMes, "Offset Trimestre", each ((4 * Date.Year([Data])) +  Date.QuarterOfYear([Data])) - ((4 * Date.Year(Date.From(DataAtual))) +  Date.QuarterOfYear(Date.From(DataAtual))), type number),
				    InsereOffsetAno = Table.AddColumn(InsereOffsetTrimestre, "Offset Ano", each Date.Year([Data]) - Date.Year(Date.From(DataAtual)), type number),
				
				    IdentificaDiaAtual = Table.SelectRows(InsereOffsetAno, each ([Data] = DataAtual)),
				    AnoFiscalAtual = IdentificaDiaAtual{0}[Ano Fiscal], 
				    InsereOffsetAnoFiscal = Table.AddColumn(InsereOffsetAno, "Offset Ano Fiscal", each Number.From(Text.Range([Ano Fiscal],2,2)) - Number.From(Text.Range(AnoFiscalAtual,2,2)), type number),
				
				    InsereSemanaCompleta = Table.AddColumn(InsereOffsetAnoFiscal, "Semana Completa", each Date.EndOfWeek([Data]) < Date.From(Date.EndOfWeek(DataAtual)), type logical),
				    InsereMesCompleto = Table.AddColumn(InsereSemanaCompleta, "Mês Completo", each Date.EndOfMonth([Data]) < Date.From(Date.EndOfMonth(DataAtual)), type logical),
				    InsereTrimestreCompleto = Table.AddColumn(InsereMesCompleto, "Trimestre Completo", each Date.EndOfQuarter([Data]) < Date.From(Date.EndOfQuarter(DataAtual)), type logical),
				    IdentificaOffsetMes = Table.AddColumn(InsereTrimestreCompleto, "MesOffsetFechamento", each if DiaInicioMes = 1 then [Offset Mês] else if DiaInicioMes > [Dia] then [Offset Mês] else [Offset Mês] + 1),
				    RemoveDuplicados = Table.Distinct(IdentificaOffsetMes, {"Offset Mês"}),
				    MesclaConsultas = Table.NestedJoin(IdentificaOffsetMes, {"MesOffsetFechamento"}, RemoveDuplicados, {"Offset Mês"}, "Join", JoinKind.LeftOuter),
				    #"Join Expandido" = Table.ExpandTableColumn(MesclaConsultas, "Join", {"Mês/Ano", "AnoMes"}, {"Mês/Ano Fechamento", "AnoMes Fechamento"}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Join Expandido",{"MesOffsetFechamento"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Removidas",{{"Data", type date}, {"Ano", Int64.Type}, {"Trimestre", Int64.Type}, {"MesNo", Int64.Type}, {"Dia", Int64.Type}, {"AnoMesDia", Int64.Type}, {"Mês", type text}, {"Mês/Ano", type text}, {"Trimestre/Ano", type text}, {"Dia da Semana", Int64.Type}, {"Nome do Dia", type text}, {"Semana do Ano", Int64.Type}, {"Semana/Ano", type text}, {"AnoSemana", Int64.Type}, {"AnoMes", Int64.Type}, {"AnoTrimestre", Int64.Type}, {"Ano Fiscal", type text}, {"Trimestre Fiscal", type text}, {"Mês Fiscal", Int64.Type}, {"Futuro", type logical}, {"Dia Útil", type logical}, {"Offset Dia", Int64.Type}, {"Offset Semana", Int64.Type}, {"Offset Mês", Int64.Type}, {"Offset Trimestre", Int64.Type}, {"Offset Ano", Int64.Type}, {"Offset Ano Fiscal", Int64.Type}, {"Semana Completa", type logical}, {"Mês Completo", type logical}, {"Trimestre Completo", type logical}, {"Mês/Ano Fechamento", type text}, {"AnoMes Fechamento", Int64.Type}})
				in
				    #"Tipo Alterado"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

