table DCEV_CONSUMOALMOXARIFADO
	lineageTag: 49768053-6f15-46ae-a178-33a7f5993003

	column NROEMPRESA
		dataType: int64
		formatString: 0
		lineageTag: 8ad2a665-cb2c-4ca6-87a2-32abaa711329
		summarizeBy: none
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

	column SEQPRODUTO
		dataType: int64
		formatString: 0
		lineageTag: 4a9eb13f-f393-48af-987b-8b650d889c37
		summarizeBy: sum
		sourceColumn: SEQPRODUTO

		annotation SummarizationSetBy = Automatic

	column DTALANCAMENTO
		dataType: dateTime
		formatString: General Date
		lineageTag: ae4f28e1-cb45-4fde-9ce0-375809103977
		summarizeBy: none
		sourceColumn: DTALANCAMENTO

		annotation SummarizationSetBy = Automatic

	column QUANTIDADE
		dataType: double
		lineageTag: c8acbd18-beb0-4107-8618-7d72b6534adc
		summarizeBy: sum
		sourceColumn: QUANTIDADE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLRUNITARIO
		dataType: double
		lineageTag: b0796b3b-8491-450a-8a60-0e2d8e9fb631
		summarizeBy: sum
		sourceColumn: VLRUNITARIO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DESCRGRUPOPROD
		dataType: string
		lineageTag: ced39b47-94d7-4467-931c-cfd4a9855ce9
		summarizeBy: none
		sourceColumn: DESCRGRUPOPROD

		annotation SummarizationSetBy = Automatic

	column DESCRSUBGRUPOPROD
		dataType: string
		lineageTag: 4ec9d19b-a9e1-4a6f-b833-b230b02dfdaf
		summarizeBy: none
		sourceColumn: DESCRSUBGRUPOPROD

		annotation SummarizationSetBy = Automatic

	partition DCEV_CONSUMOALMOXARIFADO = m
		mode: import
		queryGroup: 'Fluxo Industrial'
		source =
				let
				    // 1. Conexão SQL nativa direto na tabela do Oracle
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true, Query="#(lf)            SELECT #(lf) QUANTIDADE,#(lf)VLRUNITARIO,#(lf)SEQPRODUTO,#(lf)NROEMPRESA,#(lf)DTALANCAMENTO,#(lf)DESCRGRUPOPROD,#(lf)DESCRSUBGRUPOPROD#(lf)#(lf)            FROM DATAVALE.DCEV_CONSUMOALMOXARIFADO #(lf)            WHERE DTALANCAMENTO >= '01/JAN/2026'#(lf)        "]),
				
				    // 2. Filtro pelo grupo de produtos
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([DESCRGRUPOPROD] = "LUBRIFICANTES E COMBUSTIVEIS"))
				in
				    #"Linhas Filtradas"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

