table DCUVQ_COMPRAGADOPRAZO
	lineageTag: 23de9fb7-9cda-4858-9b2f-3ca7a369176e

	column NROEMPRESA
		dataType: int64
		formatString: 0
		lineageTag: bc54f253-313d-4262-b661-7c42d571cc57
		summarizeBy: none
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

	column NROPEDIDO
		dataType: int64
		formatString: 0
		lineageTag: 0208978b-c1be-4a00-a864-bf7d3154bc93
		summarizeBy: none
		sourceColumn: NROPEDIDO

		annotation SummarizationSetBy = Automatic

	column SEQPRODUTOR
		dataType: int64
		formatString: 0
		lineageTag: 4b92cc42-ce98-4495-a701-b6b120efb078
		summarizeBy: none
		sourceColumn: SEQPRODUTOR

		annotation SummarizationSetBy = Automatic

	column SEQPRODUTO
		dataType: int64
		formatString: 0
		lineageTag: b4d2161b-52c3-4c60-804b-0b9b0527fe0a
		summarizeBy: sum
		sourceColumn: SEQPRODUTO

		annotation SummarizationSetBy = Automatic

	column PRODUTO
		dataType: string
		lineageTag: 6361b5f4-f09c-422d-a33b-1b7fb3e626ab
		summarizeBy: none
		sourceColumn: PRODUTO

		annotation SummarizationSetBy = Automatic

	column QUANTIDADE
		dataType: double
		lineageTag: 2ea5b8c5-42d8-42ee-8fa3-3390f9dd6e57
		summarizeBy: sum
		sourceColumn: QUANTIDADE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PESO
		dataType: double
		lineageTag: 184361c9-7f60-41db-8fb8-90ae8ae95b5f
		summarizeBy: sum
		sourceColumn: PESO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PESOVIVO
		dataType: double
		lineageTag: cd151b98-d591-4125-8aa5-7cdcc07f71ca
		summarizeBy: sum
		sourceColumn: PESOVIVO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLRPRODUTO
		dataType: double
		lineageTag: d7d654e4-aa68-4894-8cb1-9cd44daa3c05
		summarizeBy: sum
		sourceColumn: VLRPRODUTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLRICMS
		dataType: double
		lineageTag: 8aaf0a18-a38e-4d45-a2c2-90a4aa421418
		summarizeBy: sum
		sourceColumn: VLRICMS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLRCOMISSAO
		dataType: double
		lineageTag: d95dabb4-2380-4bb9-bc86-fca20a617e5d
		summarizeBy: sum
		sourceColumn: VLRCOMISSAO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLRFRETE
		dataType: double
		lineageTag: 27db96c2-08bc-48dd-8a4a-7243fa864c1b
		summarizeBy: sum
		sourceColumn: VLRFRETE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLRICMSFRETE
		dataType: double
		lineageTag: fe56949d-5de8-4d16-9d08-4ca59cbbf973
		summarizeBy: sum
		sourceColumn: VLRICMSFRETE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _ConcProduto = DCUVQ_COMPRAGADOPRAZO[SEQPRODUTO]&" - "&DCUVQ_COMPRAGADOPRAZO[PRODUTO]
		lineageTag: bf9eb42b-447a-4c6c-887a-0c501128b219
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PRAZO
		dataType: int64
		formatString: 0
		lineageTag: ae702033-39b4-4058-ab0a-f7f5dc8b760b
		summarizeBy: sum
		sourceColumn: PRAZO

		annotation SummarizationSetBy = Automatic

	column _Origem = IF(or(DCUVQ_COMPRAGADOPRAZO[SEQPRODUTOR] IN { 108386 , 109457 , 164805 , 180622}, RELATED(FPBI_PESSOA[GRUPO]) in {"INTEGRADOS - TERMINACAO","INTEGRADOS - CRECHE","INTEGRADOS - CRECHE REFUGO","INTEGRADOS - UPL", "INTEGRADOS - TERMINACAO REFUGO"}), "Próprio", IF(DCUVQ_COMPRAGADOPRAZO[SEQPRODUTOR] = 248257, "Boitel", "Terceiro"))
		lineageTag: 3ab5b173-b14f-49d6-a054-004723d5644d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DATATESTE = DCUVQ_COMPRAGADOPRAZO[Aux Compra.DATA]
		formatString: General Date
		lineageTag: d7c3f20b-4ee1-4771-8d2f-a041630d83eb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Funrural = CALCULATE(SUM(EXCEL_FUNRURAL[%]),FILTER(EXCEL_FUNRURAL,EXCEL_FUNRURAL[SEQPRODUTOR]=DCUVQ_COMPRAGADOPRAZO[SEQPRODUTOR]))
		lineageTag: 1fd779a0-769b-4bed-89db-f9f37a77b582
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Valor Funrural' = DCUVQ_COMPRAGADOPRAZO[VLRPRODUTO] * DCUVQ_COMPRAGADOPRAZO[Funrural]
		lineageTag: 42861906-6b32-4ae3-8660-aef651fdd872
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pk = DCUVQ_COMPRAGADOPRAZO[NROEMPRESA]&DCUVQ_COMPRAGADOPRAZO[NROPEDIDO]
		lineageTag: 9b28187b-5e81-47fc-82bf-3dad6caa3d53
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _VlrCompra =
			
			VAR COMPRAEMP4 = CALCULATE(SUM('EXCEL_COMPLEMENTOAUX'[Valor Complemento]),
			    FILTER('EXCEL_COMPLEMENTOAUX',
			    'EXCEL_COMPLEMENTOAUX'[Data Abate] = DCUVQ_COMPRAGADOPRAZO[DATATESTE] &&
			    'EXCEL_COMPLEMENTOAUX'[Nro Empresa] = DCUVQ_COMPRAGADOPRAZO[NROEMPRESA] &&
			    'EXCEL_COMPLEMENTOAUX'[Nro Pedido] = DCUVQ_COMPRAGADOPRAZO[NROPEDIDO]))
			RETURN
			    SWITCH(
			        TRUE(), DCUVQ_COMPRAGADOPRAZO[NROEMPRESA] = 4,COMPRAEMP4,0)
		lineageTag: e37e8646-1245-44f7-b21a-31304b32c97a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _ValorCompraProp = ```
			
			VAR COMPRA  = CALCULATE(
			    SUM(DCUVQ_COMPRAGADOPRAZO[VLRPRODUTO]),
			    ALLEXCEPT(DCUVQ_COMPRAGADOPRAZO,DCUVQ_COMPRAGADOPRAZO[NROPEDIDO],DCUVQ_COMPRAGADOPRAZO[DATATESTE],DCUVQ_COMPRAGADOPRAZO[NROEMPRESA]))
			VAR QUANTIDADE = CALCULATE(
			    SUM(DCUVQ_COMPRAGADOPRAZO[QUANTIDADE]),
			    ALLEXCEPT(DCUVQ_COMPRAGADOPRAZO,DCUVQ_COMPRAGADOPRAZO[NROPEDIDO],DCUVQ_COMPRAGADOPRAZO[DATATESTE],DGE_EMPRESAMATRIZ[NROEMPRESA]))
			VAR PROP = DIVIDE(DCUVQ_COMPRAGADOPRAZO[QUANTIDADE],QUANTIDADE)
			RETURN IF(DCUVQ_COMPRAGADOPRAZO[_VlrCompra] > 0, PROP)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 397ef172-f78c-459c-a1e3-c384399fb40a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '_Valor Complemento' = DCUVQ_COMPRAGADOPRAZO[_VlrCompra]*DCUVQ_COMPRAGADOPRAZO[_ValorCompraProp]
		lineageTag: 80552e74-6a97-4ce3-9c8c-1ef846fbfe7e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DATAREALABATE
		type: calculated
		lineageTag: c2116fc5-00ea-47e5-a51e-23d26c953a18
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Mesclado
		dataType: string
		lineageTag: dafc005d-80f4-4d09-86d8-b73e44714541
		summarizeBy: none
		sourceColumn: Mesclado

		annotation SummarizationSetBy = Automatic

	column 'Aux Compra.DATA'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6ec3a7b4-27a3-46f4-84d3-045b4658392e
		summarizeBy: none
		sourceColumn: Aux Compra.DATA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _Pesovivocomplemento =
			
			VAR PESOEMP4 = CALCULATE(SUM('EXCEL_PESOVIVOAUX'[Peso Vivo Graxaria]),
			    FILTER('EXCEL_PESOVIVOAUX',
			    'EXCEL_PESOVIVOAUX'[Data] = DCUVQ_COMPRAGADOPRAZO[DATATESTE] &&
			    'EXCEL_PESOVIVOAUX'[Nro Empresa] = DCUVQ_COMPRAGADOPRAZO[NROEMPRESA] &&
			    'EXCEL_PESOVIVOAUX'[Nro Pedido] = DCUVQ_COMPRAGADOPRAZO[NROPEDIDO]))
			RETURN
			    SWITCH(
			        TRUE(), DCUVQ_COMPRAGADOPRAZO[NROEMPRESA] = 4,PESOEMP4,0)
		lineageTag: 17c04dc1-952a-48d7-9137-10e24eac6403
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _PesovivoProp = ```
			
			VAR COMPRA  = CALCULATE(
			    SUM(DCUVQ_COMPRAGADOPRAZO[VLRPRODUTO]),
			    ALLEXCEPT(DCUVQ_COMPRAGADOPRAZO,DCUVQ_COMPRAGADOPRAZO[NROPEDIDO],DCUVQ_COMPRAGADOPRAZO[DATATESTE],DCUVQ_COMPRAGADOPRAZO[NROEMPRESA]))
			VAR QUANTIDADE = CALCULATE(
			    SUM(DCUVQ_COMPRAGADOPRAZO[QUANTIDADE]),
			    ALLEXCEPT(DCUVQ_COMPRAGADOPRAZO,DCUVQ_COMPRAGADOPRAZO[NROPEDIDO],DCUVQ_COMPRAGADOPRAZO[DATATESTE],DGE_EMPRESAMATRIZ[NROEMPRESA]))
			VAR PROP = DIVIDE(DCUVQ_COMPRAGADOPRAZO[QUANTIDADE],QUANTIDADE)
			RETURN IF(DCUVQ_COMPRAGADOPRAZO[_Pesovivocomplemento] > 0, PROP)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 92b7d3e3-79bc-437c-a409-cf5767165d88
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '_Peso Vivo' = DCUVQ_COMPRAGADOPRAZO[_Pesovivocomplemento]*DCUVQ_COMPRAGADOPRAZO[_PesovivoProp]
		lineageTag: d6bf2d0c-57e1-4224-9278-1492ff0483c2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CODLINK
		dataType: double
		lineageTag: bd6a5b3f-75a5-4bea-b912-e69207a24862
		summarizeBy: sum
		sourceColumn: CODLINK

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TABLINK
		dataType: string
		lineageTag: a69ac6b2-c83b-4690-8658-8765cc4029fb
		summarizeBy: none
		sourceColumn: TABLINK

		annotation SummarizationSetBy = Automatic

	column DATACHEGADA
		dataType: dateTime
		formatString: General Date
		lineageTag: 3b5385eb-55a3-4eeb-bff6-118b51226317
		summarizeBy: none
		sourceColumn: DATACHEGADA

		annotation SummarizationSetBy = Automatic

	column DATA
		dataType: dateTime
		formatString: General Date
		lineageTag: 61cf9d77-6b0a-4a4b-8503-1e690050a8ae
		summarizeBy: none
		sourceColumn: DATA

		annotation SummarizationSetBy = Automatic

	column TIPONOTA
		dataType: string
		lineageTag: 5971cd06-1a4a-4452-ab26-abf94813aa97
		summarizeBy: none
		sourceColumn: TIPONOTA

		annotation SummarizationSetBy = Automatic

	column ANOMES
		dataType: double
		lineageTag: e4a08d06-e98c-4445-b8f6-860d55104e30
		summarizeBy: sum
		sourceColumn: ANOMES

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SEQPEDIDO
		dataType: int64
		formatString: 0
		lineageTag: e48e4776-ebdc-49e9-8a81-0cf844830c0f
		summarizeBy: sum
		sourceColumn: SEQPEDIDO

		annotation SummarizationSetBy = Automatic

	column SEQPEDIDOORIGEM
		dataType: int64
		formatString: 0
		lineageTag: f44addfc-58c3-47ba-9e22-31a66cbfe498
		summarizeBy: sum
		sourceColumn: SEQPEDIDOORIGEM

		annotation SummarizationSetBy = Automatic

	column PRODUTOR
		dataType: string
		lineageTag: 834352ef-442d-458f-b1e2-c3db09541900
		summarizeBy: none
		sourceColumn: PRODUTOR

		annotation SummarizationSetBy = Automatic

	column PROPRIEDADE
		dataType: string
		lineageTag: 1f331a6f-2189-4a5b-96a6-5c8a14b04603
		summarizeBy: none
		sourceColumn: PROPRIEDADE

		annotation SummarizationSetBy = Automatic

	column CIDADE
		dataType: string
		lineageTag: 6d256398-4295-444e-a6ff-d2723164358c
		summarizeBy: none
		sourceColumn: CIDADE

		annotation SummarizationSetBy = Automatic

	column UF
		dataType: string
		lineageTag: 2a91c225-db9c-4b59-831e-756a467ee3eb
		summarizeBy: none
		sourceColumn: UF

		annotation SummarizationSetBy = Automatic

	column SEQPRODUTOORIGEM
		dataType: int64
		formatString: 0
		lineageTag: c15622cb-6a9a-453c-a85c-42148001cf1a
		summarizeBy: sum
		sourceColumn: SEQPRODUTOORIGEM

		annotation SummarizationSetBy = Automatic

	column CODLINKPRODUTOORIGEMPEDIDO
		dataType: double
		lineageTag: b8694497-0265-40eb-ba34-0058ee5c28bc
		summarizeBy: sum
		sourceColumn: CODLINKPRODUTOORIGEMPEDIDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CODLINKITEM
		dataType: int64
		formatString: 0
		lineageTag: 2af675fc-c48f-4aef-a9ef-2cd2b0f12cb4
		summarizeBy: sum
		sourceColumn: CODLINKITEM

		annotation SummarizationSetBy = Automatic

	column CLASSIFABATERED
		dataType: string
		lineageTag: 6f186606-7ffc-492c-a41a-09dc7bd304aa
		summarizeBy: none
		sourceColumn: CLASSIFABATERED

		annotation SummarizationSetBy = Automatic

	column CLASSIFABATE
		dataType: string
		lineageTag: d20f9383-c3d4-40f2-b230-b11e33727ab6
		summarizeBy: none
		sourceColumn: CLASSIFABATE

		annotation SummarizationSetBy = Automatic

	column CLASSINDUSTRIA
		dataType: string
		lineageTag: 5d99c550-59e6-4466-a7c9-a8c0793287ae
		summarizeBy: none
		sourceColumn: CLASSINDUSTRIA

		annotation SummarizationSetBy = Automatic

	column SEQPRODUTOKIT
		dataType: string
		lineageTag: 659e6e95-bbf8-4c60-a1ba-d2ed3239f5ba
		summarizeBy: none
		sourceColumn: SEQPRODUTOKIT

		annotation SummarizationSetBy = Automatic

	column SEXO
		dataType: string
		lineageTag: 79b64a09-c173-4743-928d-96044b8d0508
		summarizeBy: none
		sourceColumn: SEXO

		annotation SummarizationSetBy = Automatic

	column CODSETOR
		dataType: double
		lineageTag: 4367a284-90e2-467f-9595-dfe4bd06dc39
		summarizeBy: sum
		sourceColumn: CODSETOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GRUPOPROD
		dataType: int64
		formatString: 0
		lineageTag: eeabead0-d347-4cb8-b776-f589664b3b03
		summarizeBy: sum
		sourceColumn: GRUPOPROD

		annotation SummarizationSetBy = Automatic

	column GRUPOPRODUTO
		dataType: string
		lineageTag: 97df9f12-761a-4cf3-99ff-df92868fae47
		summarizeBy: none
		sourceColumn: GRUPOPRODUTO

		annotation SummarizationSetBy = Automatic

	column FAMILIAPROD
		dataType: int64
		formatString: 0
		lineageTag: 682f1942-3a93-4f2a-8f4a-dab92872cb8b
		summarizeBy: sum
		sourceColumn: FAMILIAPROD

		annotation SummarizationSetBy = Automatic

	column DESCRFAMILIA
		dataType: string
		lineageTag: 3d05354e-deef-439f-8d4d-1a3ce0e639c7
		summarizeBy: none
		sourceColumn: DESCRFAMILIA

		annotation SummarizationSetBy = Automatic

	column PESOKIT
		dataType: double
		lineageTag: a82e994f-e324-48e4-ac9d-dfb2856de2ca
		summarizeBy: sum
		sourceColumn: PESOKIT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TIPOCALCULO
		dataType: int64
		formatString: 0
		lineageTag: 7fb2ec74-5931-494c-b845-7eaad1bedccd
		summarizeBy: sum
		sourceColumn: TIPOCALCULO

		annotation SummarizationSetBy = Automatic

	column VALORMERCADOKIT
		dataType: double
		lineageTag: 2ba9c6b3-0a09-463e-928d-582a7e6753ff
		summarizeBy: sum
		sourceColumn: VALORMERCADOKIT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLRPRODUTOCONTABIL
		dataType: double
		lineageTag: 978f9dd7-2d1d-480d-b6a0-d8ea8e6e392d
		summarizeBy: sum
		sourceColumn: VLRPRODUTOCONTABIL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLRDESCONTO
		dataType: double
		lineageTag: c8f6b510-c022-4bfa-a38e-5310c18dfa8f
		summarizeBy: sum
		sourceColumn: VLRDESCONTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLRICMSCONTABIL
		dataType: double
		lineageTag: e0bcf020-6c21-4ace-bad0-4548c10f9dc2
		summarizeBy: sum
		sourceColumn: VLRICMSCONTABIL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLRIPI
		dataType: double
		lineageTag: 607adea4-7230-4682-bf73-d3408b22826e
		summarizeBy: sum
		sourceColumn: VLRIPI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLRDNTI
		dataType: double
		lineageTag: d583e2df-8fc6-4272-8bb2-b945f2c2c279
		summarizeBy: sum
		sourceColumn: VLRDNTI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLRDTI
		dataType: double
		lineageTag: c2013e0d-c054-41d4-93ce-53e797ff5126
		summarizeBy: sum
		sourceColumn: VLRDTI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLRDNTNI
		dataType: double
		lineageTag: d604da65-1447-4877-9a42-c04b54b396bd
		summarizeBy: sum
		sourceColumn: VLRDNTNI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLRDTNI
		dataType: double
		lineageTag: 742eaab9-93db-4094-859f-138063a06b1f
		summarizeBy: sum
		sourceColumn: VLRDTNI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLRPISCREDITO
		dataType: double
		lineageTag: 18b7dbd9-237a-4ab6-ba48-9e28126ea018
		summarizeBy: sum
		sourceColumn: VLRPISCREDITO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLRCOFINSCREDITO
		dataType: double
		lineageTag: 5680f494-3843-4f5b-bcd0-a203e1ab1d7d
		summarizeBy: sum
		sourceColumn: VLRCOFINSCREDITO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLRCOFINS
		dataType: double
		lineageTag: e0d269e8-3204-4c47-89a5-668e69da5c53
		summarizeBy: sum
		sourceColumn: VLRCOFINS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLRPIS
		dataType: double
		lineageTag: a45a44c7-e61b-44f7-85fa-66d1d054d333
		summarizeBy: sum
		sourceColumn: VLRPIS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QTDCALCULO
		dataType: double
		lineageTag: ff708e5f-5401-494b-981d-0127b51f738c
		summarizeBy: sum
		sourceColumn: QTDCALCULO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VLRCREDITOMIUDO
		dataType: double
		lineageTag: 9f51b5e9-3076-4009-86cf-4eaae4855aa8
		summarizeBy: sum
		sourceColumn: VLRCREDITOMIUDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NRONOTAFISCAL
		dataType: string
		lineageTag: 27417220-d7f5-4634-b82c-39bc7b715837
		summarizeBy: none
		sourceColumn: NRONOTAFISCAL

		annotation SummarizationSetBy = Automatic

	column DTAATUALIZACAO
		dataType: dateTime
		formatString: General Date
		lineageTag: 52c5fb31-c0ce-4934-90eb-5859ea8bb506
		summarizeBy: none
		sourceColumn: DTAATUALIZACAO

		annotation SummarizationSetBy = Automatic

	column 'Aux Compra.NROEMPRESA'
		dataType: int64
		formatString: 0
		lineageTag: 6d2668f1-1a3a-4760-b8ec-18fcfb0de376
		summarizeBy: sum
		sourceColumn: Aux Compra.NROEMPRESA

		annotation SummarizationSetBy = Automatic

	column 'Aux Compra.NROPEDIDO'
		dataType: int64
		formatString: 0
		lineageTag: fecac946-d4e0-4b3b-a497-a46a89704147
		summarizeBy: sum
		sourceColumn: Aux Compra.NROPEDIDO

		annotation SummarizationSetBy = Automatic

	column 'Aux Compra.Mesclado'
		dataType: string
		lineageTag: a02ace1e-a5ae-441c-b6df-5cb888e8cc24
		summarizeBy: none
		sourceColumn: Aux Compra.Mesclado

		annotation SummarizationSetBy = Automatic

	partition DCUVQ_COMPRAGADOPRAZO = m
		mode: import
		source =
				let
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true, Query="select * from datavale.DCUVQ_COMPRAGADOPRAZO"]),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(Fonte, "Mesclado", each Text.Combine({Text.From([NROEMPRESA], "pt-BR"), Text.From([NROPEDIDO], "pt-BR")}, ""), type text),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Coluna Mesclada Inserida", {"Mesclado"}, #"Aux Compra", {"Mesclado"}, "Aux Compra", JoinKind.LeftOuter),
				    #"Aux Compra Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "Aux Compra", {"NROEMPRESA", "DATA", "NROPEDIDO", "Mesclado"}, {"Aux Compra.NROEMPRESA", "Aux Compra.DATA", "Aux Compra.NROPEDIDO", "Aux Compra.Mesclado"})
				in
				    #"Aux Compra Expandido"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

