table DCUVM_COMPRASUINO
	lineageTag: 001fe9de-0699-4793-87e4-aebb06d35fb1

	column NROEMPRESA
		dataType: double
		lineageTag: d224e2bf-2954-475c-8af9-3ad9e0d225cc
		summarizeBy: none
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DATA
		dataType: dateTime
		formatString: General Date
		lineageTag: d5e35d66-e230-4a9d-9f69-9301f32fced4
		summarizeBy: none
		sourceColumn: DATA

		annotation SummarizationSetBy = Automatic

	column SEQPRODUTOR
		dataType: double
		lineageTag: 67e00ae5-7b17-4c2d-9598-41953e367e20
		summarizeBy: none
		sourceColumn: SEQPRODUTOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DCUVM_COMPRASUINO = m
		mode: import
		source =
				let
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true]),
				    DATAVALE = Fonte{[Schema="DATAVALE"]}[Data],
				    DCUVM_COMPRASUINO1 = DATAVALE{[Name="DCUVM_COMPRASUINO"]}[Data],
				    #"Columns removed by Measure Killer"= Table.SelectColumns(DCUVM_COMPRASUINO1,{"SEQPRODUTOR","NROEMPRESA","DATA"})
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Exception

