table DEPARAINDUS
	lineageTag: acb357e5-746c-4dab-893b-d0b9e7822a30

	column NROPROGPRODUCAO
		dataType: int64
		formatString: 0
		lineageTag: f5ad7506-eb47-4d77-b598-f85809f99480
		summarizeBy: sum
		sourceColumn: NROPROGPRODUCAO

		annotation SummarizationSetBy = Automatic

	column LOTE
		dataType: int64
		formatString: 0
		lineageTag: 35248aab-1a21-45de-aee2-a525c17fef8c
		summarizeBy: sum
		sourceColumn: LOTE

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column _DK = DEPARAINDUS[NROPROGPRODUCAO]&DEPARAINDUS[LOTE]&DEPARAINDUS[NROEMPRESA]
		lineageTag: 4b3d6a7e-d146-499d-98c0-7b45ebf921d1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Turno = IF(DEPARAINDUS[LOTE] = 20 || DEPARAINDUS[LOTE] = 21 || DEPARAINDUS[LOTE] > 30,"Noturno" ,"Diurno")
		lineageTag: 75ee4cc5-1055-47b8-a661-339f3a8c482d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column SEQPRODUTO
		dataType: int64
		formatString: 0
		lineageTag: 0a4dfa28-62b0-4639-8d6d-ee125cf34cf6
		summarizeBy: none
		sourceColumn: SEQPRODUTO

		annotation SummarizationSetBy = Automatic

	column NROEMPRESA
		dataType: double
		lineageTag: f3c26587-91e4-4908-849b-6fe6149edfd9
		summarizeBy: sum
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DEPARAINDUS = m
		mode: import
		queryGroup: 'Fluxo Industrial'
		source =
				let
				    // 1. Conexão SQL nativa no Oracle para Entrada de Industrializados (Filiais 2 e 104)
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true, Query="#(lf)            SELECT #(lf)               2 AS NROEMPRESA, #(lf)                e.NROPROGPRODUCAO,#(lf)e.LOTE,#(lf)e.SEQPRODUTO#(lf)            FROM DINVPB_ENTRADAINDUSTRIALIZADOS@dtvind02 e #(lf)            WHERE DATAENT >= '01-JAN-2026'#(lf)#(lf)            UNION ALL#(lf)#(lf)            SELECT #(lf)                104 AS NROEMPRESA, #(lf)                e.NROPROGPRODUCAO,#(lf)e.LOTE,#(lf)e.SEQPRODUTO#(lf)            FROM DINVPB_ENTRADAINDUSTRIALIZADOS@dtvind104 e #(lf)            WHERE DATAENT >= '01-JAN-2026'#(lf)        "]),
				
				    // 2. Seleção final das colunas para o modelo
				    #"Columns removed by Measure Killer" = Table.SelectColumns(Fonte,{"NROEMPRESA", "NROPROGPRODUCAO", "LOTE", "SEQPRODUTO"})
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

