table DEPARABANHA
	lineageTag: df1120d3-a939-4fd4-b8b0-539ef855a877

	column NROPROGPRODUCAO
		dataType: int64
		formatString: 0
		lineageTag: a4af4194-0dff-4360-a0ae-659185bbc95b
		summarizeBy: sum
		sourceColumn: NROPROGPRODUCAO

		annotation SummarizationSetBy = Automatic

	column LOTE
		dataType: string
		lineageTag: 985689ab-2c82-4eba-a5be-39d43b60d42e
		summarizeBy: none
		sourceColumn: LOTE

		annotation SummarizationSetBy = Automatic

	column DTARENDIMENTO
		dataType: dateTime
		formatString: General Date
		lineageTag: 377b8d8f-26a7-4012-af29-f87613a16669
		summarizeBy: none
		sourceColumn: DTARENDIMENTO

		annotation SummarizationSetBy = Automatic

	column NROEMPRESA
		dataType: double
		lineageTag: 9a317177-a69d-49e9-b3f8-3e40fcb40165
		summarizeBy: none
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _DK = DEPARABANHA[NROPROGPRODUCAO]&DEPARABANHA[LOTE]&DEPARABANHA[NROEMPRESA]
		lineageTag: 8e2e18e8-f565-4506-847b-785349d16f13
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition DEPARABANHA = m
		mode: import
		queryGroup: 'Fluxo Industrial'
		source = ```
				let
				    // 1. Conexão SQL nativa no Oracle para Entrada de Banha (Filial 4)
				    Fonte = Oracle.Database("datavale", [
				        HierarchicalNavigation = true, 
				        Query = "
				            SELECT 
				                4 AS NROEMPRESA, 
				                e.* 
				            FROM DINVPB_ENTRADABANHA@dtvind04 e 
				            WHERE DTARENDIMENTO >= '01-JAN-2026'
				        "
				    ]),
				
				    // 2. Seleção das colunas necessárias
				    #"Outras Colunas Removidas" = Table.SelectColumns(Fonte, {
				        "NROPROGPRODUCAO", 
				        "LOTE", 
				        "DTARENDIMENTO", 
				        "NROEMPRESA"
				    }),
				
				    // 3. Remoção de duplicatas
				    #"Duplicatas Removidas" = Table.Distinct(#"Outras Colunas Removidas")
				in
				    #"Duplicatas Removidas"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

