table DEPARADESOSSA
	lineageTag: 76a40d3c-be26-4687-a5c3-639520941077

	column NROPROGPRODUCAO
		dataType: int64
		lineageTag: 9c38d6b8-794c-4649-b8f0-bb7d08273093
		summarizeBy: sum
		sourceColumn: NROPROGPRODUCAO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LOTE
		dataType: double
		lineageTag: 7c752ba7-0fd8-4885-82db-a2b32c595468
		summarizeBy: sum
		sourceColumn: LOTE

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DTARENDIMENTO
		dataType: dateTime
		formatString: General Date
		lineageTag: c0bcf319-7a2f-4e78-9791-1155bcacb7e1
		summarizeBy: none
		sourceColumn: DTARENDIMENTO

		annotation SummarizationSetBy = Automatic

	column DESCRFAMILIA
		dataType: string
		lineageTag: d8398856-bac0-40fa-957d-d3cb9139fa8e
		summarizeBy: none
		sourceColumn: DESCRFAMILIA

		annotation SummarizationSetBy = Automatic

	column NROEMPRESA
		dataType: double
		formatString: 0
		lineageTag: 8f3aeb7b-fe4a-4f52-85bc-0bd8c466bb00
		summarizeBy: none
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

	column _Turno =
			
			var var01 = IF(DEPARADESOSSA[LOTE] = 18 ||DEPARADESOSSA[LOTE] = 20 || DEPARADESOSSA[LOTE] = 21 || DEPARADESOSSA[LOTE] > 30,"Noturno" ,"Diurno")
			RETURN
			IF(DEPARADESOSSA[DESCRFAMILIA] = "CUPIM", BLANK(), IF(DEPARADESOSSA[NROEMPRESA] <> 2, "Diurno",var01))
			
			//Se mudar essa formula, trocar em ENTRADADESOSSA / PRODUÇÃO DESOSSA / DEPARADESOSSA
		lineageTag: 6d2bd1d9-efb3-4423-bfba-27b1be3c91d9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _DK = DEPARADESOSSA[NROPROGPRODUCAO]&DEPARADESOSSA[LOTE]&DEPARADESOSSA[NROEMPRESA]
		lineageTag: dcd09209-755a-4ba8-9dc6-aa144bc74cec
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '_Contar Linhas' = ```
			CALCULATE(
			    COUNTROWS(DINVPB_ENTRADADESOSSA), 
			    ALLEXCEPT(DINVPB_ENTRADADESOSSA, DINVPB_ENTRADADESOSSA[DTARENDIMENTO], DINVPB_ENTRADADESOSSA[NROEMPRESA], DINVPB_ENTRADADESOSSA[_Turno]))
			```
		formatString: 0
		lineageTag: 4f9f94b7-9897-4d99-a687-85298e4e4113
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '_Contar Data' = DEPARADESOSSA[DTARENDIMENTO]&DEPARADESOSSA[NROEMPRESA]
		lineageTag: be747ee7-a2c4-40af-ad06-fe3e826b3134
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _NomeEmpresa = ```
			
			IF( 
			    DEPARADESOSSA[_Turno] = BLANK(), RELATED(DGE_EMPRESAMATRIZ[NOMEFILIAL])
			    ,RELATED(DGE_EMPRESAMATRIZ[NOMEFILIAL])&" - "&DEPARADESOSSA[_Turno])
			```
		lineageTag: 48564014-ea0d-4fca-b395-501f6d34dc3f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _LoteChinaPCP = ```
			
			SWITCH(
			    TRUE(),
			    DEPARADESOSSA[LOTE] in {2,13,23,46,53,66} && DEPARADESOSSA[NROEMPRESA] IN {2,104} , "CHN", "OUTROS") 
			```
		lineageTag: 5d9065e5-2f15-4934-9d3a-ed8080c1d1ad
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _SK = DEPARADESOSSA[NROEMPRESA]&DEPARADESOSSA[NROPROGPRODUCAO]
		lineageTag: 29adcda1-b4ae-4b86-95cd-2f00c3296544
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '_CLASSIF.REND'
		dataType: string
		lineageTag: 8e92dc91-15fc-410c-8905-f0edfdb69e48
		summarizeBy: none
		sourceColumn: _CLASSIF.REND

		annotation SummarizationSetBy = Automatic

	column SEQPRODUTO
		dataType: int64
		formatString: 0
		lineageTag: 89b3b6fd-4c9a-4542-acb9-a1f7dcce1ef7
		summarizeBy: none
		sourceColumn: SEQPRODUTO

		annotation SummarizationSetBy = Automatic

	column DESCRICAO
		dataType: string
		lineageTag: bf5d341e-2981-4509-b9b5-55ff35974e3a
		summarizeBy: none
		sourceColumn: DESCRICAO

		annotation SummarizationSetBy = Automatic

	partition DEPARADESOSSA-330d9a0b-6897-413f-9a5c-512f03fd74b8 = m
		mode: import
		queryGroup: 'Fluxo Industrial'
		source = ```
				let
				    // 1. Conexão SQL nativa unificando as instâncias de Entrada de Desossa
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true, Query="#(lf)            SELECT #(lf)2 as NROEMPRESA,#(lf)e.* #(lf)            FROM DINVPB_ENTRADADESOSSA@dtvind02 e #(lf)            --WHERE DTARENDIMENTO >= TRUNC(SYSDATE)-60#(lf)WHERE DTARENDIMENTO >= '01-jan-2026'#(lf)            #(lf)            UNION ALL#(lf)            #(lf)            SELECT #(lf)4 as NROEMPRESA,#(lf)e.* #(lf)            FROM DINVPB_ENTRADADESOSSA@dtvind04 e #(lf)            --WHERE DTARENDIMENTO >= TRUNC(SYSDATE)-60#(lf)WHERE DTARENDIMENTO >= '01-jan-2026'#(lf)            #(lf)            UNION ALL#(lf)            #(lf)            SELECT #(lf)104 as NROEMPRESA,#(lf)e.* #(lf)            FROM DINVPB_ENTRADADESOSSA@dtvind104 e #(lf)            --WHERE DTARENDIMENTO >= TRUNC(SYSDATE)-60#(lf)WHERE DTARENDIMENTO >= '01-jan-2026'#(lf)        "]),
				
				    // 2. Adiciona a coluna condicional _CLASSIF.REND
				    #"Coluna Condicional Adicionada" = Table.AddColumn(Fonte, "_CLASSIF.REND", each 
				        if [TIPOPROGPRODUCAO] = "CONSERVA" then "CONSERVA" 
				        else if [TIPOPROGPRODUCAO] = "TRATAMENTO DE FRIO" then "T.F" 
				        else if Text.Contains([DESCRLOTE], "SALSICHARIA") then "NORMAL" 
				        else if Text.Contains([DESCRLOTE], "CH") then "CHN" 
				        else if Text.Contains([DESCRLOTE], "ANGUS") then "ANGUS" 
				        else "NORMAL",
				        type text
				    ),
				
				    // 3. Adiciona a coluna de concatenação para chave única
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Coluna Condicional Adicionada", "Conc", each Text.Combine({Text.From([NROPROGPRODUCAO], "pt-BR"), [LOTE], Text.From([NROEMPRESA], "pt-BR")}, ""), type text),
				
				    // 4. Remove duplicatas com base na chave concatenada
				    #"Removidas Duplicatas" = Table.Distinct(#"Coluna Mesclada Inserida", {"Conc"}),
				
				    // 5. Seleção final das colunas utilizadas pelo modelo
				    #"Columns removed by Measure Killer" = Table.SelectColumns(#"Removidas Duplicatas", {
				        "SEQPRODUTO",
				        "LOTE",
				        "DESCRICAO",
				        "DTARENDIMENTO",
				        "_CLASSIF.REND",
				        "NROEMPRESA",
				        "DESCRFAMILIA",
				        "NROPROGPRODUCAO"
				    })
				in
				    #"Columns removed by Measure Killer"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

