table 'DESVIOS DIF'
	lineageTag: d2fd37d0-c07b-4acc-a320-1a20961af245

	column Empresa
		dataType: int64
		formatString: 0
		lineageTag: 347924d5-a2a0-4ff3-b5bc-0a9d772b3c01
		summarizeBy: none
		sourceColumn: Empresa

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 88f17c89-1890-47fb-a197-fcb2bfab512a
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Valor
		dataType: double
		lineageTag: 3354ecbe-1014-4046-8ef4-2230319eba71
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Turno
		dataType: string
		lineageTag: 54e58c44-8412-4996-8be9-9e49299db57e
		summarizeBy: none
		sourceColumn: Turno

		annotation SummarizationSetBy = Automatic

	partition 'DESVIOS DIF' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("\\192.168.2.167\controladoria\05 - INDICADORES\09. Power BI\Desvios DIF.xlsx"), null, true),
				    Planilha1_Sheet = Fonte{[Item="Planilha1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Planilha1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Empresa", Int64.Type}, {"Data", type date}, {"Valor", type number}}),
				    #"Columns removed by Measure Killer"= Table.SelectColumns(#"Tipo Alterado",{"Valor","Data","Empresa","Turno"})
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

