table 'DESVIOS DIF'
	lineageTag: d2fd37d0-c07b-4acc-a320-1a20961af245

	column Empresa
		dataType: int64
		formatString: 0
		lineageTag: 347924d5-a2a0-4ff3-b5bc-0a9d772b3c01
		summarizeBy: none
		sourceColumn: Empresa

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 88f17c89-1890-47fb-a197-fcb2bfab512a
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Valor
		dataType: double
		lineageTag: 3354ecbe-1014-4046-8ef4-2230319eba71
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Turno
		dataType: string
		lineageTag: 54e58c44-8412-4996-8be9-9e49299db57e
		summarizeBy: none
		sourceColumn: Turno

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: 3e8be1e4-14a2-4951-83bd-6dec395484a0
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: 4f729da7-285e-4534-83c8-e895e89cd2a8
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: 102ba79d-a789-4a3e-a16e-fc2a967b4f46
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: 01d125ed-61ad-478c-9a58-623f9b179e09
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: bbb7729b-2606-446b-8929-36ea6dacc974
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		lineageTag: 8931d475-8edc-4a29-9bd4-11918ceab75c
		summarizeBy: none
		sourceColumn: Column10

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: ed0914c0-fb5f-440f-a8b5-0bec5592568e
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		lineageTag: e7a7c753-7eca-429c-a72f-7f26c6a154c4
		summarizeBy: none
		sourceColumn: Column12

		annotation SummarizationSetBy = Automatic

	column Column13
		dataType: string
		lineageTag: 8730dc80-f1c9-4788-8278-605fcc7e58c0
		summarizeBy: none
		sourceColumn: Column13

		annotation SummarizationSetBy = Automatic

	partition 'DESVIOS DIF' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("\\192.168.2.167\controladoria\05 - INDICADORES\09. Power BI\Desvios DIF.xlsx"), null, true),
				    Planilha1_Sheet = Fonte{[Item="Planilha1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Planilha1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Empresa", Int64.Type}, {"Data", type date}, {"Valor", type number}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

