table DGEVQ_HIERARQUIAVENDA
	lineageTag: 79cb9836-df02-42a8-b449-78564303e9a2

	column SEQVENDEDOR
		dataType: double
		lineageTag: 63cc02c6-dfdb-4cf3-9cec-bb52d1e73b13
		summarizeBy: sum
		sourceColumn: SEQVENDEDOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GERENTEVENDA
		dataType: string
		lineageTag: 08a24aba-06fa-4cf6-9dbf-bc402e0c48b9
		summarizeBy: none
		sourceColumn: GERENTEVENDA

		annotation SummarizationSetBy = Automatic

	column MêsAno2 = DGEVQ_HIERARQUIAVENDA[DTAFINAL].[MonthNo]&DGEVQ_HIERARQUIAVENDA[DTAFINAL].[Ano]
		lineageTag: b1158449-7716-40a4-8c56-0621cefd24d1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Chave = DGEVQ_HIERARQUIAVENDA[SEQVENDEDOR]&DGEVQ_HIERARQUIAVENDA[MêsAno2]
		lineageTag: 1adac2ae-e32c-45f7-93ef-e2c5ea7826ee
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Coordenador = DGEVQ_HIERARQUIAVENDA[GERENTEVENDA]
		lineageTag: 31c32040-f18f-41c3-abd8-73d09c174e2f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition DGEVQ_HIERARQUIAVENDA = m
		mode: import
		source =
				let
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true]),
				    DATAVALE = Fonte{[Schema="DATAVALE"]}[Data],
				    DGEVQ_HIERARQUIAVENDA1 = DATAVALE{[Name="DGEVQ_HIERARQUIAVENDA"]}[Data],
				    #"Linhas Filtradas" = Table.SelectRows(DGEVQ_HIERARQUIAVENDA1, each [DTAFINAL] > #datetime(2022, 1, 1, 0, 0, 0)),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Linhas Filtradas", each true),
				    #"Columns removed by Measure Killer"= Table.SelectColumns(#"Linhas Filtradas1",{"GERENTEVENDA","SEQVENDEDOR"})
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Exception

