table DINVPB_ENTRADABANHA
	lineageTag: c1c55fba-6352-4889-87ca-a4878fe105fc

	column NROPROGPRODUCAO
		dataType: int64
		formatString: 0
		lineageTag: adfdc53e-ef72-427d-b49e-9f7fb9a6c641
		summarizeBy: sum
		sourceColumn: NROPROGPRODUCAO

		annotation SummarizationSetBy = Automatic

	column LOTE
		dataType: string
		lineageTag: 4c8db0c1-f0f9-49ba-b526-e6509976def0
		summarizeBy: none
		sourceColumn: LOTE

		annotation SummarizationSetBy = Automatic

	column DATAHORA
		dataType: dateTime
		formatString: General Date
		lineageTag: 0da533b4-35f2-4ac2-b201-6f190062bdc3
		summarizeBy: none
		sourceColumn: DATAHORA

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column DTARENDIMENTO
		dataType: dateTime
		formatString: General Date
		lineageTag: 0691b0ed-7cb4-4ac3-a618-85522c4e2a39
		summarizeBy: none
		sourceColumn: DTARENDIMENTO

		annotation SummarizationSetBy = Automatic

	column DATAENT
		dataType: dateTime
		formatString: General Date
		lineageTag: d4505f8e-9a70-4012-908d-205a4680fb90
		summarizeBy: none
		sourceColumn: DATAENT

		annotation SummarizationSetBy = Automatic

	column NROEMPRESA
		dataType: double
		lineageTag: f252b9ca-5428-4fc2-8848-171c316ec127
		summarizeBy: sum
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _DK = DINVPB_ENTRADABANHA[NROPROGPRODUCAO]&DINVPB_ENTRADABANHA[LOTE]&DINVPB_ENTRADABANHA[NROEMPRESA]
		lineageTag: d344bb67-867d-489d-b6fe-5f62b10005fa
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Entrada =
			
			var week = WEEKDAY(DINVPB_ENTRADABANHA[DATAENT],1)
			RETURN
			IF(week = 7, DINVPB_ENTRADABANHA[DATAENT] & " 02:50:00", DINVPB_ENTRADABANHA[DATAENT] & " 05:00:00")
		dataType: dateTime
		formatString: General Date
		lineageTag: dcabcf91-5ab8-4af6-a7fd-f06eee226bbc
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column _Saída =
			
			var week = WEEKDAY(DINVPB_ENTRADABANHA[DATAENT],1)
			RETURN
			IF(week = 7, DINVPB_ENTRADABANHA[DATAENT] & " 12:00:00", DINVPB_ENTRADABANHA[DATAENT] & " 15:30:00")
		dataType: dateTime
		formatString: General Date
		lineageTag: dcac3a88-70fe-4b02-982e-d77448b8ae2d
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column _Turno = IF(DINVPB_ENTRADABANHA[DATAHORA] >= DINVPB_ENTRADABANHA[_Entrada] && DINVPB_ENTRADABANHA[DATAHORA] <= DINVPB_ENTRADABANHA[_Saída], "Diurno", "Noturno")
		lineageTag: 4edc598e-e49f-467b-a2f2-68093b70f6d4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Weekday = WEEKDAY(DINVPB_ENTRADABANHA[DATAENT],1)
		formatString: 0
		lineageTag: 27241ab1-2f75-402b-bd6a-78b10a963374
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column _DataHoraMax = ```
			CALCULATE(
			    MAX(DINVPB_ENTRADABANHA[DATAHORA]), 
			    ALLEXCEPT(DINVPB_ENTRADABANHA, DINVPB_ENTRADABANHA[DTARENDIMENTO], DINVPB_ENTRADABANHA[NROEMPRESA], DINVPB_ENTRADABANHA[_Turno]))
			```
		formatString: General Date
		lineageTag: 93687081-9fcd-4dcb-ae3d-135e6d8338ab
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _DataHoraMin =
			CALCULATE(
			    MIN(DINVPB_ENTRADABANHA[DATAHORA]),
			    ALLEXCEPT(DINVPB_ENTRADABANHA, DINVPB_ENTRADABANHA[DTARENDIMENTO], DINVPB_ENTRADABANHA[NROEMPRESA], DINVPB_ENTRADABANHA[_Turno]))
		formatString: General Date
		lineageTag: 0d2e3961-9a58-478b-85eb-fefbb64d56af
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition DINVPB_ENTRADABANHA = m
		mode: import
		queryGroup: 'Fluxo Industrial'
		source = ```
				let
				    // 1. Conexão SQL nativa no Oracle para Entrada de Banha (Filial 4)
				    Fonte = Oracle.Database("datavale", [
				        HierarchicalNavigation = true, 
				        Query = "
				            SELECT 
				                4 AS NROEMPRESA, 
				                e.* 
				            FROM DINVPB_ENTRADABANHA@dtvind04 e 
				            WHERE DTARENDIMENTO >= '01-JAN-2026'
				        "
				    ]),
				
				    // 2. Seleção final das colunas solicitadas para o modelo
				    #"Columns removed by Measure Killer" = Table.SelectColumns(Fonte, {
				        "DATAENT",
				        "DTARENDIMENTO",
				        "DATAHORA",
				        "NROEMPRESA",
				        "NROPROGPRODUCAO",
				        "LOTE"
				    })
				in
				    #"Columns removed by Measure Killer"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

