table DINVPB_PRODUCAOINDUS
	lineageTag: 68492065-36ad-45a3-9e29-7ef00dd620be

	column NROEMPRESA
		dataType: double
		formatString: 0
		lineageTag: 5add1662-ba11-479e-a493-cd8364374a01
		summarizeBy: none
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

	column NROPROGPRODUCAO
		dataType: int64
		formatString: 0
		lineageTag: 940320f3-0840-479f-814e-1c1147e98c6a
		summarizeBy: sum
		sourceColumn: NROPROGPRODUCAO

		annotation SummarizationSetBy = Automatic

	column LOTE
		dataType: int64
		formatString: 0
		lineageTag: 297eb2e5-e7b1-473c-b6a8-42b357bef938
		summarizeBy: sum
		sourceColumn: LOTE

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column DTARENDIMENTO
		dataType: dateTime
		formatString: General Date
		lineageTag: 1fa8388b-d5eb-4fc1-94d9-211984e0d1c0
		summarizeBy: none
		sourceColumn: DTARENDIMENTO

		annotation SummarizationSetBy = Automatic

	column DATAENT
		dataType: dateTime
		formatString: Long Date
		lineageTag: 62e8d2ff-796d-411a-a3a8-a33f9fa4cc2f
		summarizeBy: none
		sourceColumn: DATAENT

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SEQPRODUTO
		dataType: int64
		formatString: 0
		lineageTag: b156f614-6d4a-4654-85d5-1758d5a613de
		summarizeBy: none
		sourceColumn: SEQPRODUTO

		annotation SummarizationSetBy = Automatic

	column DESCRPRODUTO
		dataType: string
		lineageTag: 43dbb1f3-6013-497b-8723-15ca8acac3e4
		summarizeBy: none
		sourceColumn: DESCRPRODUTO

		annotation SummarizationSetBy = Automatic

	column DATAHORAENT
		dataType: dateTime
		formatString: General Date
		lineageTag: 8348e012-e85d-4879-8c1a-903111eba64a
		summarizeBy: none
		sourceColumn: DATAHORAENT

		annotation SummarizationSetBy = Automatic

	column PESOLIQUIDO
		dataType: double
		lineageTag: b2f989a9-1301-4752-9ea0-cfd6ff515331
		summarizeBy: sum
		sourceColumn: PESOLIQUIDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _DK = DINVPB_PRODUCAOINDUS[NROPROGPRODUCAO]&DINVPB_PRODUCAOINDUS[LOTE]&DINVPB_PRODUCAOINDUS[NROEMPRESA]
		lineageTag: dff25914-fece-4dfd-8233-5d206115a4ce
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Turno =
			IF(
			    DINVPB_PRODUCAOINDUS[DATAHORAENT] >= DINVPB_PRODUCAOINDUS[Entrada] && DINVPB_PRODUCAOINDUS[DATAHORAENT] <= DINVPB_PRODUCAOINDUS[Saída], "Diurno", "Noturno")
		lineageTag: 5bae5434-b42b-49bc-90ff-a88b7274f616
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Entrada
		dataType: dateTime
		formatString: General Date
		lineageTag: 2103b55d-803c-4fea-b72c-5550a1c34fd4
		summarizeBy: none
		sourceColumn: Entrada

		annotation SummarizationSetBy = Automatic

	column Saída
		dataType: dateTime
		formatString: General Date
		lineageTag: 20615efb-06c0-4679-8295-edb6a50acb30
		summarizeBy: none
		sourceColumn: Saída

		annotation SummarizationSetBy = Automatic

	column _Data = ```
			
			VAR DIAANTERIOR = IF(HOUR(DINVPB_PRODUCAOINDUS[DATAHORAENT]) >= 5 && HOUR(DINVPB_PRODUCAOINDUS[DATAHORAENT]) <= 23, DINVPB_PRODUCAOINDUS[DATAENT], DINVPB_PRODUCAOINDUS[DATAENT] -1)
			RETURN 
			DIAANTERIOR
			```
		formatString: General Date
		lineageTag: 1bfb5dd9-80a1-47cf-a608-568f5a1d3a25
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _ConcProduto = DINVPB_PRODUCAOINDUS[SEQPRODUTO]&" - "&DINVPB_PRODUCAOINDUS[DESCRPRODUTO]
		lineageTag: fcd0d844-61fb-4cf0-9ec7-222c8a457b09
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _TIPO
		dataType: string
		lineageTag: a7f34fbb-4ee8-4f13-b63b-bd887b77f17e
		summarizeBy: none
		sourceColumn: _TIPO

		annotation SummarizationSetBy = Automatic

	partition DINVPB_PRODUCAOINDUS = m
		mode: import
		queryGroup: 'Fluxo Industrial'
		source = ```
				let
				    // 1. Conexão SQL nativa no Oracle para Produção de Industrializados (Filiais 2 e 104)
				    Fonte = Oracle.Database("datavale", [
				        HierarchicalNavigation = true, 
				        Query = "
				            SELECT 
				                2 AS NROEMPRESA, 
				                e.* 
				            FROM DINVPB_PRODUCAOINDUSTRIALIZADOS@dtvind02 e 
				            WHERE DATAENT >= '01-JAN-2026'
				
				            UNION ALL
				
				            SELECT 
				                104 AS NROEMPRESA, 
				                e.* 
				            FROM DINVPB_PRODUCAOINDUSTRIALIZADOS@dtvind104 e 
				            WHERE DATAENT >= '01-JAN-2026'
				        "
				    ]),
				
				    // 2. Criação da chave
				    #"Coluna Mesclada Inserida1" = Table.AddColumn(Fonte, "Chave", each Text.Combine({Text.From([NROPROGPRODUCAO], "pt-BR"), [LOTE]}, ""), type text),
				
				    // 3. Ajustes de tipo para manipulação de texto da data
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Mesclada Inserida1", {{"DATAENT", type date}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Tipo Alterado1", {{"DATAENT", type text}}),
				
				    // 4. Geração de colunas Entrada e Saída
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado", "Personalizar", each [DATAENT] & " 05:00:00"),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Personalização Adicionada", "Personalizar.1", each [DATAENT] & " 15:30:00"),
				
				    // 5. Renomeando colunas
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Personalização Adicionada1", {{"Personalizar", "Entrada"}, {"Personalizar.1", "Saída"}}),
				
				    // 6. Conversões finais de tipo
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Renomeadas", {
				        {"DATAENT", type date}, 
				        {"Entrada", type datetime}, 
				        {"Saída", type datetime}
				    }),
				
				    // 7. Adição da coluna _TIPO
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Tipo Alterado2", "_TIPO", each 
				        if Text.Contains([DESCRPRODUTO], "RETRABALHO") then "RETRABALHO" 
				        else if Text.Contains([DESCRPRODUTO], "REPROCESSO") then "RETRABALHO" 
				        else "PRODUÇÃO NORMAL", 
				        type text
				    ),
				
				    // 8. Seleção final das colunas para o modelo
				    #"Columns removed by Measure Killer" = Table.SelectColumns(#"Coluna Condicional Adicionada", {
				        "PESOLIQUIDO",
				        "DATAHORAENT",
				        "NROEMPRESA",
				        "_TIPO",
				        "Entrada",
				        "Saída",
				        "NROPROGPRODUCAO",
				        "DATAENT",
				        "SEQPRODUTO",
				        "DESCRPRODUTO",
				        "LOTE",
				        "DTARENDIMENTO"
				    })
				in
				    #"Columns removed by Measure Killer"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

