table DINVPB_PRODUCAOMIUDOS
	lineageTag: da0e60a9-0c12-404c-a711-44e42efcb302

	column NROEMPRESA
		dataType: double
		lineageTag: 49efee67-a475-4f8c-abec-d5b6bfb9bfba
		summarizeBy: none
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DATA
		dataType: dateTime
		formatString: General Date
		lineageTag: 4f6e9497-2290-4917-87a4-bfb522e8024d
		summarizeBy: none
		sourceColumn: DATA

		annotation SummarizationSetBy = Automatic

	column NROPROGPRODUCAO
		dataType: int64
		lineageTag: ba7ffb72-2ea0-4805-a268-0a073e85510e
		summarizeBy: sum
		sourceColumn: NROPROGPRODUCAO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DESCRSUBGRUPOPRODUTO
		dataType: string
		lineageTag: b5ad4b64-840a-44ea-9403-61467cf68270
		summarizeBy: none
		sourceColumn: DESCRSUBGRUPOPRODUTO

		annotation SummarizationSetBy = Automatic

	column DESCRFAMILIA
		dataType: string
		lineageTag: 5fadd0a8-0d92-45f3-ab6b-7c7e4b46cc3f
		summarizeBy: none
		sourceColumn: DESCRFAMILIA

		annotation SummarizationSetBy = Automatic

	column SEQPRODUTO
		dataType: int64
		lineageTag: c7cee911-cc2c-4a75-9393-dcc2e2e2c75f
		summarizeBy: none
		sourceColumn: SEQPRODUTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DESCRPRODUTO
		dataType: string
		lineageTag: cc9096fb-7425-42e5-a7c4-6a9a8ac11b29
		summarizeBy: none
		sourceColumn: DESCRPRODUTO

		annotation SummarizationSetBy = Automatic

	column RENDIMENTOPADRAO
		dataType: double
		lineageTag: e6e26382-4ab3-4a5c-a1f1-e5ea50ce1807
		summarizeBy: sum
		sourceColumn: RENDIMENTOPADRAO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UNIDADE
		dataType: string
		lineageTag: 4df9b7ea-1c23-4c4a-aba2-6dc77bf6093d
		summarizeBy: none
		sourceColumn: UNIDADE

		annotation SummarizationSetBy = Automatic

	column QUANTIDADE2
		dataType: double
		lineageTag: e956c3c4-20af-449b-9627-c1c5ff3b6802
		summarizeBy: sum
		sourceColumn: QUANTIDADE2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PESOLIQUIDO
		dataType: double
		lineageTag: 8537da2c-b7cc-440a-88a3-bde5f6dee75a
		summarizeBy: sum
		sourceColumn: PESOLIQUIDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _cProduto = DINVPB_PRODUCAOMIUDOS[DESCRPRODUTO]&" - "&DINVPB_PRODUCAOMIUDOS[SEQPRODUTO]
		lineageTag: 79f7ac6b-d97d-41e4-9230-d9da331faf44
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Corte/Graxaria = IF(not (DINVPB_PRODUCAOMIUDOS[DESCRFAMILIA]) IN {"SUBPRODUTOS GRAXARIA", "SUBPRODUTOS MIUDOS", "COURO VERDE", "SANGUE", "SANGUE FETAL", "CASCOS E CHIFRES","SUBPRODUTOS GRAXARIA", "SUBPRODUTOS MIUDOS", "GRAXARIA MIUDOS", "SUBPRODUTOS TRIPARIA", "SUB-PRODUTOS"}, "Corte ","Graxaria")
		lineageTag: 98225ca3-593d-4ded-b49f-b4b45a483e28
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _cRendMeta = DINVPB_PRODUCAOMIUDOS[RENDIMENTOPADRAO]/100
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: eb568d5c-65e7-4533-8acd-dbc172fba801
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition DINVPB_PRODUCAOMIUDOS-01cfa5c0-a53d-4036-aacc-1db237d8ad45 = m
		mode: import
		queryGroup: 'Fluxo Industrial'
		source =
				let
				    // 1. Conexão SQL nativa unificando as instâncias de Produção de Miúdos no Oracle com NROEMPRESA fixo
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true, Query="#(lf)            SELECT #(lf)                2 AS NROEMPRESA, #(lf)                e.* #(lf)            FROM DINVPB_PRODUCAO_MIUDOS@dtvind02 e #(lf)            WHERE DATA >=  '01-jan-2026'#(lf)            #(lf)            UNION ALL#(lf)            #(lf)            SELECT #(lf)                4 AS NROEMPRESA, #(lf)                e.* #(lf)            FROM DINVPB_PRODUCAO_MIUDOS@dtvind04 e #(lf)            WHERE DATA >=  '01-jan-2026'#(lf)            #(lf)            UNION ALL#(lf)            #(lf)            SELECT #(lf)                104 AS NROEMPRESA, #(lf)                e.* #(lf)            FROM DINVPB_PRODUCAO_MIUDOS@dtvind104 e #(lf)            WHERE DATA >=  '01-jan-2026'#(lf)            #(lf)            UNION ALL#(lf)            #(lf)            SELECT #(lf)                12 AS NROEMPRESA, #(lf)                e.* #(lf)            FROM DINVPB_PRODUCAO_MIUDOS@dtvind12 e #(lf)            WHERE DATA >=  '01-jan-2026'#(lf)        "]),
				
				    // 2. Filtro da regra de negócio
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each [NROPROGPRODUCAO] <> 288),
				
				    // 3. Seleção final das colunas para o modelo
				    #"Columns removed by Measure Killer" = Table.SelectColumns(#"Linhas Filtradas", {
				        "PESOLIQUIDO",
				        "NROEMPRESA",
				        "DATA",
				        "UNIDADE",
				        "DESCRFAMILIA",
				        "QUANTIDADE2",
				        "DESCRSUBGRUPOPRODUTO",
				        "NROPROGPRODUCAO",
				        "SEQPRODUTO",
				        "DESCRPRODUTO",
				        "RENDIMENTOPADRAO"
				    })
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

