table DINVPB_ENTRADAINDUS
	lineageTag: 0161ee55-f0c4-4db3-ae7d-d00b626c9948

	column NROPROGPRODUCAO
		dataType: int64
		formatString: 0
		lineageTag: 5191a723-fe68-4916-ac28-2c4b14a5366c
		summarizeBy: sum
		sourceColumn: NROPROGPRODUCAO

		annotation SummarizationSetBy = Automatic

	column LOTE
		dataType: int64
		formatString: 0
		lineageTag: b81819d5-ec1f-42dc-a517-86fdc147de6d
		summarizeBy: sum
		sourceColumn: LOTE

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column SEQPRODUTO
		dataType: int64
		formatString: 0
		lineageTag: 6aed05ea-76ac-4415-9b04-095c9a8991f5
		summarizeBy: none
		sourceColumn: SEQPRODUTO

		annotation SummarizationSetBy = Automatic

	column NROEMPRESA
		dataType: double
		lineageTag: ed66364a-9895-47be-9b12-216102ed02f1
		summarizeBy: sum
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _DK = DINVPB_ENTRADAINDUS[NROPROGPRODUCAO]&DINVPB_ENTRADAINDUS[LOTE]&DINVPB_ENTRADAINDUS[NROEMPRESA]
		lineageTag: e9d78c56-beae-4c13-86d3-cb4c5a7c5828
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Turno = IF(DINVPB_ENTRADAINDUS[LOTE] = 20 || DINVPB_ENTRADAINDUS[LOTE] = 21 || DINVPB_ENTRADAINDUS[LOTE] > 30,"Noturno" ,"Diurno")
		lineageTag: dc056073-f7a2-404c-ac3a-4968f559cd6f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition DINVPB_ENTRADAINDUS = m
		mode: import
		queryGroup: 'Fluxo Industrial'
		source = ```
				let
				    // 1. Conexão SQL nativa no Oracle para Entrada Industrializada Unificada (Filial 2)
				    Fonte = Oracle.Database("datavale", [
				        HierarchicalNavigation = true, 
				        Query = "
				            SELECT 
				                2 AS NROEMPRESA, 
				                e.* 
				            FROM TVM_ENTRADAINDUSUNIFICADA e 
				            
				        "
				    ]),
				
				    // 2. Seleção final das colunas para o modelo
				    #"Columns removed by Measure Killer" = Table.SelectColumns(Fonte, {
				        "NROEMPRESA",
				        "NROPROGPRODUCAO",
				        "SEQPRODUTO",
				        "LOTE"
				    })
				in
				    #"Columns removed by Measure Killer"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

