table DINVPB_PAUSATOTAL
	lineageTag: 8e657342-5e2d-476a-bcdc-53307dcfac49

	measure '_Hora Pausas Total' = ```
			CALCULATE(
			    SUMX(
			    DINVPB_PAUSATOTAL, 
			    DATEDIFF(DINVPB_PAUSATOTAL[DTAHORAINICIAL], DINVPB_PAUSATOTAL[DTAHORAFINAL], MINUTE) / 60))
			```
		lineageTag: 0a2bbfa7-2458-47ee-8f5c-2fad9eceadda

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Hora Pausas Total H:H' =
			
			VAR HORADECIMAL = [_Hora Pausas Total]
			VAR HORA = IF(INT(HORADECIMAL) >= 10, INT(HORADECIMAL), "0"&INT(HORADECIMAL))
			VAR DIF = HORADECIMAL - HORA
			VAR MINUTOS = IF(INT(DIF * 60) <10, "0"&INT(DIF * 60), INT(DIF * 60))
			VAR FORMATOTEXTO = FORMAT(HORA & ":" & MINUTOS, "#00:00")
			VAR FORMATONUM = HORA + (MINUTOS / 100)
			RETURN
			if([_Hora Pausas Total]=BLANK(),BLANK(),FORMATOTEXTO)
		lineageTag: 2ad0813b-4667-4cf6-8db8-46295a95c855

	column MOTIVO
		dataType: string
		lineageTag: a69105e9-1d38-43b8-b57c-95aa3c579b27
		summarizeBy: none
		sourceColumn: MOTIVO

		annotation SummarizationSetBy = Automatic

	column NROEMPRESA
		dataType: int64
		formatString: 0
		lineageTag: a61591d1-8b79-49fc-8264-95998b14789d
		summarizeBy: none
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

	column DTAHORAINICIAL
		dataType: dateTime
		formatString: General Date
		lineageTag: 8fadafc8-2efb-4a12-a435-689bab24b00a
		summarizeBy: none
		sourceColumn: DTAHORAINICIAL

		annotation SummarizationSetBy = Automatic

	column DTAHORAFINAL
		dataType: dateTime
		formatString: General Date
		lineageTag: 59ccd27d-7223-4ee2-b6c5-6e949fec7c9e
		summarizeBy: none
		sourceColumn: DTAHORAFINAL

		annotation SummarizationSetBy = Automatic

	column TIPO
		dataType: string
		lineageTag: 728488ad-757e-403a-acfc-7959f7ea94fa
		summarizeBy: none
		sourceColumn: TIPO

		annotation SummarizationSetBy = Automatic

	column CLASSIFAUX
		dataType: int64
		formatString: 0
		lineageTag: 019db485-d1c2-4537-bf3a-84278cad79d3
		summarizeBy: sum
		sourceColumn: CLASSIFAUX

		annotation SummarizationSetBy = Automatic

	column AUXDESCRICAO
		dataType: string
		lineageTag: 57c99e3b-2465-41c5-bca3-4bf00e00fe27
		summarizeBy: none
		sourceColumn: AUXDESCRICAO

		annotation SummarizationSetBy = Automatic

	column TIPOPAUSA
		dataType: string
		lineageTag: 194cac19-fba4-4e03-a387-f2b11065c3e5
		summarizeBy: none
		sourceColumn: TIPOPAUSA

		annotation SummarizationSetBy = Automatic

	column _Verificação = IF(DINVPB_PAUSATOTAL[_Dif] >= 100, "Desconsiderar", "Considerar")
		lineageTag: 4119c49f-08b3-487a-b1bd-341b1b8b6841
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Dif = DATEDIFF(DINVPB_PAUSATOTAL[DTAHORAINICIAL],DINVPB_PAUSATOTAL[DTAHORAFINAL], MINUTE) / 60
		lineageTag: d42f3361-0716-4e87-b801-9e1f4992bac7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _Turno =
			
			var var01 = IF(HOUR(DINVPB_PAUSATOTAL[DTAHORAINICIAL]) >= 16 && DINVPB_PAUSATOTAL[NROEMPRESA] = 2, "Noturno", "Diurno")
			RETURN
			 var01
		lineageTag: 49e11a78-17b2-4b64-b93a-c53f4b3e40eb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Short Date
		lineageTag: 22c5bef1-23a6-4514-9831-b9ba2daec4a4
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition DINVPB_PAUSATOTAL = m
		mode: import
		queryGroup: 'Fluxo Industrial'
		source = ```
				let
				    Fonte = Table.Combine({DINVPB_ABATEPAUSA, DINVPB_PAUSADESOSSA, SINCRONISMO_DIARIOABATE }),
				    
				    // Tratamento preventivo de Nulos na coluna MOTIVO para evitar falhas em funções de Texto
				    #"Motivo Nulo Tratado" = Table.ReplaceValue(Fonte, null, "", Replacer.ReplaceValue, {"MOTIVO"}),
				    
				    #"Primeiros Caracteres Inseridos" = Table.AddColumn(#"Motivo Nulo Tratado", "Primeiros caracteres", each Text.Start([MOTIVO], 2), type text),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Primeiros Caracteres Inseridos",{{"Primeiros caracteres", Int64.Type}}),
				    #"Erros Substituídos" = Table.ReplaceErrorValues(#"Tipo Alterado", {{"Primeiros caracteres", null}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Erros Substituídos",0,null,Replacer.ReplaceValue,{"Primeiros caracteres"}),
				    
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Valor Substituído", "Personalizar", each if [Primeiros caracteres] <> null and [Primeiros caracteres] <= 9 then [Primeiros caracteres] else null),
				    #"Erros Substituídos1" = Table.ReplaceErrorValues(#"Coluna Condicional Adicionada", {{"Personalizar", null}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Erros Substituídos1",{"Primeiros caracteres"}),
				    
				    #"Valor Substituído1" = Table.ReplaceValue(#"Colunas Removidas",",","",Replacer.ReplaceText,{"MOTIVO"}),
				    #"Valor Substituído2" = Table.ReplaceValue(#"Valor Substituído1",".","",Replacer.ReplaceText,{"MOTIVO"}),
				    
				    // Inserção da lógica de busca com segurança contra nulos usando (Texto ?? "")
				    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Valor Substituído2", "Personalizar.1", each 
				        let MotivoUpper = Text.Upper([MOTIVO] ?? "") in
				        if Text.Contains(MotivoUpper, "PSICOFISIOLOGICA") or Text.Contains(MotivoUpper, "PISICOFISIOLOGICA") or Text.Contains(MotivoUpper, "FISIOLOGICA") or Text.Contains(MotivoUpper, "ALMOCO") or Text.Contains(MotivoUpper, "ALMOÇO") or Text.Contains(MotivoUpper, "BANHEIRO") or Text.Contains(MotivoUpper, "JANTA") or Text.Contains(MotivoUpper, "PAUSA TE") or Text.Contains(MotivoUpper, "ERGONOMICA") or Text.Contains(MotivoUpper, "ERGONÔMICA") then 1
				        else if Text.Contains(MotivoUpper, "OPERACIONAL") or Text.Contains(MotivoUpper, "BALANÇA") or Text.Contains(MotivoUpper, "BALANCA") or Text.Contains(MotivoUpper, "BANDA SEM PESAR") or Text.Contains(MotivoUpper, "TROCA DE PRODUÇAO") or Text.Contains(MotivoUpper, "FALTA") or Text.Contains(MotivoUpper, "MEDULA") then 2
				        else if Text.Contains(MotivoUpper, "MANUTENÇÃO") or Text.Contains(MotivoUpper, "ELETRICA") or Text.Contains(MotivoUpper, "ELÉTRICA") or Text.Contains(MotivoUpper, "FALHA") or Text.Contains(MotivoUpper, "MESA DE VICER") then 3
				        else if Text.Contains(MotivoUpper, "SIF") or Text.Contains(MotivoUpper, "DIF") then 4
				        else if Text.Contains(MotivoUpper, "PCC") or Text.Contains(MotivoUpper, "CQ") or Text.Contains(MotivoUpper, "CONTROLE") or Text.Contains(MotivoUpper, "RASTREABILIDADE") then 5
				        else if Text.Contains(MotivoUpper, "IMPRESSORA") or Text.Contains(MotivoUpper, "ESTEIRAS") or Text.Contains(MotivoUpper, "SISTEMA") then 6
				        else if Text.Contains(MotivoUpper, "ENERGIA") or Text.Contains(MotivoUpper, "AGUA") or Text.Contains(MotivoUpper, "ÁGUA") then 7
				        else 2, Int64.Type),
				        
				    #"Coluna Condicional Adicionada2" = Table.AddColumn(#"Coluna Condicional Adicionada1", "CLASSIFAUX", each if [Personalizar] = null then [Personalizar.1] else [Personalizar]),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Coluna Condicional Adicionada2",{"Personalizar", "Personalizar.1"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Removidas1",{{"MOTIVO", type text}, {"NROEMPRESA", Int64.Type}, {"DTAHORAINICIAL", type datetime}, {"DTAHORAFINAL", type datetime}, {"TIPO", type text}, {"CLASSIFAUX", Int64.Type}}),
				    
				    #"Consultas Mescladas" = Table.NestedJoin(#"Tipo Alterado1", {"CLASSIFAUX"}, CLASSIFAUX, {"AUX"}, "CLASSIFAUX.1", JoinKind.LeftOuter),
				    #"CLASSIFAUX.1 Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "CLASSIFAUX.1", {"AUXDESCRICAO"}, {"AUXDESCRICAO"}),
				    
				    #"Coluna Condicional Adicionada3" = Table.AddColumn(#"CLASSIFAUX.1 Expandido", "AUXALMOÇO", each if [CLASSIFAUX] = 1 then [MOTIVO] else null),
				    
				    // --- ALTERAÇÃO AQUI: Validação precisa do tipo de pausa ---
				    #"Coluna Condicional Adicionada4" = Table.AddColumn(#"Coluna Condicional Adicionada3", "TIPOPAUSA", each 
				        let 
				            AuxAlmocoUpper = Text.Upper([AUXALMOÇO] ?? "") 
				        in
				            if Text.Contains(AuxAlmocoUpper, "ALMOÇO") or Text.Contains(AuxAlmocoUpper, "ALMOCO") or Text.Contains(AuxAlmocoUpper, "LANCHE") or Text.Contains(AuxAlmocoUpper, "JANTA") then "ALMOÇO" 
				            else if Text.Contains(AuxAlmocoUpper, "ERGONOMICA") or Text.Contains(AuxAlmocoUpper, "ERGONÔMICA") or Text.Contains(AuxAlmocoUpper, "PSICOFISIOLOGICA") or Text.Contains(AuxAlmocoUpper, "PISICOFISIOLOGICA") or Text.Contains(AuxAlmocoUpper, "FISIOLOGICA") or Text.Contains(AuxAlmocoUpper, "PAUSA TE") or Text.Contains(AuxAlmocoUpper, "BANHEIRO") then "ERGONOMICA"
				            else "OPERACIONAL", type text),
				        
				    #"Erros Substituídos2" = Table.ReplaceErrorValues(#"Coluna Condicional Adicionada4", {{"TIPOPAUSA", "OPERACIONAL"}}),
				    #"Colunas Removidas2" = Table.RemoveColumns(#"Erros Substituídos2",{"AUXALMOÇO"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Removidas2",{{"MOTIVO", type text}, {"NROEMPRESA", Int64.Type}, {"DTAHORAINICIAL", type datetime}, {"DTAHORAFINAL", type datetime}, {"TIPO", type text}, {"CLASSIFAUX", Int64.Type}, {"AUXDESCRICAO", type text}, {"TIPOPAUSA", type text}}),
				    #"Erros Removidos" = Table.RemoveRowsWithErrors(#"Tipo Alterado2", {"DTAHORAFINAL"}),
				    
				    // Tratamento seguro de filtros sem quebrar caso seja null
				    #"Linhas Filtradas" = Table.SelectRows(#"Erros Removidos", each ([MOTIVO] <> null and [MOTIVO] <> "" and [MOTIVO] <> "0" and [MOTIVO] <> "[Em Branco]")),
				    #"Data Inserida" = Table.AddColumn(#"Linhas Filtradas", "Data", each DateTime.Date([DTAHORAINICIAL]), type date),
				    #"Columns removed by Measure Killer" = Table.SelectColumns(#"Data Inserida",{"CLASSIFAUX","DTAHORAFINAL","TIPOPAUSA","NROEMPRESA","Data","MOTIVO","DTAHORAINICIAL","AUXDESCRICAO","TIPO"})
				in
				    #"Columns removed by Measure Killer"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

