table DINVPB_PRODUCAO_BANHA
	lineageTag: 4ec5231b-3ffc-40e7-b457-79ca79ac896e

	column NROEMPRESA
		dataType: double
		formatString: 0
		lineageTag: 4544e366-14e6-4fb2-a199-1fb03232692e
		summarizeBy: sum
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

	column NROPROGPRODUCAO
		dataType: int64
		formatString: 0
		lineageTag: 075585f4-81f1-430e-a69a-e4e41ec47758
		summarizeBy: sum
		sourceColumn: NROPROGPRODUCAO

		annotation SummarizationSetBy = Automatic

	column SEQPRODUTO
		dataType: int64
		formatString: 0
		lineageTag: e4e13219-4a70-4972-92b2-686bcfff8646
		summarizeBy: none
		sourceColumn: SEQPRODUTO

		annotation SummarizationSetBy = Automatic

	column LOTE
		dataType: string
		lineageTag: 09122ea8-5dcb-4e0f-8757-450e0e69b749
		summarizeBy: none
		sourceColumn: LOTE

		annotation SummarizationSetBy = Automatic

	column _DK = DINVPB_PRODUCAO_BANHA[NROPROGPRODUCAO]&DINVPB_PRODUCAO_BANHA[LOTE]&DINVPB_PRODUCAO_BANHA[NROEMPRESA]
		lineageTag: 2a6f4b15-e57a-4b41-bb99-a06afb2e8319
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition DINVPB_PRODUCAO_BANHA = m
		mode: import
		queryGroup: 'Fluxo Industrial'
		source = ```
				let
				    // 1. Conexão SQL nativa no Oracle para Produção de Banha (Filial 4)
				    Fonte = Oracle.Database("datavale", [
				        HierarchicalNavigation = true, 
				        Query = "
				            SELECT 
				                4 AS NROEMPRESA, 
				                e.* 
				            FROM DINVPB_PRODUCAO_BANHA@dtvind04 e 
				            WHERE DATA >= '01-JAN-2026'
				        "
				    ]),
				
				    // 2. Seleção final das colunas para o modelo
				    #"Columns removed by Measure Killer" = Table.SelectColumns(Fonte, {
				        "NROPROGPRODUCAO",
				        "SEQPRODUTO",
				        "LOTE",
				        "NROEMPRESA"
				    })
				in
				    #"Columns removed by Measure Killer"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

