table DINVPB_ENTRADADESOSSA
	lineageTag: 7ee66e71-a9fd-46dc-b7cb-62019e552d2d

	column NROPROGPRODUCAO
		dataType: int64
		lineageTag: 3d83c970-e025-4ae0-9add-76e9d5eb8dfb
		summarizeBy: sum
		sourceColumn: NROPROGPRODUCAO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LOTE
		dataType: int64
		formatString: 0
		lineageTag: 1ae790db-d2ca-43e9-be4a-a4a0489f4b0d
		summarizeBy: sum
		sourceColumn: LOTE

		annotation SummarizationSetBy = Automatic

	column DATAHORA
		dataType: dateTime
		formatString: dd/mm/yyyy hh:nn:ss
		lineageTag: a935c347-479a-4341-a864-7cbb41827dd4
		summarizeBy: none
		sourceColumn: DATAHORA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column DTARENDIMENTO
		dataType: dateTime
		formatString: General Date
		lineageTag: b8fb0558-11fa-4f72-9eb0-a5b501cd16ff
		summarizeBy: none
		sourceColumn: DTARENDIMENTO

		annotation SummarizationSetBy = Automatic

	column SEQPRODUTO
		dataType: int64
		lineageTag: b2bff063-cdd4-418b-803b-e978bfbbb92e
		summarizeBy: sum
		sourceColumn: SEQPRODUTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DESCRFAMILIA
		dataType: string
		lineageTag: 9521ea38-ea9c-4eb4-8454-52722a7d030d
		summarizeBy: none
		sourceColumn: DESCRFAMILIA

		annotation SummarizationSetBy = Automatic

	column QUANTIDADE
		dataType: int64
		lineageTag: 7a3b56cb-d340-43bd-9f64-315dcfb4f4a9
		summarizeBy: sum
		sourceColumn: QUANTIDADE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PESOLIQUIDO
		dataType: double
		lineageTag: 91960cdb-bd63-422e-a573-c3ba243dba52
		summarizeBy: sum
		sourceColumn: PESOLIQUIDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NROEMPRESA
		dataType: int64
		formatString: 0
		lineageTag: 36004908-60b0-4f5a-a38b-8eb37c56ebf8
		summarizeBy: sum
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

	column _DK = DINVPB_ENTRADADESOSSA[NROPROGPRODUCAO]&DINVPB_ENTRADADESOSSA[LOTE]&DINVPB_ENTRADADESOSSA[NROEMPRESA]
		lineageTag: f378315f-2731-4fd5-9835-f3db23aa79be
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '_Contar Linhas' = ```
			CALCULATE(
			    COUNTROWS(DINVPB_ENTRADADESOSSA),
			   ALLEXCEPT(DINVPB_ENTRADADESOSSA, DINVPB_ENTRADADESOSSA[DTARENDIMENTO], DEPARADESOSSA[NROEMPRESA],DINVPB_ENTRADADESOSSA[_Turno]),
			    
			    DINVPB_ENTRADADESOSSA[_Verificação] = "Considerar")
			```
		formatString: 0
		lineageTag: 61fd3985-eaf4-49b3-9aaf-dd0c585a471b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column _DataHoraMax = ```
			
			var var01 = 
			CALCULATE(
			    MAX(DINVPB_ENTRADADESOSSA[DATAHORA]), 
			    ALLEXCEPT(DINVPB_ENTRADADESOSSA, DINVPB_ENTRADADESOSSA[DTARENDIMENTO], DEPARADESOSSA[NROEMPRESA], DINVPB_ENTRADADESOSSA[_Turno]), 
			        DINVPB_ENTRADADESOSSA[_Verificação] = "Considerar", 
			            DINVPB_ENTRADADESOSSA[_Verificação 2]  in {-1,0,1})
			RETURN
			var01
			```
		formatString: General Date
		lineageTag: 3f4f086a-8f03-4548-af94-dbcdacaad648
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _DataHoraMin = ```
			
			var var01 = 
			CALCULATE(
			    MIN(DINVPB_ENTRADADESOSSA[DATAHORA]), 
			    ALLEXCEPT(DINVPB_ENTRADADESOSSA, DINVPB_ENTRADADESOSSA[DTARENDIMENTO], DEPARADESOSSA[NROEMPRESA], DINVPB_ENTRADADESOSSA[_Turno]), 
			        DINVPB_ENTRADADESOSSA[_Verificação] = "Considerar", 
			            DINVPB_ENTRADADESOSSA[_Verificação 2]  in {-1,0,1})
			RETURN
			var01
			```
		formatString: General Date
		lineageTag: ba090bf1-ad6c-434b-a008-bf42130e0cdc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Turno =
			
			var var01 = IF(DINVPB_ENTRADADESOSSA[LOTE] = 18 ||DINVPB_ENTRADADESOSSA[LOTE] = 20 || DINVPB_ENTRADADESOSSA[LOTE] = 21 || DINVPB_ENTRADADESOSSA[LOTE] > 30,"Noturno" ,"Diurno")
			RETURN
			IF(DINVPB_ENTRADADESOSSA[DESCRFAMILIA] = "CUPIM", BLANK(), IF(DINVPB_ENTRADADESOSSA[NROEMPRESA] <> 2, "Diurno",var01))
			
			//Se mudar essa formula, trocar em ENTRADADESOSSA / PRODUÇÃO DESOSSA / DEPARADESOSSA
		lineageTag: c8ceb1b0-6be3-4b44-8e8d-fc92cd790196
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Verificação = ```
			
			var var01 = 
			IF(DINVPB_ENTRADADESOSSA[_TURNO] = "Noturno" &&
			    HOUR(DINVPB_ENTRADADESOSSA[DATAHORA]) >=5 &&
			        HOUR(DINVPB_ENTRADADESOSSA[DATAHORA]) <= 13 
			        || NOT (DINVPB_ENTRADADESOSSA [DESCRFAMILIA]) IN {"DIANTEIRO", "TRASEIRO", "PONTA DE AGULHA", "CARCACA", "LEITAO"},
			            "Desconsiderar","Considerar")
			RETURN
			var01
			```
		lineageTag: f336583f-4810-4278-b56f-0c5d9e2de13e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Sexo
		dataType: string
		lineageTag: 4125736c-228a-42de-b733-0a1b39123208
		summarizeBy: none
		sourceColumn: _Sexo

		annotation SummarizationSetBy = Automatic

	column '_Verificação 2' =
			DATEDIFF(DATE(YEAR(DINVPB_ENTRADADESOSSA[DATAHORA]),MONTH(DINVPB_ENTRADADESOSSA[DATAHORA]),day(DINVPB_ENTRADADESOSSA[DATAHORA])),DINVPB_ENTRADADESOSSA[DTARENDIMENTO],DAY)
			//Diferença entre DATAHORAENTRADA x DATARENDIMENTO
		formatString: 0
		lineageTag: 932f163c-83ea-441a-abbc-e8463050bb5f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition DINVPB_ENTRADADESOSSA-653429b3-82b3-497b-a24d-d38dbee40bab = m
		mode: import
		queryGroup: 'Fluxo Industrial'
		source = ```
				let
				    // 1. Conexão SQL nativa adicionando a coluna NROEMPRESA fixa para cada filial no banco
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true, Query="#(lf)            SELECT #(lf)                2 AS NROEMPRESA, #(lf)                e.* #(lf)            FROM DINVPB_ENTRADADESOSSA@dtvind02 e #(lf)            --WHERE DTARENDIMENTO >= TRUNC(SYSDATE)-60#(lf)WHERE DTARENDIMENTO >= '01-jan-2026'#(lf)            #(lf)            UNION ALL#(lf)            #(lf)            SELECT #(lf)                4 AS NROEMPRESA, #(lf)                e.* #(lf)            FROM DINVPB_ENTRADADESOSSA@dtvind04 e #(lf)            --WHERE DTARENDIMENTO >= TRUNC(SYSDATE)-60#(lf)WHERE DTARENDIMENTO >= '01-jan-2026'#(lf)            #(lf)            UNION ALL#(lf)            #(lf)            SELECT #(lf)                104 AS NROEMPRESA, #(lf)                e.* #(lf)            FROM DINVPB_ENTRADADESOSSA@dtvind104 e #(lf)            --WHERE DTARENDIMENTO >= TRUNC(SYSDATE)-60#(lf)WHERE DTARENDIMENTO >= '01-jan-2026'#(lf)        "]),
				
				    // 2. Coluna condicional _Sexo
				    #"Coluna Condicional Adicionada" = Table.AddColumn(Fonte, "_Sexo", each 
				        if Text.Contains([DESCRICAO], "BOI") then "MACHO" 
				        else if Text.Contains([DESCRICAO], "VACA") then "FEMEA" 
				        else null,
				        type text
				    ),
				
				    // 3. Garantia de tipagem dos dados
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada", {
				        {"NROPROGPRODUCAO", Int64.Type}, 
				        {"DESCRFORMAPRODUCAO", type text}, 
				        {"OBSERVACAO", type text}, 
				        {"TIPOPROGPRODUCAO", type text}, 
				        {"TIPOPRODUTO", type text}, 
				        {"STATUSPROGPRODUCAO", Int64.Type}, 
				        {"LOTE", Int64.Type}, 
				        {"DESCRLOTE", type text}, 
				        {"DATAHORA", type datetime}, 
				        {"DTARENDIMENTO", type datetime}, 
				        {"DTAPRODUCAO", type datetime}, 
				        {"DATAENT", type datetime}, 
				        {"SEQPRODUTO", Int64.Type}, 
				        {"DESCRICAO", type text}, 
				        {"SUBGRUPO", type text}, 
				        {"GRUPO", type text}, 
				        {"FAMILIAPROD", Int64.Type}, 
				        {"DESCRFAMILIA", type text}, 
				        {"CONSERVACAO", type text}, 
				        {"CODBARRAINTERNO", Int64.Type}, 
				        {"QUANTIDADE", Int64.Type}, 
				        {"QTDEMBALAGEM", Int64.Type}, 
				        {"PESOLIQUIDO", type number}, 
				        {"TARA", Int64.Type}, 
				        {"PESOBRUTO", type number}, 
				        {"UNIDADE", type text}, 
				        {"USUARIO", type text}, 
				        {"NROEMPRESA", Int64.Type}, 
				        {"_Sexo", type text}
				    }),
				
				    // 4. Filtro de lotes
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each [LOTE] <> 19 and [LOTE] <> 21),
				
				    // 5. Seleção das colunas utilizadas no modelo
				    #"Columns removed by Measure Killer" = Table.SelectColumns(#"Linhas Filtradas", {
				        "DTARENDIMENTO",
				        "_Sexo",
				        "PESOLIQUIDO",
				        "NROEMPRESA",
				        "DATAHORA",
				        "DESCRFAMILIA",
				        "QUANTIDADE",
				        "NROPROGPRODUCAO",
				        "SEQPRODUTO",
				        "LOTE"
				    })
				in
				    #"Columns removed by Measure Killer"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

