table DINVPB_PAUSATOTAL
	lineageTag: 8e657342-5e2d-476a-bcdc-53307dcfac49

	measure '_Hora Pausas Total' = ```
			CALCULATE(
			    SUMX(
			    DINVPB_PAUSATOTAL, 
			    DATEDIFF(DINVPB_PAUSATOTAL[DTAHORAINICIAL], DINVPB_PAUSATOTAL[DTAHORAFINAL], MINUTE) / 60))
			```
		lineageTag: 0a2bbfa7-2458-47ee-8f5c-2fad9eceadda

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Hora Pausas Total H:H' =
			
			VAR HORADECIMAL = [_Hora Pausas Total]
			VAR HORA = IF(INT(HORADECIMAL) >= 10, INT(HORADECIMAL), "0"&INT(HORADECIMAL))
			VAR DIF = HORADECIMAL - HORA
			VAR MINUTOS = IF(INT(DIF * 60) <10, "0"&INT(DIF * 60), INT(DIF * 60))
			VAR FORMATOTEXTO = FORMAT(HORA & ":" & MINUTOS, "#00:00")
			VAR FORMATONUM = HORA + (MINUTOS / 100)
			RETURN
			if([_Hora Pausas Total]=BLANK(),BLANK(),FORMATOTEXTO)
		lineageTag: 2ad0813b-4667-4cf6-8db8-46295a95c855

	column MOTIVO
		dataType: string
		lineageTag: a69105e9-1d38-43b8-b57c-95aa3c579b27
		summarizeBy: none
		sourceColumn: MOTIVO

		annotation SummarizationSetBy = Automatic

	column NROEMPRESA
		dataType: int64
		formatString: 0
		lineageTag: a61591d1-8b79-49fc-8264-95998b14789d
		summarizeBy: none
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

	column DTAHORAINICIAL
		dataType: dateTime
		formatString: General Date
		lineageTag: 8fadafc8-2efb-4a12-a435-689bab24b00a
		summarizeBy: none
		sourceColumn: DTAHORAINICIAL

		variation Variation
			isDefault
			relationship: 30008517-9ecd-44f7-8f5f-dd83c29e1642
			defaultHierarchy: LocalDateTable_1a28032a-d2fa-4d34-97de-d8983c688b4e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column DTAHORAFINAL
		dataType: dateTime
		formatString: General Date
		lineageTag: 59ccd27d-7223-4ee2-b6c5-6e949fec7c9e
		summarizeBy: none
		sourceColumn: DTAHORAFINAL

		variation Variation
			isDefault
			relationship: 4dcfa9bc-eb7d-42bb-b047-20a1d2bc2cf7
			defaultHierarchy: LocalDateTable_efad3444-f850-4ec7-9e42-22546be722bd.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column TIPO
		dataType: string
		lineageTag: 728488ad-757e-403a-acfc-7959f7ea94fa
		summarizeBy: none
		sourceColumn: TIPO

		annotation SummarizationSetBy = Automatic

	column CLASSIFAUX
		dataType: int64
		formatString: 0
		lineageTag: 019db485-d1c2-4537-bf3a-84278cad79d3
		summarizeBy: sum
		sourceColumn: CLASSIFAUX

		annotation SummarizationSetBy = Automatic

	column AUXDESCRICAO
		dataType: string
		lineageTag: 57c99e3b-2465-41c5-bca3-4bf00e00fe27
		summarizeBy: none
		sourceColumn: AUXDESCRICAO

		annotation SummarizationSetBy = Automatic

	column TIPOPAUSA
		dataType: string
		lineageTag: 194cac19-fba4-4e03-a387-f2b11065c3e5
		summarizeBy: none
		sourceColumn: TIPOPAUSA

		annotation SummarizationSetBy = Automatic

	column _Verificação = IF(DINVPB_PAUSATOTAL[_Dif] >= 100, "Desconsiderar", "Considerar")
		lineageTag: 4119c49f-08b3-487a-b1bd-341b1b8b6841
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Dif = DATEDIFF(DINVPB_PAUSATOTAL[DTAHORAINICIAL],DINVPB_PAUSATOTAL[DTAHORAFINAL], MINUTE) / 60
		lineageTag: d42f3361-0716-4e87-b801-9e1f4992bac7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _Turno =
			
			var var01 = IF(HOUR(DINVPB_PAUSATOTAL[DTAHORAINICIAL]) >= 16 && DINVPB_PAUSATOTAL[NROEMPRESA] = 2, "Noturno", "Diurno")
			RETURN
			 var01
		lineageTag: 49e11a78-17b2-4b64-b93a-c53f4b3e40eb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 22c5bef1-23a6-4514-9831-b9ba2daec4a4
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column UNIDADE
		dataType: string
		lineageTag: 64170ba7-38d9-4f8e-9aed-768e5acbc43b
		summarizeBy: none
		sourceColumn: UNIDADE

		annotation SummarizationSetBy = Automatic

	partition DINVPB_PAUSATOTAL = m
		mode: import
		queryGroup: 'Fluxo Industrial'
		source =
				let
				    Fonte = Table.Combine({DINVPB_ABATEPAUSA, DINVPB_PAUSADESOSSA, SINCRONISMO_DIARIOABATE }),
				    #"Primeiros Caracteres Inseridos" = Table.AddColumn(Fonte, "Primeiros caracteres", each Text.Start([MOTIVO], 2), type text),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Primeiros Caracteres Inseridos",{{"Primeiros caracteres", Int64.Type}}),
				    #"Erros Substituídos" = Table.ReplaceErrorValues(#"Tipo Alterado", {{"Primeiros caracteres", null}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Erros Substituídos",0,null,Replacer.ReplaceValue,{"Primeiros caracteres"}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Valor Substituído", "Personalizar", each if [Primeiros caracteres] <= 9 then [Primeiros caracteres] else null),
				    #"Erros Substituídos1" = Table.ReplaceErrorValues(#"Coluna Condicional Adicionada", {{"Personalizar", null}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Erros Substituídos1",{"Primeiros caracteres"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Colunas Removidas",",","",Replacer.ReplaceText,{"MOTIVO"}),
				    #"Valor Substituído2" = Table.ReplaceValue(#"Valor Substituído1",".","",Replacer.ReplaceText,{"MOTIVO"}),
				    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Valor Substituído2", "Personalizar.1", each if Text.Contains([MOTIVO], "PSICOFISIOLOGICA") then 1 else if Text.Contains([MOTIVO], "ALMOCO") then 1 else if Text.Contains([MOTIVO], "ALMOÇO") then 1 else if Text.Contains([MOTIVO], "BANHEIRO") then 1 else if Text.Contains([MOTIVO], "JANTA") then 1 else if Text.Contains([MOTIVO], "PAUSA TE") then 1 else if Text.Contains([MOTIVO], "JANTA") then 1 else if Text.Contains([MOTIVO], "ERGONOMICA") then 1 else if Text.Contains([MOTIVO], "PISICOFISIOLOGICA") then 1 else if Text.Contains([MOTIVO], "ERGONÔMICA") then 1 else if Text.Contains([MOTIVO], "FISIOLOGICA") then 1 else if Text.Contains([MOTIVO], "MANUTENÇÃO") then 3 else if Text.Contains([MOTIVO], "MANUTENÇÃO") then 3 else if Text.Contains([MOTIVO], "ELETRICA") then 3 else if Text.Contains([MOTIVO], "ELÉTRICA") then 3 else if Text.Contains([MOTIVO], "SIF") then 4 else if Text.Contains([MOTIVO], "DIF") then 4 else if Text.Contains([MOTIVO], "IMPRESSORA") then 6 else if Text.Contains([MOTIVO], "PCC") then 5 else if Text.Contains([MOTIVO], "FALHA") then 3 else if Text.Contains([MOTIVO], "OPERACIONAL") then 2 else if Text.Contains([MOTIVO], "RASTREABILIDADE ") then 5 else if Text.Contains([MOTIVO], "MEDULA") then 2 else if Text.Contains([MOTIVO], "MESA DE VICER") then 3 else if Text.Contains([MOTIVO], "BALANÇA") then 2 else if Text.Contains([MOTIVO], "BALANCA") then 2 else if Text.Contains([MOTIVO], "BANDA SEM PESAR") then 2 else if Text.Contains([MOTIVO], "ESTEIRAS") then 6 else if Text.Contains([MOTIVO], "ENERGIA") then 7 else if Text.Contains([MOTIVO], "AGUA") then 7 else if Text.Contains([MOTIVO], "ÁGUA") then 7 else if Text.Contains([MOTIVO], "FALTA") then 2 else if Text.Contains([MOTIVO], "CQ") then 5 else if Text.Contains([MOTIVO], "CONTROLE") then 5 else if Text.Contains([MOTIVO], "SISTEMA") then 6 else if Text.Contains([MOTIVO], "TROCA DE PRODUÇAO") then 2 else 2),
				    #"Coluna Condicional Adicionada2" = Table.AddColumn(#"Coluna Condicional Adicionada1", "CLASSIFAUX", each if [Personalizar] = null then [Personalizar.1] else [Personalizar]),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Coluna Condicional Adicionada2",{"Personalizar", "Personalizar.1"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Removidas1",{{"MOTIVO", type text}, {"NROEMPRESA", Int64.Type}, {"DTAHORAINICIAL", type datetime}, {"DTAHORAFINAL", type datetime}, {"TIPO", type text}, {"CLASSIFAUX", Int64.Type}}),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Tipo Alterado1", {"CLASSIFAUX"}, CLASSIFAUX, {"AUX"}, "CLASSIFAUX.1", JoinKind.LeftOuter),
				    #"CLASSIFAUX.1 Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "CLASSIFAUX.1", {"AUXDESCRICAO"}, {"AUXDESCRICAO"}),
				    #"Coluna Condicional Adicionada3" = Table.AddColumn(#"CLASSIFAUX.1 Expandido", "AUXALMOÇO", each if [CLASSIFAUX] = 1 then [MOTIVO] else null),
				    #"Coluna Condicional Adicionada4" = Table.AddColumn(#"Coluna Condicional Adicionada3", "TIPOPAUSA", each if Text.Contains([AUXALMOÇO], "ALMOÇO") then "ALMOÇO" else if Text.Contains([AUXALMOÇO], "ALMOCO") then "ALMOÇO" else if Text.Contains([AUXALMOÇO], "LANCHE") then "ALMOÇO" else if Text.Contains([AUXALMOÇO], "JANTA") then "ALMOÇO" else "ERGONOMICA"),
				    #"Erros Substituídos2" = Table.ReplaceErrorValues(#"Coluna Condicional Adicionada4", {{"TIPOPAUSA", null}}),
				    #"Colunas Removidas2" = Table.RemoveColumns(#"Erros Substituídos2",{"AUXALMOÇO"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Removidas2",{{"MOTIVO", type text}, {"NROEMPRESA", Int64.Type}, {"DTAHORAINICIAL", type datetime}, {"DTAHORAFINAL", type datetime}, {"TIPO", type text}, {"CLASSIFAUX", Int64.Type}, {"AUXDESCRICAO", type text}, {"TIPOPAUSA", type text}}),
				    #"Erros Removidos" = Table.RemoveRowsWithErrors(#"Tipo Alterado2", {"DTAHORAFINAL"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Erros Removidos", each ([MOTIVO] <> "" and [MOTIVO] <> "0" and [MOTIVO] <> "[Em Branco]")),
				    #"Data Inserida" = Table.AddColumn(#"Linhas Filtradas", "Data", each DateTime.Date([DTAHORAINICIAL]), type date)
				in
				    #"Data Inserida"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

