table DINVPB_PRODUCAODESOSSA
	lineageTag: d49bd57e-1251-4155-ba7f-0c67eed9210b

	column NROEMPRESA
		dataType: double
		lineageTag: 673e2a36-7b14-4470-ae1f-d745e355712c
		summarizeBy: sum
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NROPROGPRODUCAO
		dataType: int64
		lineageTag: 3abbe2be-328a-4e27-9553-e656d85a2be4
		summarizeBy: sum
		sourceColumn: NROPROGPRODUCAO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TIPOPRODUTO
		dataType: string
		lineageTag: d390c59e-1b85-4be7-92b1-15f0b45b5670
		summarizeBy: none
		sourceColumn: TIPOPRODUTO

		annotation SummarizationSetBy = Automatic

	column LOTE
		dataType: int64
		formatString: 0
		lineageTag: 0511d523-0451-4f8e-8e6d-0b80b3be3858
		summarizeBy: sum
		sourceColumn: LOTE

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column DTARENDIMENTO
		dataType: dateTime
		formatString: General Date
		lineageTag: 972cdf97-c6d2-4dd3-ba7c-2cca575254d7
		summarizeBy: none
		sourceColumn: DTARENDIMENTO

		annotation SummarizationSetBy = Automatic

	column DATAHORAENT
		dataType: dateTime
		formatString: General Date
		lineageTag: cd43a983-aadf-4682-80ea-e285db78c1e0
		summarizeBy: none
		sourceColumn: DATAHORAENT

		annotation SummarizationSetBy = Automatic

	column SEQPRODUTO
		dataType: int64
		lineageTag: 4734e187-6025-44af-84ed-8e6578e701c2
		summarizeBy: sum
		sourceColumn: SEQPRODUTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DESCRPRODUTO
		dataType: string
		lineageTag: b90f56d5-326f-4772-b864-d09a5b562925
		summarizeBy: none
		sourceColumn: DESCRPRODUTO

		annotation SummarizationSetBy = Automatic

	column DESCRGRUPOPRODUTO
		dataType: string
		lineageTag: f2257249-8926-4051-8862-85ff15c5356d
		summarizeBy: none
		sourceColumn: DESCRGRUPOPRODUTO

		annotation SummarizationSetBy = Automatic

	column DESCRSUBGRUPOPRODUTO
		dataType: string
		lineageTag: edc5ae02-d35c-4742-b99d-eeaee843058d
		summarizeBy: none
		sourceColumn: DESCRSUBGRUPOPRODUTO

		annotation SummarizationSetBy = Automatic

	column DESCRFAMILIA
		dataType: string
		lineageTag: bd49fc41-efdd-4669-ab79-1446f785dadc
		summarizeBy: none
		sourceColumn: DESCRFAMILIA

		annotation SummarizationSetBy = Automatic

	column UNIDADE
		dataType: string
		lineageTag: e7809b0c-abb2-4fc8-a56b-e3cedff020b7
		summarizeBy: none
		sourceColumn: UNIDADE

		annotation SummarizationSetBy = Automatic

	column QUANTIDADE2
		dataType: double
		lineageTag: 5fb7819d-fa1e-403b-952d-3cf8d1500e59
		summarizeBy: sum
		sourceColumn: QUANTIDADE2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QTDEMBALAGEM
		dataType: double
		lineageTag: f2004841-cddc-429b-aedb-0c3f81ab5436
		summarizeBy: sum
		sourceColumn: QTDEMBALAGEM

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PESOLIQUIDOSAIDA
		dataType: double
		lineageTag: becf70d3-ce8a-4be0-950f-182761871f5c
		summarizeBy: sum
		sourceColumn: PESOLIQUIDOSAIDA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _DK = DINVPB_PRODUCAODESOSSA[NROPROGPRODUCAO]&DINVPB_PRODUCAODESOSSA[LOTE]&DINVPB_PRODUCAODESOSSA[NROEMPRESA]
		lineageTag: 278d9618-b3c8-44d6-8460-ff47b4864898
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Turno =
			
			var var01 = IF(DINVPB_PRODUCAODESOSSA[LOTE] = 18 ||DINVPB_PRODUCAODESOSSA[LOTE] = 20 || DINVPB_PRODUCAODESOSSA[LOTE] = 21 || DINVPB_PRODUCAODESOSSA[LOTE] > 30 ,"Noturno" ,"Diurno")
			RETURN
			IF(RELATED(DEPARADESOSSA[DESCRFAMILIA]) = "CUPIM", BLANK(), IF(DINVPB_PRODUCAODESOSSA[NROEMPRESA] <> 2, "Diurno",var01))
			//IF( 'DINVPB_PRODUCAODESOSSA'[NROEMPRESA] = 2 , IF('DINVPB_PRODUCAODESOSSA'[LOTE] <=30, "Diurno", "Noturno") , "Noturno")
			//Se mudar essa formula, trocar em ENTRADADESOSSA / PRODUÇÃO DESOSSA / DEPARADESOSSA)))
		lineageTag: 853d85d5-129e-415c-b92a-997001c457a9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '_Contar Linhas' = ```
			CALCULATE(
			    COUNTROWS(DINVPB_PRODUCAODESOSSA), 
			    ALLEXCEPT(DINVPB_PRODUCAODESOSSA, DINVPB_PRODUCAODESOSSA[DTARENDIMENTO], DEPARADESOSSA[NROEMPRESA], DINVPB_PRODUCAODESOSSA[_Turno]), DINVPB_PRODUCAODESOSSA[_Verificação] = "Considerar")
			```
		formatString: 0
		lineageTag: 7dc50009-b9f3-426d-90bb-0b7ee275703f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column _Verificação = ```
			
			IF(DATEDIFF(DINVPB_PRODUCAODESOSSA[DTARENDIMENTO], DINVPB_PRODUCAODESOSSA[DATAHORAENT], HOUR ) >= 30, "Desconsiderar", 
			IF(DATE(YEAR(DINVPB_PRODUCAODESOSSA[DATAHORAENT]), MONTH(DINVPB_PRODUCAODESOSSA[DATAHORAENT]), DAY(DINVPB_PRODUCAODESOSSA[DATAHORAENT])) > DINVPB_PRODUCAODESOSSA[DTARENDIMENTO] && DINVPB_PRODUCAODESOSSA[_Turno] = "Diurno", "Desconsiderar",
			IF( DINVPB_PRODUCAODESOSSA[_Turno] = "Noturno" && HOUR(DINVPB_PRODUCAODESOSSA[DATAHORAENT]) >=5 && HOUR(DINVPB_PRODUCAODESOSSA[DATAHORAENT]) <= 13 || 
			    DINVPB_PRODUCAODESOSSA[_Turno] = "Diurno" && HOUR(DINVPB_PRODUCAODESOSSA[DATAHORAENT]) > 0 && HOUR(DINVPB_PRODUCAODESOSSA[DATAHORAENT]) < 5 ||
			    DINVPB_PRODUCAODESOSSA[_Turno] = "Diurno" && HOUR(DINVPB_PRODUCAODESOSSA[DATAHORAENT]) >= 16 && HOUR(DINVPB_PRODUCAODESOSSA[DATAHORAENT]) <= 23,
			     "Desconsiderar", "Considerar")))
			```
		lineageTag: e232f4c9-4151-4bb8-b804-3e0ead863fe3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Mercado
		dataType: string
		lineageTag: cef0e893-2b9c-4d3c-a1fb-412903031626
		summarizeBy: none
		sourceColumn: _Mercado

		annotation SummarizationSetBy = Automatic

	column _cProduto = DINVPB_PRODUCAODESOSSA[DESCRPRODUTO]&" - "&DINVPB_PRODUCAODESOSSA[SEQPRODUTO]
		lineageTag: 43f20588-e3ee-4866-88cb-998a81efe259
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _ProdutoChina
		dataType: string
		lineageTag: a4a6e78b-632c-4e4f-8baa-ad93bf5f828c
		summarizeBy: none
		sourceColumn: _ProdutoChina

		annotation SummarizationSetBy = Automatic

	column _SK = DINVPB_PRODUCAODESOSSA[NROEMPRESA]&DINVPB_PRODUCAODESOSSA[NROPROGPRODUCAO]&DINVPB_PRODUCAODESOSSA[SEQPRODUTO]
		lineageTag: 7fc1b67e-7d5e-4fe8-952d-385f3c0a77b1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _DIVIDO
		dataType: double
		lineageTag: 42017d5b-de0b-4a9d-bccf-539bc0454ed6
		summarizeBy: sum
		sourceColumn: _DIVIDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _ProdutoFilipinas
		dataType: string
		lineageTag: f9c5aa8b-70ab-4b83-88de-4bd458e21236
		summarizeBy: none
		sourceColumn: _ProdutoFilipinas

		annotation SummarizationSetBy = Automatic

	column _ProdutoSingapura
		dataType: string
		lineageTag: 969022c2-6664-4d93-807b-feb02b20bd0f
		summarizeBy: none
		sourceColumn: _ProdutoSingapura

		annotation SummarizationSetBy = Automatic

	column _ProdutoEuropa
		dataType: string
		lineageTag: 48f670fd-76ae-4092-8dbb-57b2a6ddff40
		summarizeBy: none
		sourceColumn: _ProdutoEuropa

		annotation SummarizationSetBy = Automatic

	column _PK = DINVPB_PRODUCAODESOSSA[DTARENDIMENTO]&DINVPB_PRODUCAODESOSSA[NROPROGPRODUCAO]&DINVPB_PRODUCAODESOSSA[LOTE]&DINVPB_PRODUCAODESOSSA[NROEMPRESA]&DINVPB_PRODUCAODESOSSA[SEQPRODUTO]
		lineageTag: 69751725-00ff-4233-a391-dee2ad99295c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '_Meta Pçs/H Desossa' = ```
			
			SWITCH(
			    TRUE(),
			    DINVPB_PRODUCAODESOSSA[NROEMPRESA] = 2, 500,
			    DINVPB_PRODUCAODESOSSA[NROEMPRESA] = 104, 380,
			    DINVPB_PRODUCAODESOSSA[NROEMPRESA] = 4, 260, BLANK())   
			```
		formatString: 0
		lineageTag: ad804b7d-f638-4a5c-82e2-9024518c6c2c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column _ProdutoPeru
		dataType: string
		lineageTag: 8503c6f9-00f0-40e5-811c-f4cbe8d418f0
		summarizeBy: none
		sourceColumn: _ProdutoPeru

		annotation SummarizationSetBy = Automatic

	column _DataHoraMax = ```
			
			var var01 = 
			CALCULATE(
			    MAX(DINVPB_PRODUCAODESOSSA[DATAHORAENT]), 
			    ALLEXCEPT(DINVPB_PRODUCAODESOSSA, DINVPB_PRODUCAODESOSSA[DTARENDIMENTO], DEPARADESOSSA[NROEMPRESA], DINVPB_PRODUCAODESOSSA[_Turno]), 
			        DINVPB_PRODUCAODESOSSA[_Verificação] = "Considerar", 
			            DINVPB_PRODUCAODESOSSA[_Verificação 2]  in {-1,0,1})
			RETURN
			var01
			```
		lineageTag: 3e91044e-d20e-4a34-b0e9-3fa1742e0c16
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _DataHoraMin = ```
			
			var var01 = 
			CALCULATE(
			    MIN(DINVPB_PRODUCAODESOSSA[DATAHORAENT]), 
			    ALLEXCEPT(DINVPB_PRODUCAODESOSSA, DINVPB_PRODUCAODESOSSA[DTARENDIMENTO], DEPARADESOSSA[NROEMPRESA], DINVPB_PRODUCAODESOSSA[_Turno]), 
			        DINVPB_PRODUCAODESOSSA[_Verificação] = "Considerar", 
			            DINVPB_PRODUCAODESOSSA[_Verificação 2]  in {-1,0,1})
			RETURN
			var01
			```
		lineageTag: 4efa7f1a-c468-4fd9-bf56-45186908d601
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '_Verificação 2' = DATEDIFF(DATE(YEAR(DINVPB_PRODUCAODESOSSA[DATAHORAENT]),MONTH(DINVPB_PRODUCAODESOSSA[DATAHORAENT]),day(DINVPB_PRODUCAODESOSSA[DATAHORAENT])),DINVPB_PRODUCAODESOSSA[DATAHORAENT],DAY)
		formatString: 0
		lineageTag: f9b2598a-fba3-4c3f-b8a2-512ae667433e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition DINVPB_PRODUCAODESOSSA-2c87737b-dc80-4c6a-a832-3c59abdbef6a = m
		mode: import
		queryGroup: 'Fluxo Industrial'
		source =
				let
				    // 1. Conexão SQL nativa unificando as instâncias de Produção Desossa no Oracle com NROEMPRESA fixo
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true, Query="#(lf)            SELECT #(lf)                2 AS NROEMPRESA, #(lf)                e.* #(lf)            FROM DINVPB_PRODUCAODESOSSA@dtvind02 e #(lf)            WHERE DTARENDIMENTO >= TRUNC(SYSDATE)-90#(lf)            #(lf)            UNION ALL#(lf)            #(lf)            SELECT #(lf)                4 AS NROEMPRESA, #(lf)                e.* #(lf)            FROM DINVPB_PRODUCAODESOSSA@dtvind04 e #(lf)            WHERE DTARENDIMENTO >= TRUNC(SYSDATE)-90#(lf)            #(lf)            UNION ALL#(lf)            #(lf)            SELECT #(lf)                104 AS NROEMPRESA, #(lf)                e.* #(lf)            FROM DINVPB_PRODUCAODESOSSA@dtvind104 e #(lf)            WHERE DTARENDIMENTO >= TRUNC(SYSDATE)-90#(lf)        "]),
				
				    // 2. Colunas Condicionais de Negócio
				    #"Coluna Condicional Adicionada" = Table.AddColumn(Fonte, "_Mercado", each if Text.Contains([DESCRSUBGRUPOPRODUTO], "EXP") then "ME" else "MI", type text),
				    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Coluna Condicional Adicionada", "_ProdutoChina", each if Text.Contains([DESCRPRODUTO], "CHINA") then "CHN" else null, type text),
				    #"Coluna Condicional Adicionada2" = Table.AddColumn(#"Coluna Condicional Adicionada1", "_DIVIDO", each if Text.Contains([DESCRPRODUTO], "AO MEIO") then 2 else null, type number),
				    #"Coluna Condicional Adicionada3" = Table.AddColumn(#"Coluna Condicional Adicionada2", "_ProdutoFilipinas", each if Text.Contains([DESCRPRODUTO], "FILIPINAS") then "FILIPINAS" else null, type text),
				    #"Coluna Condicional Adicionada4" = Table.AddColumn(#"Coluna Condicional Adicionada3", "_ProdutoSingapura", each if Text.Contains([DESCRPRODUTO], "SINGAPURA") then "SINGAPURA" else null, type text),
				    #"Coluna Condicional Adicionada5" = Table.AddColumn(#"Coluna Condicional Adicionada4", "_ProdutoEuropa", each if Text.Contains([DESCRPRODUTO], "U.E") then "Europa" else null, type text),
				    #"Coluna Condicional Adicionada6" = Table.AddColumn(#"Coluna Condicional Adicionada5", "_ProdutoPeru", each if Text.Contains([DESCRPRODUTO], "PERU") then "Peru" else null, type text),
				
				    // 3. Renomeação de Coluna e Filtros
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Coluna Condicional Adicionada6", {{"PESOLIQUIDO", "PESOLIQUIDOSAIDA"}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Renomeadas", each Text.From([LOTE]) <> "19"),
				
				    // 4. Seleção final das colunas para o modelo
				    #"Columns removed by Measure Killer" = Table.SelectColumns(#"Linhas Filtradas", {
				        "NROPROGPRODUCAO",
				        "_ProdutoSingapura",
				        "PESOLIQUIDOSAIDA",
				        "SEQPRODUTO",
				        "LOTE",
				        "DESCRPRODUTO",
				        "_ProdutoChina",
				        "_ProdutoPeru",
				        "DTARENDIMENTO",
				        "QTDEMBALAGEM",
				        "_ProdutoEuropa",
				        "DATAHORAENT",
				        "NROEMPRESA",
				        "DESCRGRUPOPRODUTO",
				        "UNIDADE",
				        "_DIVIDO",
				        "DESCRFAMILIA",
				        "QUANTIDADE2",
				        "TIPOPRODUTO",
				        "DESCRSUBGRUPOPRODUTO",
				        "_ProdutoFilipinas",
				        "_Mercado"
				    })
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

