table DINVPB_PESOVIVO
	lineageTag: 7d46310d-8fe6-4739-838d-d513cb973f68

	column DATA
		dataType: dateTime
		formatString: General Date
		lineageTag: 41c71f49-b3eb-4225-9801-7e4fd9ba5d43
		summarizeBy: none
		sourceColumn: DATA

		annotation SummarizationSetBy = Automatic

	column PESOMETA
		dataType: double
		lineageTag: 509bd819-2343-483e-a013-6a37505ad319
		summarizeBy: sum
		sourceColumn: PESOMETA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NROEMPRESA
		dataType: double
		lineageTag: a677e000-d44c-46b7-b89b-72d64def528d
		summarizeBy: none
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _Turno = "Diurno"
		lineageTag: 23e3fedd-73ab-4b1a-88e3-0c1f6294bb4f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition DINVPB_PESOVIVO = m
		mode: import
		queryGroup: 'Fluxo Industrial'
		source =
				let
				    // 1. Conexão SQL nativa unificando as instâncias de Peso Vivo no Oracle com NROEMPRESA fixo
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true, Query="#(lf)                       #(lf)            SELECT #(lf)                4 AS NROEMPRESA, #(lf)                e.* #(lf)            FROM DINVPB_PESOVIVO@dtvind04 e #(lf)            WHERE DATA >= '01-JAN-2026'#(lf)            #(lf)            UNION ALL#(lf)            #(lf)            SELECT #(lf)                104 AS NROEMPRESA, #(lf)                e.* #(lf)            FROM DINVPB_PESOVIVO@dtvind104 e #(lf)            WHERE DATA >= '01-JAN-2026'#(lf)            #(lf)           "]),
				
				    // 2. Seleção final das colunas solicitadas para o modelo
				    #"Columns removed by Measure Killer" = Table.SelectColumns(Fonte, {
				        "PESOMETA",
				        "NROEMPRESA",
				        "DATA"
				    })
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

