table DINVPB_ABATE
	lineageTag: 18c07a2e-91a7-4247-8206-791e1e4be504

	column NROEMPRESA
		dataType: int64
		lineageTag: e0726626-35a2-45f5-9552-bb9cca287416
		summarizeBy: none
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DATA
		dataType: dateTime
		formatString: Short Date
		lineageTag: dda42ce3-ef71-4195-b88c-afa069c491a2
		summarizeBy: none
		sourceColumn: DATA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PESOLIQUIDO
		dataType: double
		lineageTag: a2c72071-4041-4315-8e42-26235fb0a361
		summarizeBy: sum
		sourceColumn: PESOLIQUIDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DESCRSEXO
		dataType: string
		lineageTag: e5798f44-66b9-4f08-a1b7-c9061419162e
		summarizeBy: none
		sourceColumn: DESCRSEXO

		annotation SummarizationSetBy = Automatic

	column DESCRREDCLASSIFABATE
		dataType: string
		lineageTag: c1b2afa3-b72b-4d18-9885-4fa7395aea0b
		summarizeBy: none
		sourceColumn: DESCRREDCLASSIFABATE

		annotation SummarizationSetBy = Automatic

	column DESCRREDCLASSIFCONFORMIDADE
		dataType: string
		lineageTag: 379a632c-9077-48a5-a749-753ad20c77a1
		summarizeBy: none
		sourceColumn: DESCRREDCLASSIFCONFORMIDADE

		annotation SummarizationSetBy = Automatic

	column NROPEDIDO
		dataType: int64
		lineageTag: a9355d93-56c8-431d-a97d-facfef019962
		summarizeBy: sum
		sourceColumn: NROPEDIDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SEQPESSOA
		dataType: int64
		lineageTag: 59da9fbd-07df-4d43-9168-2fd522ef4b6b
		summarizeBy: none
		sourceColumn: SEQPESSOA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Data e Hora'
		dataType: dateTime
		formatString: General Date
		lineageTag: f938d105-ff00-4132-9535-580c2a05e534
		summarizeBy: none
		sourceColumn: Data e Hora

		annotation SummarizationSetBy = Automatic

	column CLASSIFICAÇÃO
		dataType: string
		lineageTag: a1288c2f-037d-44c2-8d0c-456b7c6a0c33
		summarizeBy: none
		sourceColumn: CLASSIFICAÇÃO

		annotation SummarizationSetBy = Automatic

	column _Origem = IF(or(DINVPB_ABATE[SEQPESSOA] IN { 108386 , 109457 , 164805 , 180622}, RELATED(FPBI_PESSOA[GRUPO]) in {"INTEGRADOS - TERMINACAO","INTEGRADOS - CRECHE","INTEGRADOS - CRECHE REFUGO","INTEGRADOS - UPL", "INTEGRADOS - TERMINACAO REFUGO"}), "Próprio", IF(DINVPB_ABATE[SEQPESSOA] = 248257, "Boitel", "Terceiro"))
		lineageTag: ecb76d10-6399-4ba6-ab51-bddb96342b0a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '_Meta Cbç/H Abate' = ```
			
			SWITCH(
			    TRUE(),
			    DINVPB_ABATE[NROEMPRESA] = 2, 120,
			    DINVPB_ABATE[NROEMPRESA] = 12, 100,
			    DINVPB_ABATE[NROEMPRESA] = 104, 300,
			    DINVPB_ABATE[NROEMPRESA] = 4, 200, BLANK())   
			```
		formatString: 0
		lineageTag: bcf02b57-64c4-4ed0-bc45-029410f42202
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '_Meta Orçado Abate' = ```
			
			var ANO = 
			    SWITCH(
			    TRUE(),
			    DINVPB_ABATE[NROEMPRESA] = 2, 1500,
			    DINVPB_ABATE[NROEMPRESA] = 12, 600,
			    DINVPB_ABATE[NROEMPRESA] = 104, 1500,
			    DINVPB_ABATE[NROEMPRESA] = 4, 1800, BLANK())
			var TRI = 
			    SWITCH(
			    TRUE(),
			    DINVPB_ABATE[NROEMPRESA] = 2, 850,
			    DINVPB_ABATE[NROEMPRESA] = 12, 450,
			    DINVPB_ABATE[NROEMPRESA] = 104, 1350,
			    DINVPB_ABATE[NROEMPRESA] = 4, 1400, BLANK())
			var FDS = 
			    SWITCH(
			    TRUE(),
			    DINVPB_ABATE[NROEMPRESA] = 2, IF (MONTH(DINVPB_ABATE[DATA]) IN {1,2}, TRI, ANO),
			    DINVPB_ABATE[NROEMPRESA] = 12, IF (MONTH(DINVPB_ABATE[DATA]) IN {1,2}, TRI, ANO),
			    DINVPB_ABATE[NROEMPRESA] = 104, 0,
			    DINVPB_ABATE[NROEMPRESA] = 4, 0, BLANK())
			RETURN
			IF(WEEKDAY(DINVPB_ABATE[DATA],1) = 1 , BLANK(), 
			    IF(WEEKDAY(DINVPB_ABATE[DATA],1) = 7 , FDS, 
			        IF(YEAR(DINVPB_ABATE[DATA]) = 2024 , IF (MONTH(DINVPB_ABATE[DATA]) IN {1,2}, TRI, ANO))))
			```
		formatString: #,0
		lineageTag: 5185eea0-7cba-4cdd-a176-bd20fa13f049
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column CLASSIFICACAORED
		dataType: string
		lineageTag: e14c2457-2d5e-497c-8e68-94564e838fd6
		summarizeBy: none
		sourceColumn: CLASSIFICACAORED

		annotation SummarizationSetBy = Automatic

	column _NOVACLASSIFRED = ```
			
			SWITCH( 
			    TRUE(),
			    DINVPB_ABATE[DESCRREDCLASSIFABATE] = "G.", "GRAXARIA",
			    DINVPB_ABATE[DESCRREDCLASSIFABATE] = "O.", "CONSERVA",
			    DINVPB_ABATE[DESCRREDCLASSIFABATE] = "E.C.", "EMB.COZIDO",
			    DINVPB_ABATE[DESCRREDCLASSIFABATE] = "TF", "TRAT.FRIO",
			    DINVPB_ABATE[DESCRREDCLASSIFABATE] = "GRAXARIA", "GRAXARIA",
			    DINVPB_ABATE[DESCRREDCLASSIFABATE] = "CONSERVA", "CONSERVA",
			    DINVPB_ABATE[DESCRREDCLASSIFABATE] <> BLANK(),"NORMAL",
			    DINVPB_ABATE[DESCRREDCLASSIFABATE])
			```
		lineageTag: 14c15c74-1552-4b9f-ac1c-d2b03f81b474
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Pk = DINVPB_ABATE[NROEMPRESA]&DINVPB_ABATE[NROPEDIDO]
		lineageTag: 6521ed68-1a67-44e2-a98f-6e091548c196
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Data e Hora Ajustada' = ```
			
			VAR DataHora = DINVPB_ABATE[Data e Hora]
			VAR Hora = DataHora - TRUNC ( DataHora )
			RETURN
			IF (
			    Hora >= TIME ( 0, 0, 0 )
			        && Hora < TIME ( 4, 0, 0 ),
			     DataHora  + 1,
			     DataHora 
			)
			
			
			
			```
		dataType: dateTime
		formatString: General Date
		lineageTag: 947b92ef-db23-429d-b83f-eb7f30cb79d0
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Turno
		dataType: string
		lineageTag: 596c7169-64cd-4781-9b02-224d4b905648
		summarizeBy: none
		sourceColumn: Turno

		annotation SummarizationSetBy = Automatic

	column _Sexo
		dataType: string
		lineageTag: 33375b7a-a55e-4c77-8719-0aa4f9535bd1
		summarizeBy: none
		sourceColumn: _Sexo

		annotation SummarizationSetBy = Automatic

	column _HoraMax
		dataType: dateTime
		formatString: General Date
		lineageTag: 835effdc-5b74-4a97-a7b3-b68d046816f9
		summarizeBy: none
		sourceColumn: _HoraMax

		annotation SummarizationSetBy = Automatic

	column _HoraMin
		dataType: dateTime
		formatString: General Date
		lineageTag: 2345f40b-7241-49cc-8a54-51bae3fa248e
		summarizeBy: none
		sourceColumn: _HoraMin

		annotation SummarizationSetBy = Automatic

	column '_Contar Linhas'
		dataType: double
		lineageTag: 4cce8219-88da-4211-bd2d-83b72e9a33e6
		summarizeBy: sum
		sourceColumn: _Contar Linhas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _MinutosTrabalhados
		dataType: double
		lineageTag: 90149401-e5c8-433e-953d-a41f2efbb6d8
		summarizeBy: sum
		sourceColumn: _MinutosTrabalhados

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DINVPB_ABATE-015b6fe3-14d3-4263-8b79-ed9f3ce91f0c = m
		mode: import
		queryGroup: 'Fluxo Industrial'
		source = ```
				let
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true, Query="#(lf)        SELECT e.NROEMPRESA,#(tab)e.DATA,#(tab)e.HR,#(tab)e.SEQUENCIADIA,#(tab)e.SEQPRODUTO,#(tab)e.DESCRPRODUTO,#(tab)e.BANDA,#(tab)e.PESOLIQUIDO,#(tab)e.PESOLIQUIDOQUEBRA,#(tab)e.SEXO,#(tab)e.DESCRSEXO,#(tab)e.DESCRREDCLASSIFICACAO,#(tab)e.DESCRCLASSIFICACAO,#(tab)e.SEQCLASSIFABATE,#(tab)e.DESCRCLASSIFABATE,#(tab)e.DESCRCLASSIFACABAMENTO,#(tab)e.DESCRREDCLASSIFABATE,#(tab)e.SEQCLASSIFMATURIDADE,#(tab)e.DESCRCLASSIFMATURIDADE,#(tab)e.DESCRREDCLASSIFMATURIDADE,#(tab)e.SEQCLASSIFRACA,#(tab)e.DESCRCLASSIFRACA,#(tab)e.SEQCLASSIFCONFORMIDADE,#(tab)e.DESCRCLASSIFCONFORMIDADE,#(tab)e.DESCRREDCLASSIFCONFORMIDADE,#(tab)e.ASPERSAO,#(tab)e.CONFORME,#(tab)e.NROPEDIDO,#(tab)e.NROLOTE,#(tab)e.SEQVENDEDOR,#(tab)e.SEQPESSOA,#(tab)e.NOMEPESSOA,#(tab)e.NOMEPROPRIEDADE,#(tab)e.CIDADEPROPRIEDADE,#(tab)e.UFPROPRIEDADE,#(tab)e.GRUPOPROD,#(tab)e.SUBGRUPOPROD,#(tab)e.FAMILIAPROD#(lf) FROM DINVPB_ABATE@dtvind02 e WHERE DATA>= '01-jan-2026'#(lf)        UNION ALL#(lf)        SELECT e.NROEMPRESA,#(tab)e.DATA,#(tab)e.HR,#(tab)e.SEQUENCIADIA,#(tab)e.SEQPRODUTO,#(tab)e.DESCRPRODUTO,#(tab)e.BANDA,#(tab)e.PESOLIQUIDO,#(tab)e.PESOLIQUIDOQUEBRA,#(tab)e.SEXO,#(tab)e.DESCRSEXO,#(tab)e.DESCRREDCLASSIFICACAO,#(tab)e.DESCRCLASSIFICACAO,#(tab)e.SEQCLASSIFABATE,#(tab)e.DESCRCLASSIFABATE,#(tab)e.DESCRCLASSIFACABAMENTO,#(tab)e.DESCRREDCLASSIFABATE,#(tab)e.SEQCLASSIFMATURIDADE,#(tab)e.DESCRCLASSIFMATURIDADE,#(tab)e.DESCRREDCLASSIFMATURIDADE,#(tab)e.SEQCLASSIFRACA,#(tab)e.DESCRCLASSIFRACA,#(tab)e.SEQCLASSIFCONFORMIDADE,#(tab)e.DESCRCLASSIFCONFORMIDADE,#(tab)e.DESCRREDCLASSIFCONFORMIDADE,#(tab)e.ASPERSAO,#(tab)e.CONFORME,#(tab)e.NROPEDIDO,#(tab)e.NROLOTE,#(tab)e.SEQVENDEDOR,#(tab)e.SEQPESSOA,#(tab)e.NOMEPESSOA,#(tab)e.NOMEPROPRIEDADE,#(tab)e.CIDADEPROPRIEDADE,#(tab)e.UFPROPRIEDADE,#(tab)e.GRUPOPROD,#(tab)e.SUBGRUPOPROD,#(tab)e.FAMILIAPROD#(lf) FROM DINVPB_ABATE@dtvind04 e WHERE DATA>= '01-jan-2026'#(lf)        UNION ALL#(lf)        SELECT e.NROEMPRESA,#(tab)e.DATA,#(tab)e.HR,#(tab)e.SEQUENCIADIA,#(tab)e.SEQPRODUTO,#(tab)e.DESCRPRODUTO,#(tab)e.BANDA,#(tab)e.PESOLIQUIDO,#(tab)e.PESOLIQUIDOQUEBRA,#(tab)e.SEXO,#(tab)e.DESCRSEXO,#(tab)e.DESCRREDCLASSIFICACAO,#(tab)e.DESCRCLASSIFICACAO,#(tab)e.SEQCLASSIFABATE,#(tab)e.DESCRCLASSIFABATE,#(tab)e.DESCRCLASSIFACABAMENTO,#(tab)e.DESCRREDCLASSIFABATE,#(tab)e.SEQCLASSIFMATURIDADE,#(tab)e.DESCRCLASSIFMATURIDADE,#(tab)e.DESCRREDCLASSIFMATURIDADE,#(tab)e.SEQCLASSIFRACA,#(tab)e.DESCRCLASSIFRACA,#(tab)e.SEQCLASSIFCONFORMIDADE,#(tab)e.DESCRCLASSIFCONFORMIDADE,#(tab)e.DESCRREDCLASSIFCONFORMIDADE,#(tab)e.ASPERSAO,#(tab)e.CONFORME,#(tab)e.NROPEDIDO,#(tab)e.NROLOTE,#(tab)e.SEQVENDEDOR,#(tab)e.SEQPESSOA,#(tab)e.NOMEPESSOA,#(tab)e.NOMEPROPRIEDADE,#(tab)e.CIDADEPROPRIEDADE,#(tab)e.UFPROPRIEDADE,#(tab)e.GRUPOPROD,#(tab)e.SUBGRUPOPROD,#(tab)e.FAMILIAPROD#(lf) FROM DINVPB_ABATE@dtvind12 e WHERE DATA>= '01-jan-2026'#(lf)        UNION ALL#(lf)        SELECT e.NROEMPRESA,#(tab)e.DATA,#(tab)e.HR,#(tab)e.SEQUENCIADIA,#(tab)e.SEQPRODUTO,#(tab)e.DESCRPRODUTO,#(tab)e.BANDA,#(tab)e.PESOLIQUIDO,#(tab)e.PESOLIQUIDOQUEBRA,#(tab)e.SEXO,#(tab)e.DESCRSEXO,#(tab)e.DESCRREDCLASSIFICACAO,#(tab)e.DESCRCLASSIFICACAO,#(tab)e.SEQCLASSIFABATE,#(tab)e.DESCRCLASSIFABATE,#(tab)e.DESCRCLASSIFACABAMENTO,#(tab)e.DESCRREDCLASSIFABATE,#(tab)e.SEQCLASSIFMATURIDADE,#(tab)e.DESCRCLASSIFMATURIDADE,#(tab)e.DESCRREDCLASSIFMATURIDADE,#(tab)e.SEQCLASSIFRACA,#(tab)e.DESCRCLASSIFRACA,#(tab)e.SEQCLASSIFCONFORMIDADE,#(tab)e.DESCRCLASSIFCONFORMIDADE,#(tab)e.DESCRREDCLASSIFCONFORMIDADE,#(tab)e.ASPERSAO,#(tab)e.CONFORME,#(tab)e.NROPEDIDO,#(tab)e.NROLOTE,#(tab)e.SEQVENDEDOR,#(tab)e.SEQPESSOA,#(tab)e.NOMEPESSOA,#(tab)e.NOMEPROPRIEDADE,#(tab)e.CIDADEPROPRIEDADE,#(tab)e.UFPROPRIEDADE,#(tab)e.GRUPOPROD,#(tab)e.SUBGRUPOPROD,#(tab)e.FAMILIAPROD#(lf) FROM DINVPB_ABATE@dtvind104 e WHERE DATA>= '01-jan-2026'#(lf)    "]),
				
				
				    // Resto do processamento
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte, {
				        {"NROEMPRESA", Int64.Type}, {"DATA", type date}, {"HR", type time}, {"SEQUENCIADIA", Int64.Type},
				        {"SEQPRODUTO", Int64.Type}, {"DESCRPRODUTO", type text}, {"BANDA", type text}, {"PESOLIQUIDO", type number},
				        {"PESOLIQUIDOQUEBRA", type number}, {"SEXO", type text}, {"DESCRSEXO", type text}, {"DESCRREDCLASSIFICACAO", type text},
				        {"DESCRCLASSIFICACAO", type text}, {"SEQCLASSIFABATE", Int64.Type}, {"DESCRCLASSIFABATE", type text},
				        {"DESCRCLASSIFACABAMENTO", type text}, {"DESCRREDCLASSIFABATE", type text}, {"SEQCLASSIFMATURIDADE", Int64.Type},
				        {"DESCRCLASSIFMATURIDADE", type text}, {"DESCRREDCLASSIFMATURIDADE", Int64.Type}, {"SEQCLASSIFRACA", Int64.Type},
				        {"DESCRCLASSIFRACA", type text}, {"SEQCLASSIFCONFORMIDADE", Int64.Type}, {"DESCRCLASSIFCONFORMIDADE", type text},
				        {"DESCRREDCLASSIFCONFORMIDADE", type text}, {"ASPERSAO", type text}, {"CONFORME", type text},
				        {"NROPEDIDO", Int64.Type}, {"NROLOTE", Int64.Type}, {"SEQVENDEDOR", Int64.Type}, {"SEQPESSOA", Int64.Type},
				        {"NOMEPESSOA", type text}, {"NOMEPROPRIEDADE", type text}, {"CIDADEPROPRIEDADE", type text},
				        {"UFPROPRIEDADE", type text}, {"GRUPOPROD", Int64.Type}, {"SUBGRUPOPROD", Int64.Type}, {"FAMILIAPROD", Int64.Type}
				    }),
				    #"Data e Hora Mescladas Inseridas" = Table.AddColumn(#"Tipo Alterado", "Data e Hora", each [DATA] & [HR], type datetime),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Data e Hora Mescladas Inseridas", {"DESCRREDCLASSIFCONFORMIDADE"}, #"Classificação Aux", {"DESCRREDCLASSIFCONFORMIDADE"}, "Classificação Aux", JoinKind.LeftOuter),
				    #"Classificação Aux Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "Classificação Aux", {"CLASSIFICAÇÃO", "CLASSIFICACAORED"}, {"CLASSIFICAÇÃO", "CLASSIFICACAORED"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Classificação Aux Expandido", {
				        {"NROEMPRESA", Int64.Type}, {"DATA", type date}, {"HR", type time}, {"SEQUENCIADIA", Int64.Type},
				        {"SEQPRODUTO", Int64.Type}, {"DESCRPRODUTO", type text}, {"BANDA", type text}, {"PESOLIQUIDO", type number},
				        {"PESOLIQUIDOQUEBRA", type number}, {"SEXO", type text}, {"DESCRSEXO", type text}, {"DESCRREDCLASSIFICACAO", type text},
				        {"DESCRCLASSIFICACAO", type text}, {"SEQCLASSIFABATE", Int64.Type}, {"DESCRCLASSIFABATE", type text},
				        {"DESCRCLASSIFACABAMENTO", type text}, {"DESCRREDCLASSIFABATE", type text}, {"SEQCLASSIFMATURIDADE", Int64.Type},
				        {"DESCRCLASSIFMATURIDADE", type text}, {"DESCRREDCLASSIFMATURIDADE", Int64.Type}, {"SEQCLASSIFRACA", Int64.Type},
				        {"DESCRCLASSIFRACA", type text}, {"SEQCLASSIFCONFORMIDADE", Int64.Type}, {"DESCRCLASSIFCONFORMIDADE", type text},
				        {"DESCRREDCLASSIFCONFORMIDADE", type text}, {"ASPERSAO", type text}, {"CONFORME", type text},
				        {"NROPEDIDO", Int64.Type}, {"NROLOTE", Int64.Type}, {"SEQVENDEDOR", Int64.Type}, {"SEQPESSOA", Int64.Type},
				        {"NOMEPESSOA", type text}, {"NOMEPROPRIEDADE", type text}, {"CIDADEPROPRIEDADE", type text},
				        {"UFPROPRIEDADE", type text}, {"GRUPOPROD", Int64.Type}, {"SUBGRUPOPROD", Int64.Type},
				        {"FAMILIAPROD", Int64.Type}, {"Data e Hora", type datetime}, {"CLASSIFICAÇÃO", type text}
				    }),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado1"),
				    #"Columns removed by Measure Killer"= Table.SelectColumns(#"Duplicatas Removidas",{"DESCRSEXO","CLASSIFICAÇÃO","PESOLIQUIDO","NROEMPRESA","DATA","DESCRREDCLASSIFCONFORMIDADE","DESCRREDCLASSIFABATE","NROPEDIDO","Data e Hora","SEQPESSOA","CLASSIFICACAORED"}),
				
				// 1. Ajuste o nome #"Etapa Anterior" para o nome da última etapa do seu Power Query
				    FonteDados = #"Columns removed by Measure Killer",
				
				    // 2. Garante tipagem correta de Data/Hora e Empresa para evitar erros nas comparações
				    #"Tipos Garantidos" = Table.TransformColumnTypes(FonteDados, {
				        {"Data e Hora", type datetime},
				        {"DATA", type date},
				        {"NROEMPRESA", Int64.Type},
				        {"DESCRSEXO", type text}
				    }),
				
				    // 3. Tradução do 'Turno' (DAX) para Power Query (M)
				    // Extrai o componente de horário Time.From([Data e Hora]) para validar a janela das 04:00:00 às 15:59:59
				    #"Coluna Turno Adicionada" = Table.AddColumn(#"Tipos Garantidos", "Turno", each 
				        if [NROEMPRESA] = 4 or [NROEMPRESA] = 12 or [NROEMPRESA] = 104 then 
				            "Diurno"
				        else if Time.From([Data e Hora]) >= #time(4, 0, 0) and Time.From([Data e Hora]) <= #time(15, 59, 59) then 
				            "Diurno"
				        else 
				            "Noturno", 
				        type text
				    ),
				
				    // 4. Tradução da coluna _Sexo para M
				    #"Coluna _Sexo Adicionada" = Table.AddColumn(#"Coluna Turno Adicionada", "_Sexo", each 
				        if [NROEMPRESA] = 2 or [NROEMPRESA] = 12 then 
				            if [DESCRSEXO] = "Macho Inteiro" or [DESCRSEXO] = "Macho Castrado" then "Macho" else [DESCRSEXO]
				        else if [NROEMPRESA] = 4 or [NROEMPRESA] = 104 then 
				            "Suino" 
				        else 
				            [DESCRSEXO], 
				        type text
				    ),
				
				    // 5. Criação da coluna auxiliar de horário para a _HoraMin (>= 04:00:00)
				    //#"DataHora Filtro Mínimo" = Table.AddColumn(#"Coluna _Sexo Adicionada", "_DataHoraParaMin", each 
				    //    if Time.From([Data e Hora]) >= #time(4, 0, 0) then [Data e Hora] else null, 
				    //    type datetime
				    //),
				
				    // 6. Agrupamento equivalente ao ALLEXCEPT(DINVPB_ABATE, DATA, NROEMPRESA, Turno)
				    //#"Tabela Agrupada" = Table.Group(#"DataHora Filtro Mínimo", {"DATA", "NROEMPRESA", "Turno"}, {
				    //    {"_HoraMax", each List.Max([Data e Hora]), type datetime},
				    //    {"_HoraMin", each List.Min([_DataHoraParaMin]), type datetime},
				    //    {"_Contar Linhas", each Table.RowCount(_), type number}
				    //}),
				
				    
				
				 // 5. Coluna auxiliar para _HoraMin (somente horas >= 04:00)
				    #"DataHora Filtro Mínimo" = Table.AddColumn(
				        #"Coluna _Sexo Adicionada",
				        "_DataHoraParaMin",
				        each
				            if Time.From([Data e Hora]) >= #time(4, 0, 0)
				            then [Data e Hora]
				            else null,
				        type nullable datetime
				    ),
				
				    // 5B. Data e Hora Ajustada — registros entre 00:00 e 03:59 recebem +1 dia
				    // Replica exatamente a coluna calculada DAX original "Data e Hora Ajustada"
				    #"DataHora Ajustada" = Table.AddColumn(
				        #"DataHora Filtro Mínimo",
				        "Data e Hora Ajustada",
				        each
				            let
				                hora = Time.From([Data e Hora])
				            in
				                if hora >= #time(0, 0, 0) and hora < #time(4, 0, 0)
				                then DateTime.From(Date.AddDays(Date.From([Data e Hora]), 1))
				                     + Duration.From(hora)
				                else [Data e Hora],
				        type datetime
				    ),
				
				    // 6. Agrupamento — equivalente ao ALLEXCEPT(DINVPB_ABATE, DATA, NROEMPRESA, Turno)
				    // _HoraMax usa "Data e Hora Ajustada" — igual ao DAX original
				    // _HoraMin usa "_DataHoraParaMin" — somente horas >= 04:00
				    #"Tabela Agrupada" = Table.Group(
				        #"DataHora Ajustada",
				        {"DATA", "NROEMPRESA", "Turno"},
				        {
				            {"_HoraMax",
				                each List.Max([Data e Hora Ajustada]),
				                type nullable datetime},
				            {"_HoraMin",
				                each List.Min([_DataHoraParaMin]),
				                type nullable datetime},
				            {"_Contar Linhas",
				                each Table.RowCount(_),
				                type number}
				        }
				    ),
				
				    // 7. Merge do agrupamento de volta na tabela fato principal
				    #"Mesclado Com Agrupamento" = Table.NestedJoin(
				        #"DataHora Ajustada",
				        {"DATA", "NROEMPRESA", "Turno"},
				        #"Tabela Agrupada",
				        {"DATA", "NROEMPRESA", "Turno"},
				        "TabelaAgrupada",
				        JoinKind.LeftOuter
				    ),
				
				    // 8. Expansão das colunas calculadas
				    #"Agregados Expandidos" = Table.ExpandTableColumn(
				        #"Mesclado Com Agrupamento",
				        "TabelaAgrupada",
				        {"_HoraMax", "_HoraMin", "_Contar Linhas"},
				        {"_HoraMax", "_HoraMin", "_Contar Linhas"}
				    ),
				
				    // 9. _MinutosTrabalhados = (HoraMax - HoraMin) / Contar Linhas
				    #"Coluna _MinutosTrabalhados Adicionada" = Table.AddColumn(
				        #"Agregados Expandidos",
				        "_MinutosTrabalhados",
				        each
				            if [_HoraMax] <> null
				               and [_HoraMin] <> null
				               and [_Contar Linhas] <> null
				               and [_Contar Linhas] > 0
				               and [_HoraMax] > [_HoraMin]  // ← guarda extra: garante resultado positivo
				            then Duration.TotalMinutes([_HoraMax] - [_HoraMin]) / [_Contar Linhas]
				            else 0,
				        type number
				    ),
				
				    // 10. Remove colunas temporárias
				    #"Colunas Temporarias Removidas" = Table.RemoveColumns(
				        #"Coluna _MinutosTrabalhados Adicionada",
				        {"_DataHoraParaMin", "Data e Hora Ajustada"}
				    )
				in
				    #"Colunas Temporarias Removidas"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

