table EXCEL_QUEBRADEFRIO
	lineageTag: 314d9762-9644-461e-8662-aae9e492921a

	measure '_Hora Maturação' = ```
			CALCULATE(
			    SUMX(
			    'EXCEL_QUEBRADEFRIO', 
			    DATEDIFF('EXCEL_QUEBRADEFRIO'[DTAHORA QUARTEIO], 'EXCEL_QUEBRADEFRIO'[DTAHORA ASPERSÃO / FECHAMENTO], MINUTE) / 60))
			```
		lineageTag: 799c4ec6-bc0c-47b9-ab4a-3d38cea60300

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'NRO EMPRESA'
		dataType: int64
		formatString: 0
		lineageTag: dd5f3614-739f-4303-a439-d1ed7cb1613f
		summarizeBy: none
		sourceColumn: NRO EMPRESA

		annotation SummarizationSetBy = Automatic

	column DATA
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7bf9edba-d3e6-4b7d-9672-998232df0155
		summarizeBy: none
		sourceColumn: DATA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CÂMARA
		dataType: int64
		formatString: 0
		lineageTag: 371379cb-0c30-4e50-8e97-28f13f22d0f6
		summarizeBy: sum
		sourceColumn: CÂMARA

		annotation SummarizationSetBy = Automatic

	column RECEITA
		dataType: int64
		formatString: 0
		lineageTag: 20b0c0a6-5fdb-4a5b-b196-306c9926acf5
		summarizeBy: sum
		sourceColumn: RECEITA

		annotation SummarizationSetBy = Automatic

	column 'DTAHORA ASPERSÃO / FECHAMENTO'
		dataType: dateTime
		formatString: General Date
		lineageTag: 8218683b-71d2-4b45-b30c-0b45ff9b9efc
		summarizeBy: none
		sourceColumn: DTAHORA ASPERSÃO / FECHAMENTO

		variation Variation
			isDefault
			relationship: 48a840f8-0e18-4563-b9b7-ca3e1bdfbaf8
			defaultHierarchy: LocalDateTable_1b35b7dd-bb19-4b34-9102-5ee7e661ec7e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'DTAHORA QUARTEIO'
		dataType: dateTime
		formatString: General Date
		lineageTag: 99cb2390-5806-4b6a-a0fe-862cbcc35638
		summarizeBy: none
		sourceColumn: DTAHORA QUARTEIO

		variation Variation
			isDefault
			relationship: b9f94347-429a-4e90-bb23-8651f4c7dca7
			defaultHierarchy: LocalDateTable_4c4aaf05-8b0d-494b-83e3-f94ef1d4994b.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column MATURAÇÃO
		dataType: string
		lineageTag: 2e9c2ac1-eca4-4e1b-9a4c-55c1db43052d
		summarizeBy: none
		sourceColumn: MATURAÇÃO

		annotation SummarizationSetBy = Automatic

	column 'PESO QUENTE'
		dataType: double
		lineageTag: 4346898c-8942-4043-a34e-67742012d0af
		summarizeBy: sum
		sourceColumn: PESO QUENTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PESO FRIO'
		dataType: double
		lineageTag: de880e53-f1d0-4305-a43b-7f9dd365491d
		summarizeBy: sum
		sourceColumn: PESO FRIO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'QUEBRA %'
		dataType: double
		lineageTag: bf63b6ef-eee4-4849-be7d-b75bc34fedc6
		summarizeBy: sum
		sourceColumn: QUEBRA %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'QTD. CARCAÇAS'
		dataType: int64
		formatString: 0
		lineageTag: edb49f82-de88-4d96-b4df-ba15d8808abf
		summarizeBy: sum
		sourceColumn: QTD. CARCAÇAS

		annotation SummarizationSetBy = Automatic

	column 'QTD. SEM PESAR'
		dataType: int64
		formatString: 0
		lineageTag: 9461b365-da2d-4682-bdaf-83989f3bdb69
		summarizeBy: sum
		sourceColumn: QTD. SEM PESAR

		annotation SummarizationSetBy = Automatic

	column 'QTD. PESADAS'
		dataType: int64
		formatString: 0
		lineageTag: 0d546ca5-f6dd-47c4-a99b-e60c705bb457
		summarizeBy: sum
		sourceColumn: QTD. PESADAS

		annotation SummarizationSetBy = Automatic

	column OBSERVAÇÃO
		dataType: string
		lineageTag: 3cbe4a5b-c6a4-46f8-8e82-80b3924ff043
		summarizeBy: none
		sourceColumn: OBSERVAÇÃO

		annotation SummarizationSetBy = Automatic

	partition EXCEL_QUEBRADEFRIO = m
		mode: import
		source =
				let
				    Fonte = Folder.Files("\\192.168.2.167\controladoria\05 - INDICADORES\09. Power BI\Quebra de Frio"),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(Fonte, each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo", each #"Transformar Arquivo"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo"}),
				    #"Transformar Arquivo Expandido" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo", {"BASE DE DADOS - QUEBRA DE FRIO", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18"}, {"BASE DE DADOS - QUEBRA DE FRIO", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Transformar Arquivo Expandido",{{"Nome da Origem", type text}, {"BASE DE DADOS - QUEBRA DE FRIO", type any}, {"Column2", type any}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type text}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each ([#"BASE DE DADOS - QUEBRA DE FRIO"] <> null and [#"BASE DE DADOS - QUEBRA DE FRIO"] <> "EMPRESA")),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Linhas Filtradas",{"Nome da Origem"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Removidas",{{"BASE DE DADOS - QUEBRA DE FRIO", "NRO EMPRESA"}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"NRO EMPRESA", Int64.Type}}),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"Tipo Alterado1",{{"Column2", "DATA"}}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Renomeadas2",{{"DATA", type date}}),
				    #"Colunas Renomeadas3" = Table.RenameColumns(#"Tipo Alterado2",{{"Column3", "CÂMARA"}}),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Colunas Renomeadas3",{{"CÂMARA", Int64.Type}}),
				    #"Colunas Renomeadas4" = Table.RenameColumns(#"Tipo Alterado3",{{"Column4", "RECEITA"}}),
				    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Colunas Renomeadas4",{{"RECEITA", Int64.Type}}),
				    #"Colunas Renomeadas5" = Table.RenameColumns(#"Tipo Alterado4",{{"Column5", "DTAHORA ASPERSÃO / FECHAMENTO"}, {"Column6", "DTAHORA QUARTEIO"}}),
				    #"Tipo Alterado5" = Table.TransformColumnTypes(#"Colunas Renomeadas5",{{"DTAHORA ASPERSÃO / FECHAMENTO", type datetime}, {"DTAHORA QUARTEIO", type datetime}}),
				    #"Colunas Renomeadas6" = Table.RenameColumns(#"Tipo Alterado5",{{"Column7", "MATURAÇÃO"}, {"Column8", "PESO QUENTE"}, {"Column9", "PESO FRIO"}, {"Column10", "QUEBRA %"}, {"Column11", "QTD. CARCAÇAS"}, {"Column12", "QTD. SEM PESAR"}, {"Column13", "QTD. PESADAS"}, {"Column14", "OBSERVAÇÃO"}}),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Colunas Renomeadas6",{"Column15", "Column16", "Column17", "Column18"}),
				    #"Tipo Alterado6" = Table.TransformColumnTypes(#"Colunas Removidas1",{{"PESO QUENTE", type number}, {"PESO FRIO", type number}, {"QUEBRA %", type number}, {"QTD. CARCAÇAS", Int64.Type}, {"QTD. SEM PESAR", Int64.Type}, {"QTD. PESADAS", Int64.Type}, {"OBSERVAÇÃO", type text}}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Tipo Alterado6", each true)
				in
				    #"Linhas Filtradas1"

	annotation PBI_ResultType = Table

