table EXCEL_PESOVIVOAUX
	lineageTag: 94bc2f01-9482-465e-a957-59f873a3b37f

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: a81b619a-8dab-4459-82ca-b2d6f5801d68
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Nro Empresa'
		dataType: int64
		formatString: 0
		lineageTag: 2f4b72ab-ceba-4313-aa1f-26e7fa0a995b
		summarizeBy: sum
		sourceColumn: Nro Empresa

		annotation SummarizationSetBy = Automatic

	column 'Nro Pedido'
		dataType: int64
		formatString: 0
		lineageTag: 48d9a55b-c9a7-4248-963b-3c23e8d2f062
		summarizeBy: none
		sourceColumn: Nro Pedido

		annotation SummarizationSetBy = User

	column 'Peso Vivo Graxaria'
		dataType: double
		lineageTag: 4b739a5b-3ef8-4a4b-905b-dbbad51c50e6
		summarizeBy: sum
		sourceColumn: Peso Vivo Graxaria

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition EXCEL_PESOVIVOAUX = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("\\192.168.1.203\Controladoria\Controle de Graxaria - Custo do Abate.xlsx"), null, true),
				    Planilha1_Sheet = Fonte{[Item="Planilha1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Planilha1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Data", type date}, {"Nro Empresa", Int64.Type}, {"Nro Pedido", Int64.Type}, {"Qtd Graxaria", Int64.Type}, {"Peso Vivo Graxaria", type number}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each ([Data] <> null)),
				    #"Columns removed by Measure Killer"= Table.SelectColumns(#"Linhas Filtradas",{"Peso Vivo Graxaria","Nro Pedido","Data","Nro Empresa"})
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

