table EXCEL_COMPLEMENTOAUX
	lineageTag: 3f7534a5-cb2a-4cd2-bdf7-65668a9b1abf

	column 'Data Abate'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 836f8b5c-3e67-463d-8f06-c98340932b64
		summarizeBy: none
		sourceColumn: Data Abate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Nro Pedido'
		dataType: int64
		formatString: 0
		lineageTag: 0d07aa9f-56a6-4888-b7a4-42b81f5c209d
		summarizeBy: none
		sourceColumn: Nro Pedido

		annotation SummarizationSetBy = Automatic

	column 'Valor Complemento'
		dataType: double
		lineageTag: 00406d47-d680-4de6-a003-9eb6ee29705a
		summarizeBy: sum
		sourceColumn: Valor Complemento

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nro Empresa'
		dataType: int64
		formatString: 0
		lineageTag: 875aac0a-bb20-48b1-a3b1-4a832b61dc80
		summarizeBy: sum
		sourceColumn: Nro Empresa

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition EXCEL_COMPLEMENTOAUX = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("\\192.168.1.203\controladoria\Planilha de Complemento - Custo do Abate.xlsx"), null, true),
				    Planilha1_Sheet = Fonte{[Item="Planilha1",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Planilha1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Data Abate", type date}, {"Nro Pedido", Int64.Type}, {"Valor Complemento", type number}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each [Data Abate] <> null and [Data Abate] <> "")
				in
				    #"Linhas Filtradas"

	annotation PBI_ResultType = Table

