table EXCEL_METAS
	lineageTag: ecfa539a-2136-40af-b36a-d5564c3f9bc2

	column Indicador
		dataType: string
		lineageTag: ac44fbcb-3490-412e-85da-0aeca2d97381
		summarizeBy: none
		sourceColumn: Indicador

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: int64
		formatString: 0
		lineageTag: 9a5e7131-ae59-4f5e-a5ff-689923d190db
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column Turno
		dataType: string
		lineageTag: 142ec519-1283-4b85-9dda-5c92d28eb2d5
		summarizeBy: none
		sourceColumn: Turno

		annotation SummarizationSetBy = Automatic

	column TipoMeta
		dataType: int64
		formatString: 0
		lineageTag: 6fd20901-9fe9-40af-86fa-0b80b0fc7a19
		summarizeBy: sum
		sourceColumn: TipoMeta

		annotation SummarizationSetBy = Automatic

	column Regra
		dataType: string
		lineageTag: 22650b80-75cf-49a8-975b-8bac730dce72
		summarizeBy: none
		sourceColumn: Regra

		annotation SummarizationSetBy = Automatic

	column %Aceitavel
		dataType: double
		lineageTag: cf56f48a-11d6-4c88-a72f-a1087862f6a6
		summarizeBy: sum
		sourceColumn: %Aceitavel

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Data
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 593a2a11-5bd8-4b1b-8029-91987b340526
		summarizeBy: none
		sourceColumn: Data

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column VlrMeta
		dataType: double
		lineageTag: 13cbb0a8-7772-4142-85d5-cfee8ceea666
		summarizeBy: sum
		sourceColumn: VlrMeta

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition EXCEL_METAS = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("\\192.168.2.167\CONTROLADORIA\01 - RELATÓRIOS GERAIS\2026\TRAB 009 - Indicadores Produção Meta - Realizado (Rafael)\BI\MetsIndicadores.xlsx"), null, true),
				    EXCEL_METAS_Sheet = Fonte{[Item="EXCEL_METAS",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(EXCEL_METAS_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"IDMeta", type text}, {"Ano", Int64.Type}, {"VigenciaInicio", type date}, {"VigenciaFim", type date}, {"Ativa", type logical}, {"Indicador", type text}, {"Setor", type text}, {"FILIAL", Int64.Type}, {"Turno", type text}, {"Valor", type number}, {"TipoMeta", Int64.Type}}),
				    #"Columns removed by Measure Killer"= Table.SelectColumns(#"Tipo Alterado",{"%Aceitavel","Data","Indicador","VlrMeta","FILIAL","Turno","Regra","TipoMeta"})
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

