table FPBI_FUNCIONARIO
	lineageTag: 9fbf27f1-b5ca-49bc-9fa0-1dd1ee806cbb

	column NROEMPRESA
		dataType: double
		lineageTag: 5c40aa85-59c0-4dcb-83f4-b54ed267344d
		summarizeBy: sum
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CODFUNCIONARIO
		dataType: double
		lineageTag: 07aa7298-bc64-49dd-85be-5f2117e35132
		summarizeBy: sum
		sourceColumn: CODFUNCIONARIO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NOME
		dataType: string
		lineageTag: 9f42b7d4-404f-4e86-b20e-154c8c72c40c
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column DTAADMISSAO
		dataType: dateTime
		formatString: General Date
		lineageTag: 6d78de8e-3554-4aa4-8a08-947e20a7ae22
		summarizeBy: none
		sourceColumn: DTAADMISSAO

		variation Variation
			isDefault
			relationship: 01605ab9-e6fb-4671-a9ca-fd1833f06dec
			defaultHierarchy: LocalDateTable_2f21e5a7-5ce2-4036-836b-8842768446ef.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column FUNCAO
		dataType: string
		lineageTag: 069ab451-6e51-496a-92da-08147c2b758f
		summarizeBy: none
		sourceColumn: FUNCAO

		annotation SummarizationSetBy = Automatic

	column SITUACAO
		dataType: string
		lineageTag: e87d762e-8919-4b6d-9b8c-950781207e47
		summarizeBy: none
		sourceColumn: SITUACAO

		annotation SummarizationSetBy = Automatic

	column CODDEPARTAMENTO
		dataType: double
		lineageTag: 14efeca0-d889-4b75-889f-369b656f6944
		summarizeBy: sum
		sourceColumn: CODDEPARTAMENTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DESCRDEPARTAMENTO
		dataType: string
		lineageTag: 50dd24bc-6f1f-40f3-abde-6d18ea76d782
		summarizeBy: none
		sourceColumn: DESCRDEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	column CODSETOR
		dataType: double
		lineageTag: b9ffe040-d4cd-4750-b912-86eb49085988
		summarizeBy: sum
		sourceColumn: CODSETOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DESCRSETOR
		dataType: string
		lineageTag: 7fda9f2e-edf5-4d0c-a314-954966755052
		summarizeBy: none
		sourceColumn: DESCRSETOR

		annotation SummarizationSetBy = Automatic

	column CODSECAO
		dataType: double
		lineageTag: 19d86022-d7e7-4de8-bc64-9bcd22a196de
		summarizeBy: sum
		sourceColumn: CODSECAO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DESCRSECAO
		dataType: string
		lineageTag: afe2af9c-9882-4a48-b790-a95d0580eddc
		summarizeBy: none
		sourceColumn: DESCRSECAO

		annotation SummarizationSetBy = Automatic

	column SITUACAOATUAL
		dataType: string
		lineageTag: afddda0f-12c8-449c-ba7c-027931fc94e3
		summarizeBy: none
		sourceColumn: SITUACAOATUAL

		annotation SummarizationSetBy = Automatic

	column DTADEMISSAO
		dataType: dateTime
		formatString: General Date
		lineageTag: e4788333-cc4b-4179-9684-ac29f223da3b
		summarizeBy: none
		sourceColumn: DTADEMISSAO

		variation Variation
			isDefault
			relationship: f4a885b4-8945-44ed-9034-fcc26bf91da0
			defaultHierarchy: LocalDateTable_84cd189a-2e9a-41c4-a837-12cf6abdc790.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column SEQPESSOA
		dataType: double
		lineageTag: d687fb10-293c-40a3-a78e-9bcf4afdde49
		summarizeBy: sum
		sourceColumn: SEQPESSOA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NROPLANTADEPTO
		dataType: double
		lineageTag: 9e13174b-7f19-4d6d-b11c-e01cf33a17e5
		summarizeBy: sum
		sourceColumn: NROPLANTADEPTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _DSSTURNO
		dataType: string
		lineageTag: db218e15-be2d-4c1e-9460-9fd6f33e4c3a
		summarizeBy: none
		sourceColumn: _DSSTURNO

		annotation SummarizationSetBy = Automatic

	column _UK = FPBI_FUNCIONARIO[NROEMPRESA]&"-"&FPBI_FUNCIONARIO[CODFUNCIONARIO]
		lineageTag: 11e6d708-d8e5-4ccf-bef1-de841be44d7b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Turno
		dataType: string
		lineageTag: 8e3ddee6-1357-499d-a6ce-048fdbda84a3
		summarizeBy: none
		sourceColumn: _Turno

		annotation SummarizationSetBy = Automatic

	partition FPBI_FUNCIONARIO = m
		mode: import
		queryGroup: 'Ponto Funcionário'
		source =
				let
				    Fonte = Oracle.Database("DATAVALE", [HierarchicalNavigation=true]),
				    DATAVALE = Fonte{[Schema="DATAVALE"]}[Data],
				    #"Linhas Filtradas" = Table.SelectRows(DATAVALE, each ([Name] = "FPBI_FUNCIONARIO")),
				    FPBI_FUNCIONARIO = #"Linhas Filtradas"{[Name="FPBI_FUNCIONARIO"]}[Data],
				    #"Linhas Filtradas1" = Table.SelectRows(FPBI_FUNCIONARIO, each ([NROEMPRESA] = 2 or [NROEMPRESA] = 4 or [NROEMPRESA] = 12 or [NROEMPRESA] = 18 or [NROEMPRESA] = 72 or [NROEMPRESA] = 27 or [NROEMPRESA] = 104)),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Linhas Filtradas1", "_Turno", each if Text.Contains([DESCRSECAO], "NOTURNO") then "NOTURNO" else if Text.Contains([DESCRSETOR], "NOTURNO") then "NOTURNO" else if Text.Contains([DESCRSECAO], "NOTURNA") then "NOTURNO" else if Text.Contains([DESCRSETOR], "NOTURNA") then "NOTURNO" else if Text.Contains([DESCRSECAO], "1º TURNO") then "DIURNO" else if Text.Contains([DESCRSECAO], "2º TURNO") then "NOTURNO" else if Text.Contains([DESCRSECAO], "3º TURNO") then "NOTURNO" else "DIURNO"),
				    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Coluna Condicional Adicionada", "_DSSTURNO", each if [DESCRSECAO] = "DESOSSA NOTURNA" then "NOTURNA" else if [DESCRSECAO] = "CAIXARIA NOTURNA" then "NOTURNA" else if [DESCRSECAO] = "P094 REINSPEÇÃO" then "NOTURNA" else if [DESCRSECAO] = "P098 DESOSSA TRASEIRO" then "NOTURNA" else if [DESCRSECAO] = "P101 EMBALAGENS PEÇAS CARNE" then "NOTURNA" else "DIURNA"),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada1",{{"_Turno", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Exception

