table FPBI_CORTESPEDIDOS
	lineageTag: 831c97a3-7875-49d4-8bc7-e3e69c27c416

	measure '_QtdPed Correto' = SUM(FPBI_CORTESPEDIDOS[QTD PEDIDO REAL])
		lineageTag: c6c5ac39-5469-48aa-a1a9-34c57af6c33c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _QtdCorte = [_QtdPed Correto]-[_Qtd Expedida]
		lineageTag: 90af47d6-9b45-4857-8fd2-dfb2a889431e

	measure '_Qtd Expedida' = SUM(FPBI_CORTESPEDIDOS[QTDEXPEDIDA])
		lineageTag: eae4ad05-a857-4686-a2cf-a05053d49a2a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _PesoCorte = ```
			
			    SUM(FPBI_CORTESPEDIDOS[Corte de Peso])
			```
		lineageTag: 8ed9deb4-9fee-4b3e-a519-5da2338f25b8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Peso Pedido' = SUM(FPBI_CORTESPEDIDOS[PESO PEDIDO REAL])
		lineageTag: 8ece35ab-1f62-4233-8675-dafc4017102c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Peso Expedido' = SUM(FPBI_CORTESPEDIDOS[PESOEXPEDIDO])
		lineageTag: 4fdab02c-0eab-4792-8185-21b82addba8c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NROPLANTA
		dataType: int64
		formatString: 0
		lineageTag: bbebf567-8fa2-45de-abf3-890886245be9
		summarizeBy: none
		sourceColumn: NROPLANTA

		annotation SummarizationSetBy = Automatic

	column SEQPRODUTO
		dataType: int64
		formatString: 0
		lineageTag: 65126c7a-de5e-4223-b107-f7e337708d60
		summarizeBy: none
		sourceColumn: SEQPRODUTO

		annotation SummarizationSetBy = Automatic

	column DESCRPRODUTO
		dataType: string
		lineageTag: fa28c91c-5850-42bf-927a-3a6e73cc25f0
		summarizeBy: none
		sourceColumn: DESCRPRODUTO

		annotation SummarizationSetBy = Automatic

	column UNIDADE
		dataType: string
		lineageTag: 1c629454-97de-4889-b99d-a2684c5e51b0
		summarizeBy: none
		sourceColumn: UNIDADE

		annotation SummarizationSetBy = Automatic

	column NROPEDIDO
		dataType: int64
		formatString: 0
		lineageTag: 0b4b527f-f076-468d-b323-258f2636817e
		summarizeBy: sum
		sourceColumn: NROPEDIDO

		annotation SummarizationSetBy = Automatic

	column DTAEMBARQUE
		dataType: dateTime
		formatString: General Date
		lineageTag: 422b0e7e-dc1d-4fab-b249-22c0a3783e56
		summarizeBy: none
		sourceColumn: DTAEMBARQUE

		annotation SummarizationSetBy = Automatic

	column SEQVENDEDOR
		dataType: int64
		formatString: 0
		lineageTag: b00ba837-1a1c-4418-ac97-fa55450373b5
		summarizeBy: sum
		sourceColumn: SEQVENDEDOR

		annotation SummarizationSetBy = Automatic

	column SEQCLIENTE
		dataType: int64
		formatString: 0
		lineageTag: 06033878-9172-421a-8a38-dbb9e6cf3864
		summarizeBy: sum
		sourceColumn: SEQCLIENTE

		annotation SummarizationSetBy = Automatic

	column QTDPEDIDA
		dataType: double
		lineageTag: b5d19019-e7b0-40b4-a274-275c1f1a2ced
		summarizeBy: sum
		sourceColumn: QTDPEDIDA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PESOPEDIDO
		dataType: double
		lineageTag: 978308d6-8915-40ec-93e2-b10a0eccbed5
		summarizeBy: sum
		sourceColumn: PESOPEDIDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PESOMEDIO
		dataType: double
		lineageTag: 33c26a5b-a6e0-44bc-9170-d4db200eeb1d
		summarizeBy: sum
		sourceColumn: PESOMEDIO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QTDEXPEDIDA
		dataType: double
		lineageTag: cbd58ad9-4b68-4652-8165-9dc04f8d0e60
		summarizeBy: sum
		sourceColumn: QTDEXPEDIDA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PESOEXPEDIDO
		dataType: double
		lineageTag: 3af4c9cc-87f0-4369-b3e2-2abdc8ea4b9e
		summarizeBy: sum
		sourceColumn: PESOEXPEDIDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Chave = FPBI_CORTESPEDIDOS[NROPEDIDO]&FPBI_CORTESPEDIDOS[NROPLANTA]
		lineageTag: 923f9890-7250-44bd-b139-a9f3ad391eb4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Num.Semana' = WEEKNUM(FPBI_CORTESPEDIDOS[DTAEMBARQUE])
		formatString: 0
		lineageTag: fd912821-d7e4-4263-8a76-214e25c0789f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Mês = MONTH(FPBI_CORTESPEDIDOS[DTAEMBARQUE])
		formatString: 0
		lineageTag: d772f0cb-3dca-4158-a6f8-22be4f47a02f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'PESO PEDIDO REAL' = ```
			
			SWITCH(
			    TRUE(), 
			    FPBI_CORTESPEDIDOS[UNIDADE] IN {"MC", "UN"}, FPBI_CORTESPEDIDOS[QTDPEDIDA],
			    FPBI_CORTESPEDIDOS[PESOPEDIDO] = 0 && FPBI_CORTESPEDIDOS[QTDPEDIDA] > 0 , FPBI_CORTESPEDIDOS[PESOMEDIO] * FPBI_CORTESPEDIDOS[QTDPEDIDA], FPBI_CORTESPEDIDOS[PESOPEDIDO])
			```
		lineageTag: c6366da9-cefa-4c5a-83d5-5560a73cdd5f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'QTD PEDIDO REAL' =
			
			IF(
			    FPBI_CORTESPEDIDOS[QTDPEDIDA] = 0 , ROUND( DIVIDE(FPBI_CORTESPEDIDOS[PESOPEDIDO], FPBI_CORTESPEDIDOS[PESOMEDIO]), 0), FPBI_CORTESPEDIDOS[QTDPEDIDA])
		lineageTag: 32386ec7-6abe-4b8d-b451-13877c6dccb0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Corte de QTD' = FPBI_CORTESPEDIDOS[QTD PEDIDO REAL] - FPBI_CORTESPEDIDOS[QTDEXPEDIDA]
		lineageTag: c5a0bced-607b-4b5c-ba4c-23631be88701
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Corte de Peso' = IF(FPBI_CORTESPEDIDOS[Corte de QTD] = 0, 0, FPBI_CORTESPEDIDOS[PESO PEDIDO REAL] - FPBI_CORTESPEDIDOS[PESOEXPEDIDO])
		lineageTag: 4065685b-dba7-4574-819b-ca4fc0ccc520
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Intercompany.' = IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=173651,"INTERCOMPANY",IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=117782,"INTERCOMPANY",IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=217785,"INTERCOMPANY",IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=100892,"INTERCOMPANY",IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=101143,"INTERCOMPANY",IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=181810,"INTERCOMPANY",IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=136591,"INTERCOMPANY",IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=233138,"INTERCOMPANY",IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=1871,"INTERCOMPANY",IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=148516,"INTERCOMPANY","VENDA"))))))))))
		lineageTag: 03e6d164-11d2-45d3-b78d-7f27dacc799b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DTAPEDIDO
		dataType: dateTime
		formatString: General Date
		lineageTag: 0b69ca18-0e9f-4bcd-a1e8-2d5616eaa724
		summarizeBy: none
		sourceColumn: DTAPEDIDO

		annotation SummarizationSetBy = Automatic

	partition FPBI_CORTESPEDIDOS = m
		mode: import
		source =
				let
				    Fonte = Oracle.Database("DATAVALE", [HierarchicalNavigation=true, CommandTimeout=#duration(0, 3, 0, 0), Query="select * from datavale.FPBI_CORTESPEDIDOS2#(lf)#(lf)where dtaembarque >= trunc(sysdate)-180"]),
				    #"Linhas Filtradas1" = Table.SelectRows(Fonte, each ([SEQPRODUTO] <> 162010 and [SEQPRODUTO] <> 14008 and [SEQPRODUTO] <> 14002 and [SEQPRODUTO] <> 51113 and [SEQPRODUTO] <> 162012 and [SEQPRODUTO] <> 13023)),
				    #"Linhas Filtradas" = Table.SelectRows(#"Linhas Filtradas1", each Text.Contains([DESCRICAO], "VENDA")),
				    #"Columns removed by Measure Killer"= Table.SelectColumns(#"Linhas Filtradas",{"NROPLANTA", "SEQPRODUTO", "DESCRPRODUTO", "UNIDADE", "NROPEDIDO", "DTAPEDIDO", "DTAEMBARQUE", "SEQVENDEDOR", "SEQCLIENTE", "QTDPEDIDA", "PESOPEDIDO", "PESOMEDIO", "QTDEXPEDIDA", "PESOEXPEDIDO"})
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

