table FPBI_PONTODIARIO
	lineageTag: e44f597d-ba81-4449-8c4a-d87b5b0bdf56

	column CODFUNCIONARIO
		dataType: double
		lineageTag: ebe71437-b894-4ea6-8a3f-4c47c7fbda70
		summarizeBy: sum
		sourceColumn: CODFUNCIONARIO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DEPARTAMENTO
		dataType: string
		lineageTag: 217cba04-82a2-4f60-812e-ef41a8de73c9
		summarizeBy: none
		sourceColumn: DEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	column SETOR
		dataType: string
		lineageTag: 5d02acfb-cde3-4aee-b335-e23aeaac5013
		summarizeBy: none
		sourceColumn: SETOR

		annotation SummarizationSetBy = Automatic

	column DATA
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4ef7090d-c823-431a-b6bb-4141e4656784
		summarizeBy: none
		sourceColumn: DATA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OCORRENCIA
		dataType: string
		lineageTag: c7bfc3d0-c51e-4f7a-97bd-9785830f776b
		summarizeBy: none
		sourceColumn: OCORRENCIA

		annotation SummarizationSetBy = Automatic

	column _Turno
		dataType: string
		lineageTag: 135e8ab9-e796-49ee-8c20-c9b53040c331
		summarizeBy: none
		sourceColumn: _Turno

		annotation SummarizationSetBy = Automatic

	column NROEMPRESA
		dataType: int64
		formatString: 0
		lineageTag: ef6fbcdc-d114-4027-b11e-508aee58706c
		summarizeBy: none
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

	column '_Verifica Dia' =
			
			VAR ABATE = CALCULATE(
			    MAX(FPBI_RESUMOABATE[DATA]),
			    FILTER(
			        FPBI_RESUMOABATE,
			        FPBI_RESUMOABATE[DATA] = FPBI_PONTODIARIO[DATA]))
			VAR DESOSSA = CALCULATE(
			    MAX(DINVPB_ENTRADADESOSSA[DTARENDIMENTO]),
			    FILTER(
			        DINVPB_ENTRADADESOSSA,
			        DINVPB_ENTRADADESOSSA[DTARENDIMENTO] = FPBI_PONTODIARIO[DATA]))
			VAR MIUDOS = CALCULATE(
			    MAX(FPBI_RESUMOABATE[DATA]),
			    FILTER(
			        FPBI_RESUMOABATE,
			        FPBI_RESUMOABATE[DATA] = FPBI_PONTODIARIO[DATA]))
			VAR INDUS = CALCULATE(
			    MAX(DINVPB_PRODUCAOINDUS[_Data]),
			    FILTER(
			        DINVPB_PRODUCAOINDUS,
			        DINVPB_PRODUCAOINDUS[_Data] = FPBI_PONTODIARIO[DATA]))
			RETURN
			IF(
			SWITCH(
			    TRUE(),
			    FPBI_PONTODIARIO[SETOR] IN {"CURRAL","POCILGA", "NATURA AREA QUENTE", "NATURA ÁREA QUENTE","NATURA AREA QUENTE","IN NATURA AREA QUENTE","TRIPARIA","BUCHARIA","ABATE","GRAXARIA"}, FPBI_PONTODIARIO[DATA] = ABATE,
			    FPBI_PONTODIARIO[SETOR] IN {"BUCHARIA", "MIUDOS", "BUCHARIA SUJA","BUCHARIA LIMPA", "BUCHARIA - LIMPA", "BUCHARIA - SUJA"}, FPBI_PONTODIARIO[DATA] = MIUDOS,
			    FPBI_PONTODIARIO[SETOR] IN {"DESOSSA", "CAIXARIA", "CORTE", "DESOSSA DIURNO", "DESOSSA NOTURNO", "CAIXARIA DIURNO", "CAIXARIA NOTURNO","DESOSSA DIURNA", "DESOSSA NOTURNA", "CAIXARIA DIURNA", "CAIXARIA NOTURNA"}, FPBI_PONTODIARIO[DATA] = DESOSSA,
			    FPBI_PONTODIARIO[DEPARTAMENTO] IN {"INDUSTRIA INDUSTRIALIZADOS","INDUSTRIA EMBUTIDOS","INDUSTRIA EMBUTIDO"}, FPBI_PONTODIARIO[DATA] = INDUS) = TRUE(), 1, 0)
		formatString: 0
		lineageTag: 827c6137-caaf-4a52-ada3-f089eac38c82
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '_Ocorrencia Novo' = ```
			SWITCH(
			    TRUE(), FPBI_PONTODIARIO[OCORRENCIA] in {"Falta", "Falta Simples","Suspensão" },"Falta/Suspensao", 
			            FPBI_PONTODIARIO[OCORRENCIA] in {"-","Compensado BH", "Folga"}, "Normal", 
			        FPBI_PONTODIARIO[OCORRENCIA])
			```
		lineageTag: 3fc21446-8b0f-4623-9dd2-c82b12da1350
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '_Turno v2' =
			
			SWITCH(
			    TRUE(),
			    FPBI_PONTODIARIO[_Turno] = "1° TURNO", "DIURNO",
			    FPBI_PONTODIARIO[_Turno] = "2° TURNO", "NOTURNO",
			    FPBI_PONTODIARIO[_Turno] = "3° TURNO", "NOTURNO")
		lineageTag: d0272631-56f4-4160-8581-3793eb1a1be0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _UK = FPBI_PONTODIARIO[NROEMPRESA]&FPBI_PONTODIARIO[CODFUNCIONARIO]
		lineageTag: c57a132b-8852-499b-b6c2-d2c7fa2b5cde
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition FPBI_PONTODIARIO = m
		mode: import
		queryGroup: 'Ponto Funcionário'
		source = ```
				let
				    // 1. Conexão e navegação direta no banco Oracle DATAVALE.FPBI_PONTODIARIO
				    Origem = Oracle.Database("datavale", [HierarchicalNavigation = true]),
				    #"Navegação 1" = Origem{[Schema = "DATAVALE"]}[Data],
				    FPBI_PONTODIARIO1 = #"Navegação 1"{[Name = "FPBI_PONTODIARIO"]}[Data],
				
				    // 2. Filtros de data e departamento
				    #"Linhas Filtradas6" = Table.SelectRows(FPBI_PONTODIARIO1, each [DATA] >= #datetime(2023, 1, 1, 0, 0, 0) and [DATA] <= #datetime(2024, 12, 31, 0, 0, 0)),
				    #"Linhas Filtradas" = Table.SelectRows(#"Linhas Filtradas6", each ([DEPARTAMENTO] = "INDUSTRIA CARNE" or [DEPARTAMENTO] = "INDUSTRIA DIRETA" or [DEPARTAMENTO] = "INDUSTRIA EMBUTIDOS" or [DEPARTAMENTO] = "INDUSTRIA INDIRETA")),
				
				    // 3. Coluna condicional _Turno
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Linhas Filtradas", "_Turno", each 
				        if Text.Contains([SECAO], "NOTURNO") then "2° TURNO" 
				        else if Text.Contains([SECAO], "2° TURNO") then "2° TURNO" 
				        else if Text.Contains([SECAO], "NOTURNA") then "2° TURNO" 
				        else if Text.Contains([SECAO], "3° TURNO") then "3° TURNO" 
				        else if Text.Contains([SETOR], "NOTURNO") then "2° TURNO" 
				        else if Text.Contains([SETOR], "NOTURNA") then "2° TURNO" 
				        else "1° TURNO", 
				        type text
				    ),
				
				    // 4. Filtro de empresas desconsideradas
				    #"Linhas Filtradas1" = Table.SelectRows(#"Coluna Condicional Adicionada", each ([EMPRESA] <> "001-FRIG.MATRIZ" and [EMPRESA] <> "020-FRIG.SERRA" and [EMPRESA] <> "105-ALIM.IJUI")),
				
				    // 5. Criação de Mês, Ano e Chave (CODFUNCIONARIO + AnoMes)
				    #"Mês Inserido" = Table.AddColumn(#"Linhas Filtradas1", "Mês", each Date.Month([DATA]), Int64.Type),
				    #"Ano Inserido" = Table.AddColumn(#"Mês Inserido", "Ano", each Date.Year([DATA]), Int64.Type),
				    #"Colunas Mescladas" = Table.CombineColumns(Table.TransformColumnTypes(#"Ano Inserido", {{"Mês", type text}, {"Ano", type text}}, "pt-BR"), {"Mês", "Ano"}, Combiner.CombineTextByDelimiter("/", QuoteStyle.None), "AnoMes"),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Mescladas", {{"AnoMes", type date}}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Tipo Alterado", "Chave", each Text.Combine({Text.From([CODFUNCIONARIO], "pt-BR"), Text.From([AnoMes], "pt-BR")}, ""), type text),
				
				    // 6. Tratamento de ConsiderarDia e conversão de data
				    #"Personalização Adicionada" = Table.AddColumn(#"Coluna Mesclada Inserida", "ConsiderarDia", each if [DATA] <= DateTime.FixedLocalNow() then 1 else 0),
				    #"Linhas Filtradas3" = Table.SelectRows(#"Personalização Adicionada", each [ConsiderarDia] = 1),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Linhas Filtradas3", {{"DATA", type date}}),
				
				    // 7. Mesclagens e filtros adicionais
				    #"Consultas Mescladas" = Table.NestedJoin(#"Tipo Alterado1", {"CODFUNCIONARIO", "DATA"}, ESTV_FUNCDIASAFASTADOS, {"CODFUNCIONARIO", "Intervalo"}, "ESTV_FUNCDIASAFASTADOS", JoinKind.LeftOuter),
				    #"ESTV_FUNCDIASAFASTADOS Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "ESTV_FUNCDIASAFASTADOS", {"CODFUNCIONARIO"}, {"CODFUNCIONARIO.1"}),
				    #"Linhas Filtradas2" = Table.SelectRows(#"ESTV_FUNCDIASAFASTADOS Expandido", each ([CODFUNCIONARIO.1] = null)),
				    #"Consultas Mescladas1" = Table.NestedJoin(#"Linhas Filtradas2", {"CODFUNCIONARIO"}, ESTV_FUNCDIASAFASTADOS, {"CODFUNCIONARIO"}, "ESTV_FUNCDIASAFASTADOS", JoinKind.LeftOuter),
				    #"Consultas Mescladas2" = Table.NestedJoin(#"Consultas Mescladas1", {"CODFUNCIONARIO"}, #"AFASTADOS ATUALMENTE", {"CODFUNCIONARIO"}, "ESTV_FUNCDIASAFASTADOS (2)", JoinKind.LeftOuter),
				    #"ESTV_FUNCDIASAFASTADOS (2) Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas2", "ESTV_FUNCDIASAFASTADOS (2)", {"CODFUNCIONARIO"}, {"CODFUNCIONARIO.2"}),
				    #"Linhas Filtradas4" = Table.SelectRows(#"ESTV_FUNCDIASAFASTADOS (2) Expandido", each ([CODFUNCIONARIO.2] = null)),
				    #"Linhas Filtradas5" = Table.SelectRows(#"Linhas Filtradas4", each [DATA] < #date(2023, 4, 1)),
				
				    // 8. Extração do número da empresa e seleção de colunas
				    #"Texto Inserido Antes do Delimitador" = Table.AddColumn(#"Linhas Filtradas5", "NROEMPRESA", each Text.BeforeDelimiter([EMPRESA], "-"), type text),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Texto Inserido Antes do Delimitador", {{"NROEMPRESA", Int64.Type}}),
				    #"Columns removed by Measure Killer" = Table.SelectColumns(#"Tipo Alterado2", {
				        "DEPARTAMENTO",
				        "OCORRENCIA",
				        "NROEMPRESA",
				        "DATA",
				        "SETOR",
				        "CODFUNCIONARIO",
				        "_Turno"
				    })
				in
				    #"Columns removed by Measure Killer"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

