table FPBI_FUNCIONARIO
	lineageTag: 9fbf27f1-b5ca-49bc-9fa0-1dd1ee806cbb

	column NROEMPRESA
		dataType: double
		lineageTag: 5c40aa85-59c0-4dcb-83f4-b54ed267344d
		summarizeBy: sum
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CODFUNCIONARIO
		dataType: double
		lineageTag: 07aa7298-bc64-49dd-85be-5f2117e35132
		summarizeBy: sum
		sourceColumn: CODFUNCIONARIO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DESCRDEPARTAMENTO
		dataType: string
		lineageTag: 50dd24bc-6f1f-40f3-abde-6d18ea76d782
		summarizeBy: none
		sourceColumn: DESCRDEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	column DESCRSETOR
		dataType: string
		lineageTag: 7fda9f2e-edf5-4d0c-a314-954966755052
		summarizeBy: none
		sourceColumn: DESCRSETOR

		annotation SummarizationSetBy = Automatic

	column _UK = FPBI_FUNCIONARIO[NROEMPRESA]&"-"&FPBI_FUNCIONARIO[CODFUNCIONARIO]
		lineageTag: 11e6d708-d8e5-4ccf-bef1-de841be44d7b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Turno
		dataType: string
		lineageTag: 8e3ddee6-1357-499d-a6ce-048fdbda84a3
		summarizeBy: none
		sourceColumn: _Turno

		annotation SummarizationSetBy = Automatic

	partition FPBI_FUNCIONARIO = m
		mode: import
		queryGroup: 'Ponto Funcionário'
		source =
				let
				    Fonte = Oracle.Database("DATAVALE", [HierarchicalNavigation=true]),
				    DATAVALE = Fonte{[Schema="DATAVALE"]}[Data],
				    #"Linhas Filtradas" = Table.SelectRows(DATAVALE, each ([Name] = "FPBI_FUNCIONARIO")),
				    FPBI_FUNCIONARIO = #"Linhas Filtradas"{[Name="FPBI_FUNCIONARIO"]}[Data],
				    #"Linhas Filtradas1" = Table.SelectRows(FPBI_FUNCIONARIO, each ([NROEMPRESA] = 2 or [NROEMPRESA] = 4 or [NROEMPRESA] = 12 or [NROEMPRESA] = 18 or [NROEMPRESA] = 72 or [NROEMPRESA] = 27 or [NROEMPRESA] = 104)),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Linhas Filtradas1", "_Turno", each if Text.Contains([DESCRSECAO], "NOTURNO") then "NOTURNO" else if Text.Contains([DESCRSETOR], "NOTURNO") then "NOTURNO" else if Text.Contains([DESCRSECAO], "NOTURNA") then "NOTURNO" else if Text.Contains([DESCRSETOR], "NOTURNA") then "NOTURNO" else if Text.Contains([DESCRSECAO], "1º TURNO") then "DIURNO" else if Text.Contains([DESCRSECAO], "2º TURNO") then "NOTURNO" else if Text.Contains([DESCRSECAO], "3º TURNO") then "NOTURNO" else "DIURNO"),
				    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Coluna Condicional Adicionada", "_DSSTURNO", each if [DESCRSECAO] = "DESOSSA NOTURNA" then "NOTURNA" else if [DESCRSECAO] = "CAIXARIA NOTURNA" then "NOTURNA" else if [DESCRSECAO] = "P094 REINSPEÇÃO" then "NOTURNA" else if [DESCRSECAO] = "P098 DESOSSA TRASEIRO" then "NOTURNA" else if [DESCRSECAO] = "P101 EMBALAGENS PEÇAS CARNE" then "NOTURNA" else "DIURNA"),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada1",{{"_Turno", type text}}),
				    #"Columns removed by Measure Killer"= Table.SelectColumns(#"Tipo Alterado",{"DESCRSETOR","DESCRDEPARTAMENTO","CODFUNCIONARIO","_Turno","NROEMPRESA"})
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

