table FPBI_PESSOA
	lineageTag: 75e3eb70-65ef-4d4e-b401-67b666196597

	column SEQPESSOA
		dataType: double
		lineageTag: 0ce3e97f-004a-4a6c-a536-ac6d1b354032
		summarizeBy: none
		sourceColumn: SEQPESSOA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NOMERAZAO
		dataType: string
		lineageTag: df4aa7f7-6fa3-4f3a-b04a-380936239d45
		summarizeBy: none
		sourceColumn: NOMERAZAO

		annotation SummarizationSetBy = Automatic

	column GRUPO
		dataType: string
		lineageTag: c72f84d0-22fc-4570-bb8a-7b0945d18dba
		summarizeBy: none
		sourceColumn: GRUPO

		annotation SummarizationSetBy = Automatic

	column _Produtor = FPBI_PESSOA[NOMERAZAO]& " - "&FPBI_PESSOA[SEQPESSOA]
		lineageTag: 319bc9d6-1b16-469b-83b0-69ffc91c2dd1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Origem = IF(or(FPBI_PESSOA[SEQPESSOA] IN { 108386 , 109457 , 164805 , 180622},FPBI_PESSOA[GRUPO] in {"INTEGRADOS - TERMINACAO","INTEGRADOS - CRECHE","INTEGRADOS - CRECHE REFUGO","INTEGRADOS - UPL", "INTEGRADOS - TERMINACAO REFUGO"}), "Próprio", IF(FPBI_PESSOA[SEQPESSOA] = 248257, "Boitel", "Terceiro"))
		lineageTag: 42deb1ee-866d-4bbb-a0c7-c96f1913c1c5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition FPBI_PESSOA = m
		mode: import
		source =
				let
				    Fonte = Oracle.Database("DATAVALE", [HierarchicalNavigation=true]),
				    DATAVALE = Fonte{[Schema="DATAVALE"]}[Data],
				    FPBI_PESSOA1 = DATAVALE{[Name="FPBI_PESSOA"]}[Data],
				    #"Columns removed by Measure Killer"= Table.SelectColumns(FPBI_PESSOA1,{"SEQPESSOA","NOMERAZAO","GRUPO"})
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

