table FPBI_TRANSBORDODEORDEM
	lineageTag: 2378ed86-d05c-4d88-a143-813a5bd804e6

	column SEQPRODUTO
		dataType: int64
		formatString: 0
		lineageTag: 883271fb-2950-41ad-b3e0-bb054f4c18eb
		summarizeBy: sum
		sourceColumn: SEQPRODUTO

		annotation SummarizationSetBy = Automatic

	column NROEMPRESA
		dataType: int64
		formatString: 0
		lineageTag: 62ce2cb6-2647-4de7-ad27-4fcdedc3e0cc
		summarizeBy: sum
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

	column DE
		dataType: int64
		formatString: 0
		lineageTag: 53071d46-c591-4d38-a39a-5f4c1f57953c
		summarizeBy: sum
		sourceColumn: DE

		annotation SummarizationSetBy = Automatic

	column _SK = FPBI_TRANSBORDODEORDEM[NROEMPRESA]&FPBI_TRANSBORDODEORDEM[DE]&FPBI_TRANSBORDODEORDEM[SEQPRODUTO]
		lineageTag: c59cbe1d-0a00-4dc1-89da-4bf2f7ebd301
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition FPBI_TRANSBORDODEORDEM = m
		mode: import
		queryGroup: 'Fluxo Industrial'
		source = ```
				let
				    // 1. Conexão SQL nativa unificando as instâncias de Transbordo de Ordem no Oracle com NROEMPRESA fixo
				    Fonte = Oracle.Database("datavale", [
				        HierarchicalNavigation = true, 
				        Query = "
				            SELECT 
				                2 AS NROEMPRESA, 
				                e.* 
				            FROM FPBI_TRANSBORDODEORDEM@dtvind02 e 
				            WHERE DTAPRODUCAO >= '01-JAN-2026'
				
				            UNION ALL
				
				            SELECT 
				                4 AS NROEMPRESA, 
				                e.* 
				            FROM FPBI_TRANSBORDODEORDEM@dtvind04 e 
				            WHERE DTAPRODUCAO >= '01-JAN-2026'
				
				            UNION ALL
				
				            SELECT 
				                104 AS NROEMPRESA, 
				                e.* 
				            FROM FPBI_TRANSBORDODEORDEM@dtvind104 e 
				            WHERE DTAPRODUCAO >= '01-JAN-2026'
				
				            UNION ALL
				
				            SELECT 
				                12 AS NROEMPRESA, 
				                e.* 
				            FROM FPBI_TRANSBORDODEORDEM@dtvind12 e 
				            WHERE DTAPRODUCAO >= '01-JAN-2026'
				        "
				    ]),
				
				    // 2. Seleção de colunas necessárias para as transformações de texto
				    #"Outras Colunas Removidas" = Table.SelectColumns(Fonte, {
				        "SEQPRODUTO", 
				        "HISTORICOENT", 
				        "QUANTIDADE", 
				        "QTDEMBALAGEM", 
				        "PESOLIQUIDO", 
				        "PESOBRUTO", 
				        "NROEMPRESA"
				    }),
				
				    // 3. Tratamentos de texto no campo HISTORICOENT
				    #"Valor Substituído" = Table.ReplaceValue(#"Outras Colunas Removidas", "Transbordo da Ordem Produção/Contrato: ", "", Replacer.ReplaceText, {"HISTORICOENT"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído", "Ordem Produção/Contrato: ‹", "", Replacer.ReplaceText, {"HISTORICOENT"}),
				    #"Valor Substituído2" = Table.ReplaceValue(#"Valor Substituído1", " / ›", "", Replacer.ReplaceText, {"HISTORICOENT"}),
				    #"Valor Substituído3" = Table.ReplaceValue(#"Valor Substituído2", ". ", "", Replacer.ReplaceText, {"HISTORICOENT"}),
				
				    // 4. Extração dos campos DE e PARA
				    #"Texto Inserido Antes do Delimitador" = Table.AddColumn(#"Valor Substituído3", "DE", each Text.BeforeDelimiter([HISTORICOENT], " para"), type text),
				    #"Texto Inserido Após o Delimitador" = Table.AddColumn(#"Texto Inserido Antes do Delimitador", "PARA", each Text.AfterDelimiter([HISTORICOENT], "para "), type text),
				    #"Texto Extraído Após o Delimitador" = Table.TransformColumns(#"Texto Inserido Após o Delimitador", {
				        {"DE", each Text.AfterDelimiter(_, " "), type text}, 
				        {"PARA", each Text.AfterDelimiter(_, " "), type text}
				    }),
				
				    // 5. Alteração de tipos de dados
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Texto Extraído Após o Delimitador", {
				        {"SEQPRODUTO", Int64.Type}, 
				        {"HISTORICOENT", type text}, 
				        {"QUANTIDADE", Int64.Type}, 
				        {"QTDEMBALAGEM", Int64.Type}, 
				        {"PESOLIQUIDO", type number}, 
				        {"PESOBRUTO", type number}, 
				        {"NROEMPRESA", Int64.Type}, 
				        {"DE", Int64.Type}, 
				        {"PARA", Int64.Type}
				    }),
				
				    // 6. Seleção final das colunas para o modelo
				    #"Columns removed by Measure Killer" = Table.SelectColumns(#"Tipo Alterado", {
				        "DE",
				        "SEQPRODUTO",
				        "NROEMPRESA"
				    })
				in
				    #"Columns removed by Measure Killer"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

