table FPBI_OCORRENCIASPEDIDOS
	lineageTag: e1c95dc5-5853-4b20-979f-7d3326e58108

	column NROPLANTA
		dataType: double
		lineageTag: 40b09849-464b-42c1-9803-9ddb27aa8010
		summarizeBy: sum
		sourceColumn: NROPLANTA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NROPEDIDO
		dataType: double
		lineageTag: 0e5e7cb3-4e7a-4f4c-b157-aa29b2ae735c
		summarizeBy: sum
		sourceColumn: NROPEDIDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Chave = FPBI_OCORRENCIASPEDIDOS[NROPEDIDO]&FPBI_OCORRENCIASPEDIDOS[NROPLANTA]
		lineageTag: e2b8e81a-12c9-4c62-8ad5-c26850e83c70
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition FPBI_OCORRENCIASPEDIDOS = m
		mode: import
		source =
				let
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true, CommandTimeout=#duration(0, 3, 0, 0)]),
				    DATAVALE = Fonte{[Schema="DATAVALE"]}[Data],
				    FPBI_OCORRENCIASPEDIDOS1 = DATAVALE{[Name="FPBI_OCORRENCIASPEDIDOS"]}[Data],
				    #"Linhas Filtradas" = Table.SelectRows(FPBI_OCORRENCIASPEDIDOS1, each ([CLASSIFICACAO] = "Alteração de Datas")),
				    #"Columns removed by Measure Killer"= Table.SelectColumns(#"Linhas Filtradas",{"NROPEDIDO","NROPLANTA"})
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Exception

