table FPBI_CORTESPEDIDOS
	lineageTag: 831c97a3-7875-49d4-8bc7-e3e69c27c416

	measure '_QtdPed Correto' = SUM(FPBI_CORTESPEDIDOS[QTD PEDIDO REAL])
		lineageTag: c6c5ac39-5469-48aa-a1a9-34c57af6c33c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _QtdCorte = [_QtdPed Correto]-[_Qtd Expedida]
		lineageTag: 90af47d6-9b45-4857-8fd2-dfb2a889431e

	measure '_Qtd Expedida' = SUM(FPBI_CORTESPEDIDOS[QTDEXPEDIDA])
		lineageTag: eae4ad05-a857-4686-a2cf-a05053d49a2a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _PesoCorte = ```
			
			    SUM(FPBI_CORTESPEDIDOS[Corte de Peso])
			```
		lineageTag: 8ed9deb4-9fee-4b3e-a519-5da2338f25b8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Peso Pedido' = SUM(FPBI_CORTESPEDIDOS[PESO PEDIDO REAL])
		lineageTag: 8ece35ab-1f62-4233-8675-dafc4017102c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Peso Expedido' = SUM(FPBI_CORTESPEDIDOS[PESOEXPEDIDO])
		lineageTag: 4fdab02c-0eab-4792-8185-21b82addba8c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NROPLANTA
		dataType: int64
		formatString: 0
		lineageTag: bbebf567-8fa2-45de-abf3-890886245be9
		summarizeBy: none
		sourceColumn: NROPLANTA

		annotation SummarizationSetBy = Automatic

	column NROCARGA
		dataType: int64
		formatString: 0
		lineageTag: a25c8442-2176-4f5f-8ae5-55da6322fff3
		summarizeBy: sum
		sourceColumn: NROCARGA

		annotation SummarizationSetBy = Automatic

	column STATUSCARGA
		dataType: int64
		formatString: 0
		lineageTag: 16da368f-8fa1-4eb5-990b-b0d9d54b4d6e
		summarizeBy: sum
		sourceColumn: STATUSCARGA

		annotation SummarizationSetBy = Automatic

	column SEQPRODUTO
		dataType: int64
		formatString: 0
		lineageTag: 65126c7a-de5e-4223-b107-f7e337708d60
		summarizeBy: none
		sourceColumn: SEQPRODUTO

		annotation SummarizationSetBy = Automatic

	column DESCRPRODUTO
		dataType: string
		lineageTag: fa28c91c-5850-42bf-927a-3a6e73cc25f0
		summarizeBy: none
		sourceColumn: DESCRPRODUTO

		annotation SummarizationSetBy = Automatic

	column UNIDADE
		dataType: string
		lineageTag: 1c629454-97de-4889-b99d-a2684c5e51b0
		summarizeBy: none
		sourceColumn: UNIDADE

		annotation SummarizationSetBy = Automatic

	column TIPOCALCULO
		dataType: string
		lineageTag: c6b7a50c-67d7-444c-9895-f5e617e20edf
		summarizeBy: none
		sourceColumn: TIPOCALCULO

		annotation SummarizationSetBy = Automatic

	column TIPOEXPEDICAO
		dataType: string
		lineageTag: af3d730c-a7eb-4241-a700-c1778cb29d3f
		summarizeBy: none
		sourceColumn: TIPOEXPEDICAO

		annotation SummarizationSetBy = Automatic

	column NROPEDIDO
		dataType: int64
		formatString: 0
		lineageTag: 0b4b527f-f076-468d-b323-258f2636817e
		summarizeBy: sum
		sourceColumn: NROPEDIDO

		annotation SummarizationSetBy = Automatic

	column DTAPEDIDO
		dataType: dateTime
		formatString: General Date
		lineageTag: adf75188-4ecb-49fb-88c3-30dda6e33730
		summarizeBy: none
		sourceColumn: DTAPEDIDO

		variation Variation
			isDefault
			relationship: c8e24cf6-74d1-448a-9be9-cb858dd69978
			defaultHierarchy: LocalDateTable_0d105b46-c0cb-4abd-a3ee-a817a325ee65.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column DTAEMBARQUE
		dataType: dateTime
		formatString: General Date
		lineageTag: 422b0e7e-dc1d-4fab-b249-22c0a3783e56
		summarizeBy: none
		sourceColumn: DTAEMBARQUE

		annotation SummarizationSetBy = Automatic

	column DTAINCLUSAO
		dataType: dateTime
		formatString: General Date
		lineageTag: 37e35db4-73a7-4a1e-b0b6-f44f202a4027
		summarizeBy: none
		sourceColumn: DTAINCLUSAO

		variation Variation
			isDefault
			relationship: 3c0ed613-52bd-4705-b55a-df0897e9a4d7
			defaultHierarchy: LocalDateTable_0c3b7d84-7b5d-4073-9057-c8c3090600cc.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column SEQVENDEDOR
		dataType: int64
		formatString: 0
		lineageTag: b00ba837-1a1c-4418-ac97-fa55450373b5
		summarizeBy: sum
		sourceColumn: SEQVENDEDOR

		annotation SummarizationSetBy = Automatic

	column SEQCLIENTE
		dataType: int64
		formatString: 0
		lineageTag: 06033878-9172-421a-8a38-dbb9e6cf3864
		summarizeBy: sum
		sourceColumn: SEQCLIENTE

		annotation SummarizationSetBy = Automatic

	column NOMECLIENTE
		dataType: string
		lineageTag: 128ead1d-49ee-444a-a329-077682e1b058
		summarizeBy: none
		sourceColumn: NOMECLIENTE

		annotation SummarizationSetBy = Automatic

	column STATUSPEDIDO
		dataType: string
		lineageTag: d4d6e98e-dba0-4ae4-8f14-d5a678de7e3f
		summarizeBy: none
		sourceColumn: STATUSPEDIDO

		annotation SummarizationSetBy = Automatic

	column STATUSCARREG
		dataType: string
		lineageTag: 0aff3f4e-216d-4c6c-a417-9b388fe69301
		summarizeBy: none
		sourceColumn: STATUSCARREG

		annotation SummarizationSetBy = Automatic

	column QTDPEDIDA
		dataType: double
		lineageTag: b5d19019-e7b0-40b4-a274-275c1f1a2ced
		summarizeBy: sum
		sourceColumn: QTDPEDIDA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PESOPEDIDO
		dataType: double
		lineageTag: 978308d6-8915-40ec-93e2-b10a0eccbed5
		summarizeBy: sum
		sourceColumn: PESOPEDIDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PESOMEDIO
		dataType: double
		lineageTag: 33c26a5b-a6e0-44bc-9170-d4db200eeb1d
		summarizeBy: sum
		sourceColumn: PESOMEDIO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QTDEXPEDIDA
		dataType: double
		lineageTag: cbd58ad9-4b68-4652-8165-9dc04f8d0e60
		summarizeBy: sum
		sourceColumn: QTDEXPEDIDA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PESOEXPEDIDO
		dataType: double
		lineageTag: 3af4c9cc-87f0-4369-b3e2-2abdc8ea4b9e
		summarizeBy: sum
		sourceColumn: PESOEXPEDIDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QTDCORTE
		dataType: double
		lineageTag: 52ef1b1c-59d4-4961-b5ca-9fdc7398e21b
		summarizeBy: sum
		sourceColumn: QTDCORTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PESOCORTE
		dataType: double
		lineageTag: 06502515-2f43-4b33-b6ba-59205bfce23b
		summarizeBy: sum
		sourceColumn: PESOCORTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QTDCORTEANT
		dataType: double
		lineageTag: a8b60b58-c9a0-406b-b3d3-085d15a90ce7
		summarizeBy: sum
		sourceColumn: QTDCORTEANT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PESOCORTEANT
		dataType: double
		lineageTag: 0e78b9f5-5443-428d-88d8-8ba5f18efde9
		summarizeBy: sum
		sourceColumn: PESOCORTEANT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DESCRICAO
		dataType: string
		lineageTag: 56a0ff8c-a11e-4726-b253-5dd90ebe1654
		summarizeBy: none
		sourceColumn: DESCRICAO

		annotation SummarizationSetBy = Automatic

	column Chave = FPBI_CORTESPEDIDOS[NROPEDIDO]&FPBI_CORTESPEDIDOS[NROPLANTA]
		lineageTag: 923f9890-7250-44bd-b139-a9f3ad391eb4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Nome Mês' = REPLACE(FORMAT(FPBI_CORTESPEDIDOS[DTAEMBARQUE],"mmm"),1,1,LEFT(UPPER(FPBI_CORTESPEDIDOS[DTAEMBARQUE].[Mês]),1))
		lineageTag: e13bbea9-085e-43ad-af48-39a5e1393c8c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Num.Semana' = WEEKNUM(FPBI_CORTESPEDIDOS[DTAEMBARQUE])
		formatString: 0
		lineageTag: fd912821-d7e4-4263-8a76-214e25c0789f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Mês = MONTH(FPBI_CORTESPEDIDOS[DTAEMBARQUE])
		formatString: 0
		lineageTag: d772f0cb-3dca-4158-a6f8-22be4f47a02f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'PESO PEDIDO REAL' = ```
			
			SWITCH(
			    TRUE(), 
			    FPBI_CORTESPEDIDOS[UNIDADE] IN {"MC", "UN"}, FPBI_CORTESPEDIDOS[QTDPEDIDA],
			    FPBI_CORTESPEDIDOS[PESOPEDIDO] = 0 && FPBI_CORTESPEDIDOS[QTDPEDIDA] > 0 , FPBI_CORTESPEDIDOS[PESOMEDIO] * FPBI_CORTESPEDIDOS[QTDPEDIDA], FPBI_CORTESPEDIDOS[PESOPEDIDO])
			```
		lineageTag: c6366da9-cefa-4c5a-83d5-5560a73cdd5f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'QTD PEDIDO REAL' =
			
			IF(
			    FPBI_CORTESPEDIDOS[QTDPEDIDA] = 0 , ROUND( DIVIDE(FPBI_CORTESPEDIDOS[PESOPEDIDO], FPBI_CORTESPEDIDOS[PESOMEDIO]), 0), FPBI_CORTESPEDIDOS[QTDPEDIDA])
		lineageTag: 32386ec7-6abe-4b8d-b451-13877c6dccb0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Corte de QTD' = FPBI_CORTESPEDIDOS[QTD PEDIDO REAL] - FPBI_CORTESPEDIDOS[QTDEXPEDIDA]
		lineageTag: c5a0bced-607b-4b5c-ba4c-23631be88701
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Corte de Peso' = IF(FPBI_CORTESPEDIDOS[Corte de QTD] = 0, 0, FPBI_CORTESPEDIDOS[PESO PEDIDO REAL] - FPBI_CORTESPEDIDOS[PESOEXPEDIDO])
		lineageTag: 4065685b-dba7-4574-819b-ca4fc0ccc520
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Intercompany.' = IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=173651,"INTERCOMPANY",IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=117782,"INTERCOMPANY",IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=217785,"INTERCOMPANY",IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=100892,"INTERCOMPANY",IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=101143,"INTERCOMPANY",IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=181810,"INTERCOMPANY",IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=136591,"INTERCOMPANY",IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=233138,"INTERCOMPANY",IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=1871,"INTERCOMPANY",IF(FPBI_CORTESPEDIDOS[SEQCLIENTE]=148516,"INTERCOMPANY","VENDA"))))))))))
		lineageTag: 03e6d164-11d2-45d3-b78d-7f27dacc799b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Mercado = IF(FPBI_CORTESPEDIDOS[MSGNATOPERACAO]="EXPORTACAO","MERCADO EXTERNO",IF(FPBI_CORTESPEDIDOS[MSGNATOPERACAO]="EXPORTACAO DE MERC. RECEBIDA C/ FIM ESP. EXPORTACAO","MERCADO EXTERNO","MERCADO INTERNO"))
		lineageTag: a7155969-7302-4274-9d08-07de7151b2d9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column MêsAno2 = FPBI_CORTESPEDIDOS[DTAPEDIDO].[MonthNo]&FPBI_CORTESPEDIDOS[DTAPEDIDO].[Ano]
		lineageTag: 26dfbdf4-5468-40c4-9fe8-749e6c7f5b8a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Chave2 = FPBI_CORTESPEDIDOS[SEQVENDEDOR]&FPBI_CORTESPEDIDOS[MêsAno2]
		lineageTag: b2284fee-5fee-4127-ae3d-9275a50a563d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition FPBI_CORTESPEDIDOS = m
		mode: import
		source =
				let
				    Fonte = Oracle.Database("DATAVALE", [HierarchicalNavigation=true, CommandTimeout=#duration(0, 3, 0, 0), Query="select * from datavale.FPBI_CORTESPEDIDOS2#(lf)#(lf)where dtaembarque >= trunc(sysdate)-180"]),
				    #"Linhas Filtradas1" = Table.SelectRows(Fonte, each ([SEQPRODUTO] <> 162010 and [SEQPRODUTO] <> 14008 and [SEQPRODUTO] <> 14002 and [SEQPRODUTO] <> 51113 and [SEQPRODUTO] <> 162012 and [SEQPRODUTO] <> 13023)),
				    #"Linhas Filtradas" = Table.SelectRows(#"Linhas Filtradas1", each Text.Contains([DESCRICAO], "VENDA"))
				in
				    #"Linhas Filtradas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

