table FPBI_RESUMOABATE
	lineageTag: b330c6d1-6d27-4a59-bf08-c27fb5eca57a

	column DATA
		dataType: dateTime
		formatString: General Date
		lineageTag: 7520a8a4-909f-4dd2-b815-e94a80a8d9da
		summarizeBy: none
		sourceColumn: DATA

		annotation SummarizationSetBy = Automatic

	column NROEMPRESA
		dataType: double
		formatString: 0
		lineageTag: 1d351a2c-76ac-40fc-b758-b0c8b7b924c1
		summarizeBy: none
		sourceColumn: NROEMPRESA

		annotation SummarizationSetBy = Automatic

	partition FPBI_RESUMOABATE-18df64a6-908e-45b6-a37e-f55881649b81 = m
		mode: import
		queryGroup: 'Fluxo Industrial'
		source =
				let
				    // 1. Conexão SQL nativa unificando as instâncias de Resumo de Abate no Oracle com NROEMPRESA fixo
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true, Query="#(lf)            SELECT #(lf)                2 as NROEMPRESA, #(lf)                e.data #(lf)            FROM FPBI_RESUMOABATE@dtvind02 e #(lf)            WHERE DATA >= '01-JAN-2026'#(lf)            #(lf)            UNION ALL#(lf)            #(lf)            SELECT #(lf)               4 as NROEMPRESA,  #(lf)                e.data #(lf)            FROM FPBI_RESUMOABATE@dtvind04 e #(lf)            WHERE DATA >= '01-JAN-2026'#(lf)            #(lf)            UNION ALL#(lf)            #(lf)            SELECT #(lf)                104 as NROEMPRESA, #(lf)                e.data #(lf)            FROM FPBI_RESUMOABATE@dtvind104 e #(lf)            WHERE DATA >= '01-JAN-2026'#(lf)            #(lf)            UNION ALL#(lf)            #(lf)            SELECT #(lf)                12 as NROEMPRESA, #(lf)                e.data #(lf)            FROM FPBI_RESUMOABATE@dtvind12 e #(lf)            WHERE DATA >= '01-JAN-2026'#(lf)        "]),
				
				    // 2. Seleção final das colunas solicitadas
				    #"Columns removed by Measure Killer" = Table.SelectColumns(Fonte, {
				        "NROEMPRESA",
				        "DATA"
				    })
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

