table OESTE
	lineageTag: 219d97ab-810e-45f0-bceb-a6554802de2b

	measure '_Volume Prod. Grax Oeste' = SUM(OESTE[VOLUME])
		lineageTag: 847bb95d-1550-466d-837b-d034c1fdbfad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EMPRESA
		dataType: int64
		formatString: 0
		lineageTag: 19dd5872-68cc-418f-abac-afa5365e4bb3
		summarizeBy: none
		sourceColumn: EMPRESA

		annotation SummarizationSetBy = Automatic

	column SEMANA
		dataType: int64
		formatString: 0
		lineageTag: 87227518-2571-40bb-883f-2b967caa09c5
		summarizeBy: sum
		sourceColumn: SEMANA

		annotation SummarizationSetBy = Automatic

	column 'DATA INÍCIO'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c971ed92-506b-4a24-9ac7-7f9d1d52137a
		summarizeBy: none
		sourceColumn: DATA INÍCIO

		variation Variation
			isDefault
			relationship: 539ad877-11e5-4612-b081-75d62546882e
			defaultHierarchy: LocalDateTable_09de61f2-6430-4af8-ab95-ca374ead8cee.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'DATA FINAL'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 20979ff8-9dd8-4474-ad32-e56f96fdde7e
		summarizeBy: none
		sourceColumn: DATA FINAL

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column VOLUME
		dataType: double
		lineageTag: a276e57b-bb62-4f82-bda3-f8b1e6261db1
		summarizeBy: sum
		sourceColumn: VOLUME

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'GRUPO PRODUTO'
		dataType: string
		lineageTag: 22ba0600-cf84-4500-b5f2-3bcdaa1788ee
		summarizeBy: none
		sourceColumn: GRUPO PRODUTO

		annotation SummarizationSetBy = Automatic

	partition OESTE = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("\\192.168.2.167\controladoria\05 - INDICADORES\09. Power BI\Volume Oeste.xlsx"), null, true),
				    OESTE_Sheet = Fonte{[Item="OESTE",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(OESTE_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"EMPRESA", Int64.Type}, {"SEMANA", Int64.Type}, {"DATA INÍCIO", type date}, {"DATA FINAL", type date}, {"VOLUME", type number}, {"GRUPO PRODUTO", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

