table OESTE
	lineageTag: 219d97ab-810e-45f0-bceb-a6554802de2b

	measure '_Volume Prod. Grax Oeste' = SUM(OESTE[VOLUME])
		lineageTag: 847bb95d-1550-466d-837b-d034c1fdbfad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EMPRESA
		dataType: int64
		formatString: 0
		lineageTag: 19dd5872-68cc-418f-abac-afa5365e4bb3
		summarizeBy: none
		sourceColumn: EMPRESA

		annotation SummarizationSetBy = Automatic

	column 'DATA FINAL'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 20979ff8-9dd8-4474-ad32-e56f96fdde7e
		summarizeBy: none
		sourceColumn: DATA FINAL

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column VOLUME
		dataType: double
		lineageTag: a276e57b-bb62-4f82-bda3-f8b1e6261db1
		summarizeBy: sum
		sourceColumn: VOLUME

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition OESTE = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("\\192.168.2.167\controladoria\05 - INDICADORES\09. Power BI\Volume Oeste.xlsx"), null, true),
				    OESTE_Sheet = Fonte{[Item="OESTE",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(OESTE_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"EMPRESA", Int64.Type}, {"SEMANA", Int64.Type}, {"DATA INÍCIO", type date}, {"DATA FINAL", type date}, {"VOLUME", type number}, {"GRUPO PRODUTO", type text}}),
				    #"Columns removed by Measure Killer"= Table.SelectColumns(#"Tipo Alterado",{"VOLUME","EMPRESA","DATA FINAL"})
				in
				    #"Columns removed by Measure Killer"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

